### PR TITLE
Fix USFM parsing bugs

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/machine/issues/228
* Add custom exception for parsing
* Fix off-by-one error
* Handle triplicate, quadruplicate, n-plicate verses *Add test to cover triplicate verse

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jPbA9EF0U8JrlipXT:-O2jPbA9EF0U8JrlipXU:bsrf7ad) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L86)):*
> ```Smalltalk
>         );
> 
>         Assert.That(rows, Has.Length.EqualTo(1));
> ```

I would check a few more things:
* That verse one text truly concatenates
* That a verse 2 is added
* That non-verse text in all three parts of verse 1 are added properly

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmParsingException.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQ5h1DChWOyFG5xCy:-O2jQ5h1DChWOyFG5xCz:b-wpv0jy) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParsingException.cs#L10)):*
> ```Smalltalk
>         public UsfmParsingException(UsfmParserState state, Exception exception)
>             : base(
>                 $"Failed to parse at line {state.LineNumber} column {state.ColumnNumber} verse ref {state.VerseRef} with surrounding tokens [{string.Join(",", state.Tokens.ToList().GetRange(Math.Max(state.Index - 3, 0), Math.Min(7, state.Tokens.Count - (state.Index - 3))).Select(t => $"{t.Text} (TokenType={t.Type})"))}]",
> ```

How does this interact with the other sources of errors?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 582 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQHS-4livAtRrnLYC:-O2jQHS-4livAtRrnLYD:b-8ubd0e) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParser.cs#L582)):*
> ```Smalltalk
>                 }
>             }
>             catch (Exception e)
> ```

Why put the try/catch here rather than in the `ProcessTokens` function?  The `ProcessToken` function is already 300 lines of code ...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmParsingException.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQ5h1DChWOyFG5xCy:-O2jQo1p-WCbGEoDMEYk:bhz3aje) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParsingException.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How does this interact with the other sources of errors?
</blockquote></details>

Ahh - no more "stack empty" errors.  Please look into the other error handling for these functions and make sure that there is no redundant information.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 582 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQHS-4livAtRrnLYC:-O2jh8frBHK0-UJ4MqF8:b-6u9lb9) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParser.cs#L582)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why put the try/catch here rather than in the `ProcessTokens` function?  The `ProcessToken` function is already 300 lines of code ...
</blockquote></details>

That's a good point. Somehow I wanted to not break the lovely simplicity of `ProcessTokens` :laughing: . Done.
___
*[`src/SIL.Machine/Corpora/UsfmParsingException.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQ5h1DChWOyFG5xCy:-O2jhI712CFoMVKN-bds:b-sq4i8p) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParsingException.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ahh - no more "stack empty" errors.  Please look into the other error handling for these functions and make sure that there is no redundant information.
</blockquote></details>

Exactly! This way, a readable error will propagate up. I couldn't see any other error handling with specific info. 
___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jPbA9EF0U8JrlipXT:-O2jisR_9FBQHyqy3hPY:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L86)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would check a few more things:
* That verse one text truly concatenates
* That a verse 2 is added
* That non-verse text in all three parts of verse 1 are added properly
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmParsingException.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQ5h1DChWOyFG5xCy:-O2k0qSR603txrKHHRAw:bb1mwwz) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParsingException.cs#L10)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Exactly! This way, a readable error will propagate up. I couldn't see any other error handling with specific info.
</blockquote></details>

In UsfmTextBase, it also calls `ProcessTokens` and uses the `ColumnNumber` among other things to propagate the error upward.  It would likely be good to remove the duplicate information from the error, even if you catch and rethrow as you have here.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParsingException.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jQ5h1DChWOyFG5xCy:-O2kPxu_A1jPKBAN8mc_:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/src/SIL.Machine/Corpora/UsfmParsingException.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

In UsfmTextBase, it also calls `ProcessTokens` and uses the `ColumnNumber` among other things to propagate the error upward.  It would likely be good to remove the duplicate information from the error, even if you catch and rethrow as you have here.
</blockquote></details>

Done.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 57 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kOq-BDPqQRWS3A9u5:-O2kOq-BDPqQRWS3A9u6:b-lq0zhi) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmParser.cs#L57)):*
> ```Smalltalk
>                 );
>                 sb.Append($"column: {parser.State.ColumnNumber}, error: '{ex.Message}'");
>                 throw new InvalidOperationException(sb.ToString(), ex);
> ```

I would rather not throw a new exception here. I want to avoid a deeply nested hierarchy of inner exceptions that can hide the initial exception. I intentionally shifted the responsibility for these types of exceptions to the classes that use the parser, so that they can add information that is relevant to their context. Also, this function is one of many ways that the `UsfmParser` class can be used. I don't want to have inconsistent exception handling. It would be better to throw this type of exception from the calling code.
___
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 396 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kQEJ27O99Pb3Tg4py:-O2kQEJ27O99Pb3Tg4pz:bdmr0wf) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L396)):*
> ```Smalltalk
>         private void PopNewTokens()
>         {
>             // if (_replace.Any())
> ```

Was this left in by accident?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 396 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kQEJ27O99Pb3Tg4py:-O2kXlQ52OiN81RF0x3t:b-uh2az7) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L396)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Was this left in by accident?
</blockquote></details>

Yes, it was - thank you! Done.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 57 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kOq-BDPqQRWS3A9u5:-O2kY3t92uLAD8eb2dyx:b9kc26t) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmParser.cs#L57)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rather not throw a new exception here. I want to avoid a deeply nested hierarchy of inner exceptions that can hide the initial exception. I intentionally shifted the responsibility for these types of exceptions to the classes that use the parser, so that they can add information that is relevant to their context. Also, this function is one of many ways that the `UsfmParser` class can be used. I don't want to have inconsistent exception handling. It would be better to throw this type of exception from the calling code.
</blockquote></details>

OK. I initially had the `ProcessToken` throwing a custom `UsfmParsingException` that gave line, column, verse ref, and token context information (that way, it's the same regardless of how it is called), but John said you weren't a fan of that either judging from an earlier PR and committed this instead. What do you suggest, @ddaspit? The way it was was pretty unhelpful. When running the `CreateUsfm` test, all you're getting is Stack empty or Index out of bounds - it would be helpful to have a more meaningful exception that can help you diagnose the issue. I mean, of course you can just use the debugger :laughing: , but it doesn't seem particularly clean.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 57 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kOq-BDPqQRWS3A9u5:-O2zWzZE7sdwFXvmgjjI:b1ptxnz) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmParser.cs#L57)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK. I initially had the `ProcessToken` throwing a custom `UsfmParsingException` that gave line, column, verse ref, and token context information (that way, it's the same regardless of how it is called), but John said you weren't a fan of that either judging from an earlier PR and committed this instead. What do you suggest, @ddaspit? The way it was was pretty unhelpful. When running the `CreateUsfm` test, all you're getting is Stack empty or Index out of bounds - it would be helpful to have a more meaningful exception that can help you diagnose the issue. I mean, of course you can just use the debugger :laughing: , but it doesn't seem particularly clean.
</blockquote></details>

Here is my concern. If we add another layer of exception handling in-between the original exception and the exception at the Serval/SIL.Machine.Corpora layer, then you end up with multiple levels of nesting (`InvalidOperationException` -> `UsfmParsingException` -> original exception). Each layer obfuscates the original exception even more. I was hoping to keep it to two levels: the original exception and the calling code exception that adds relevant contextual information.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 57 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kOq-BDPqQRWS3A9u5:-O2zaQSx54gSvzmBcQx6:b70zbja) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmParser.cs#L57)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Here is my concern. If we add another layer of exception handling in-between the original exception and the exception at the Serval/SIL.Machine.Corpora layer, then you end up with multiple levels of nesting (`InvalidOperationException` -> `UsfmParsingException` -> original exception). Each layer obfuscates the original exception even more. I was hoping to keep it to two levels: the original exception and the calling code exception that adds relevant contextual information.
</blockquote></details>

I understand - particularly in regards to having a helpful error message bubble up to the other end - you're forced to not only pass the exception into the constructor but also append the message to the  exception's message to ensure it's interpretable all the way up which is awkward. And it needs to be an `InvalidOperationException`, right? If so and if your main concern is the nesting, could we throw the `InvalidOperationException` from `ProcessTokens`? Or perhaps instead of calling `ProcessTokens` directly, overload `Parse` again to take tokens as a first argument and then that can be called `GetVersesInDocOrder`? That way, we wouldn't have to have multiple places that we're throwing this special, parsing-info-laden `InvalidOperationException`. Or is the concern that you'd like to have project information in the exception and that isn't possible from within the parser?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 57 at r4](https://reviewable.io/reviews/sillsdev/machine/229#-O2kOq-BDPqQRWS3A9u5:-O2zswIo9_qEV9g9QMbU:bsiglz7) ([raw file](https://github.com/sillsdev/machine/blob/d9d77dbde61060a965b41a601b964e088750ebd1/src/SIL.Machine/Corpora/UsfmParser.cs#L57)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I understand - particularly in regards to having a helpful error message bubble up to the other end - you're forced to not only pass the exception into the constructor but also append the message to the  exception's message to ensure it's interpretable all the way up which is awkward. And it needs to be an `InvalidOperationException`, right? If so and if your main concern is the nesting, could we throw the `InvalidOperationException` from `ProcessTokens`? Or perhaps instead of calling `ProcessTokens` directly, overload `Parse` again to take tokens as a first argument and then that can be called `GetVersesInDocOrder`? That way, we wouldn't have to have multiple places that we're throwing this special, parsing-info-laden `InvalidOperationException`. Or is the concern that you'd like to have project information in the exception and that isn't possible from within the parser?
</blockquote></details>

The calling code might have contextual information that isn't available to the parser. The corpus class adds project information to the exception. Pushing the responsibility to the calling code for how exceptions are handled allows the calling code to customize the exceptions for their specific requirements.

**Review by ddaspit — COMMENTED** [review]
I submitted a commit that adds a new `ParatextProjectTextUpdaterBase` class. It mirrors the `ParatextProjectSettingsParserBase` class and it can be used to update the USFM from a Paratext project. @Enkidu93, you will need to fill out the missing zip classes. You can follow the `ZipParatextProjectSettingsParserBase` and `ZipParatextProjectSettingsParser` classes.  This will give us a logical place to throw an exception with project information similar to what we do in `UsfmTextBase`. We will need to update Serval to use the new classes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3-9BkZ31vjNJQ7thPL:bqgxmnd)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

**Review by Enkidu93 — COMMENTED** [review]
That sounds good. I'm on it :+1:. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O39JxjxEgZ4lF56lw56:b-kj0wm0)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

**Comment by Enkidu93** [comment]
> I submitted a commit that adds a new `ParatextProjectTextUpdaterBase` class. It mirrors the `ParatextProjectSettingsParserBase` class and it can be used to update the USFM from a Paratext project. @Enkidu93, you will need to fill out the missing zip classes. You can follow the `ZipParatextProjectSettingsParserBase` and `ZipParatextProjectSettingsParser` classes. This will give us a logical place to throw an exception with project information similar to what we do in `UsfmTextBase`. We will need to update Serval to use the new classes.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3-9BkZ31vjNJQ7thPL:bqgxmnd)_ status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

What is the rationale behind having a `ZipParatextProjectTextUpdaterBase` class and a `ZipParatextProjectTextUpdater` class besides symmetry. What were you picturing having just in one or in the other, @ddaspit ?

**Comment by Enkidu93** [comment]
> > I submitted a commit that adds a new `ParatextProjectTextUpdaterBase` class. It mirrors the `ParatextProjectSettingsParserBase` class and it can be used to update the USFM from a Paratext project. @Enkidu93, you will need to fill out the missing zip classes. You can follow the `ZipParatextProjectSettingsParserBase` and `ZipParatextProjectSettingsParser` classes. This will give us a logical place to throw an exception with project information similar to what we do in `UsfmTextBase`. We will need to update Serval to use the new classes.
> > > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3-9BkZ31vjNJQ7thPL:bqgxmnd)_ status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)
> 
> What is the rationale behind having a `ZipParatextProjectTextUpdaterBase` class and a `ZipParatextProjectTextUpdater` class besides symmetry. What were you picturing having just in one or in the other, @ddaspit ?

I'll just push what I have and you can review haha.

**Review by Enkidu93 — COMMENTED** [review]
Still a draft - I'll ping when it's time for review (i.e., once I've prepped parallel PR in Serval).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3DmWR9CRn9VfoWKmc2:b-2v7n39)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

**Review by Enkidu93 — COMMENTED** [review]
@johnml1135 @ddaspit I think it's ready for review

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3I6o2UAxx2OXaYi19b:bhc6ggi)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

**Comment by Enkidu93** [comment]
Parallel PR: https://github.com/sillsdev/serval/pull/447

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r6, 1 of 4 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3JWbG6EtIqA0EtPAai:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 2 of 5 files at r6, 1 of 4 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/229#-O2jPbA9EF0U8JrlipXT:-O2k1PL2-eEX-EtyfZ1_:bc1w4r6) ([raw file](https://github.com/sillsdev/machine/blob/27180f4090ca8d723745a6e02d930d9b0e677de4/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L86)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, so the duplicates are thrown on the ground, but each non-verse

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/229#-:-O3dBxCQ8W743CUbZTL0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Pull request merged**
