### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/machine/issues/181

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/182)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/182)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/SIL.Machine.AspNetCore.Tests/SIL.Machine.AspNetCore.Tests.csproj` line 16 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXfqc_BI9k65jLwq-9:-NvXfqc_BI9k65jLwq-A:br024qy) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.AspNetCore.Tests/SIL.Machine.AspNetCore.Tests.csproj#L16)):*
> ```XML
> 
> 	<ItemGroup>
> 		<PackageReference Include="coverlet.msbuild" Version="6.0.2">
> ```

What is the difference between this package and `coverlet.collector`?
___
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 55 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgRD43723oT6LZOLZ:-NvXgRD43723oT6LZOL_:b-5b8qpt) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L55)):*
> ```Smalltalk
> 
>     [TestCase]
>     public void CompareTemplate()
> ```

I don't quite understand what this test is buying us. It seems to be mostly testing `List.Sort` and `HashSet`.
___
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 78 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgtul-AwidHJP2dh3:-NvXgtul-AwidHJP2dh4:bpkcti8) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L78)):*
> ```Smalltalk
>     [TestCase("MAT 1:0/1:esb", "MAT 1:0/1:esb/1:p", ExpectedResult = false, Description = "NonVerseParentChild")]
>     [TestCase("MAT 1:0/1:p/2:esb", "MAT 1:0/2:esb/1:p", ExpectedResult = false, Description = "NonVerseParentChild")]
>     public bool Overlaps(string ref1Str, string ref2Str)
> ```

I don't think `Overlaps` is being used, so I wanted to remove it.
___
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 99 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXghvK3GjqXumHdyd8:-NvXghvK3GjqXumHdyd9:b-4jxj79) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L99)):*
> ```Smalltalk
>             Assert.That(!ref1.Equals(obj1));
>         });
>         Assert.Throws<ArgumentException>(() => ref1.CompareTo(obj1));
> ```

This should be a separate test.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 55 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgRD43723oT6LZOLZ:-NvXtwt_78lE213qpQY7:b-ri05g5) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L55)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't quite understand what this test is buying us. It seems to be mostly testing `List.Sort` and `HashSet`.
</blockquote></details>

this tests the IComparable<ScriptureRef>.CompareTo method

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 78 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgtul-AwidHJP2dh3:-NvXukUg03JOpBkV5XWc:bss4a2b) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L78)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think `Overlaps` is being used, so I wanted to remove it.
</blockquote></details>

Removed.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 55 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgRD43723oT6LZOLZ:-NvXz0SnBB8pmgiHm26m:b-5nlszk) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L55)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We are already testing the `CompareTo` method. We can just remove these tests.
</blockquote></details>

Yes for `public int CompareTo(object obj)`, no for `int IComparable<ScriptureRef>.CompareTo(ScriptureRef other)`.  It is just a little thing, but I wanted to make sure it was covered.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/182)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs` line 55 at r1](https://reviewable.io/reviews/sillsdev/machine/182#-NvXgRD43723oT6LZOLZ:-NvYXRId71BuT-Sh6Lw6:b2huyyg) ([raw file](https://github.com/sillsdev/machine/blob/1931c13a2208814129404d4195ba757664c1303b/tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs#L55)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes for `public int CompareTo(object obj)`, no for `int IComparable<ScriptureRef>.CompareTo(ScriptureRef other)`.  It is just a little thing, but I wanted to make sure it was covered.
</blockquote></details>

If you want to test that method, then test it directly. I think it is unnecessary and only creates more tests that need to be maintained for almost no benefit. You can test it directly by referencing the instance using the interface, i.e.

```
int result = ((IComparable<ScriptureRef>)ref1).CompareTo(ref2);
```

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/182#-:-NvbKj_f2M_9_Gm4-uK_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
