### PR TITLE
Added open telemetry instrumentation

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/serval/issues/58

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/88)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
See my comments on the corresponding [Serval PR](https://github.com/sillsdev/serval/pull/137). 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/88#-:-NeolYSN8rpYY1J4uV8B:bvgrcc3)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine/88#-NeolIru6e1ad1XTMhci:-NeolIru6e1ad1XTMhcj:bu3u5r4) ([raw file](https://github.com/sillsdev/machine/blob/0ba3d1700b3ed0e931d2f6dd5613c5703d7a97f8/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj#L37)):*
> ```XML
> 		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.16" />
> 		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.14" />
> 		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.6.0" />
> ```

I would move these package references to the individual server projects, since this project has no dependency on OpenTelemetry.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Serval.EngineServer/Program.cs` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/88#-NesFDY9CTwplNlbs_ZK:-NesFDY9CTwplNlbs_ZL:b-fiixlr) ([raw file](https://github.com/sillsdev/machine/blob/aad90086ee7dce269dd16470c0b51e70d7c6d93d/src/SIL.Machine.Serval.EngineServer/Program.cs#L21)):*
> ```Smalltalk
>             .AddHttpClientInstrumentation()
>             .AddGrpcClientInstrumentation()
>             .AddSource("MongoDB.Driver.Core.Extensions.DiagnosticSources")
> ```

Doesn't this need a subscription to the mongo DB - or do I nut understand: https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources?

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.Serval.EngineServer/Program.cs` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/88#-NesFDY9CTwplNlbs_ZK:-NesKBc47HXTUiSBhw6g:b3l9f5v) ([raw file](https://github.com/sillsdev/machine/blob/aad90086ee7dce269dd16470c0b51e70d7c6d93d/src/SIL.Machine.Serval.EngineServer/Program.cs#L21)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Doesn't this need a subscription to the mongo DB - or do I nut understand: https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources?
</blockquote></details>

You are correct. I've already added that in Serval (see [the other PR](https://github.com/sillsdev/serval/pull/137)). And Machine calls that code [here](https://github.com/sillsdev/machine/blob/2340e829725d7d52769bf0ccf4281c27b18486d9/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L201C26-L201C44).

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/88#-:-NesShnZEdv9iS2EK8cI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
@johnml1135 Do you want this to be merged or would you rather I put the console exporter behind a development flag first?

**Comment by johnml1135** [comment]
Please do - I don't want it spamming production logging.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> Please do - I don't want it spamming production logging.

@johnml1135 I hadn't yet added that. I'll make another PR I guess. I'm sorry - I just got out of a long meeting.

**Pull request merged**
