### PR TITLE
Allow for write commands that are greater than 5MB.

### PR DESCRIPTION
**Pull request by johnml1135**
Fixes https://github.com/sillsdev/serval/issues/364

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/188)

### CODE REVIEW

**Comment by johnml1135** [comment]
Testing in CI was challenging, but I was able to run a test locally by hacking the test data.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/188)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine/188#-Nvhhoaq6vesS7UGMBN5:-Nvhhoaq6vesS7UGMBN6:bpetxby) ([raw file](https://github.com/sillsdev/machine/blob/629817ef3338db891073681e43180ba105e1f8f1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L62)):*
> ```Smalltalk
>             {
>                 int partNumber = _uploadResponses.Count + 1;
>                 UploadPartRequest request =
> ```

Unless I'm misunderstanding something, don't we need to shift the offset in the buffer. It looks like this code will just upload the first 5MB of the buffer over and over again.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine/188#-Nvhhoaq6vesS7UGMBN5:-NvlSE2zC4wxHOUG1Kb8:b-muy8qp) ([raw file](https://github.com/sillsdev/machine/blob/629817ef3338db891073681e43180ba105e1f8f1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L62)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Unless I'm misunderstanding something, don't we need to shift the offset in the buffer. It looks like this code will just upload the first 5MB of the buffer over and over again.
</blockquote></details>

We just use the `MemoryStream`, not the `count` and `offset` directly in the while loop.  As the  `ms` is consumed, it progresses through the data.  I verified this through manual testing.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/188#-:-Nvld-0_EDKEsCkoxATy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by Enkidu93 — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/188#-:-Nvli-OWBgX4Yb_CkUSj:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
