### PR TITLE
Run e2etests on release

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/serval/issues/100. (Currently failing E2E tests are resolved elsewhere).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`.github/workflows/ci-e2e.yml` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4YH725SL7baHOKbKG:-Ne4YH725SL7baHOKbKH:b66dhv9) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/.github/workflows/ci-e2e.yml#L7)):*
> ```YAML
>     branches: ["run_e2etests_on_release_#100"]
>   release:
>     types: [published]
> ```

I don't think we are currently publishing releases. Right now, we mark releases with tags.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 100 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4Y5_H12ZDqQ9Bh8s_:-Ne4Y5_H12ZDqQ9Bh8sa:btgy1ue) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L100)):*
> ```Smalltalk
>             {
>                 cancellationToken.ThrowIfCancellationRequested();
>                 await smtModelTrainer.SaveAsync(CancellationToken.None);
> ```

I'm confused. Wasn't this already fixed in another PR?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 100 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4Y5_H12ZDqQ9Bh8s_:-Ne4k-cw-7_-dNyutx7k:b-902uvn) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L100)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm confused. Wasn't this already fixed in another PR?
</blockquote></details>

@Enkidu93, can  you rebase this off of master?  That should clear up these artifacts.

**Comment by johnml1135** [comment]
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4kKxTEWWJCp1fNBlK):*
Can you rebase and clean up the history to be 1 or 2 commits?

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4kKxTEWWJCp1fNBlK):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you rebase and clean up the history to be 1 or 2 commits?
</blockquote></details>

OK! I can just squash and merge when the PR is approved, right?
___
*[`.github/workflows/ci-e2e.yml` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4YH725SL7baHOKbKG:-Ne8_ujf01IuhdDEjHXi:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/.github/workflows/ci-e2e.yml#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we are currently publishing releases. Right now, we mark releases with tags.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 100 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4Y5_H12ZDqQ9Bh8s_:-Ne8_yE08mvnGyF3-OGn:bwzbi3f) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L100)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@Enkidu93, can  you rebase this off of master?  That should clear up these artifacts.
</blockquote></details>

I think I've fixed this.

**Comment by johnml1135** [comment]
*[`.github/workflows/ci-e2e.yml` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4YH725SL7baHOKbKG:-Ne8n2gk9LdmrAoX8U9f:by76jkq) ([raw file](https://github.com/sillsdev/machine/blob/3fab687398ad4d5ab623675c844c45b043941ab0/.github/workflows/ci-e2e.yml#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The main release tag that would care about E2E tests is "docker_*".

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/83#-Ne4kKxTEWWJCp1fNBlK):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK! I can just squash and merge when the PR is approved, right?
</blockquote></details>

I see that you rebased - but also merged the changes in over time.  I believe that @ddaspit prefers if possible for each branch to branch off of master, and be "recreated" as a commit or 2 rebased onto master.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @Enkidu93)

___
*[`.github/workflows/ci-e2e.yml` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/83#-Ne8p20EASRP2z3RxtdI:-Ne8p20EASRP2z3RxtdJ:b-v3yaxd) ([raw file](https://github.com/sillsdev/machine/blob/7d3caaf5f35d03348e2f895644c6c1e719708b4c/.github/workflows/ci-e2e.yml#L8)):*
> ```YAML
>       - 'v*.*.*'
>   workflow_dispatch:
> ```

should be changed to docker_*

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`.github/workflows/ci-e2e.yml` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/83#-Ne8p20EASRP2z3RxtdI:-Ne93-Py-l0Z69e8QwtP:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d3caaf5f35d03348e2f895644c6c1e719708b4c/.github/workflows/ci-e2e.yml#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

should be changed to docker_*
</blockquote></details>

Done.

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
