### PR TITLE
Chapter level aspnetcore

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/167)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/167)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine/167#-Nq3DZq_1MATv1Qlvuoe:-Nq3DZq_1MATv1Qlvuof:blregts) ([raw file](https://github.com/sillsdev/machine/blob/2000ce62b3299e0fed4fd345a7748f2557b01c6c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L1)):*
> ```Smalltalk
> using System.Data;
> ```

If this is needed, it should be moved to global usings.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Usings.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/machine/167#-Nq3DmpwBhuyajnJ_Q9b:-Nq3DmpwBhuyajnJ_Q9c:b-43qhyr) ([raw file](https://github.com/sillsdev/machine/blob/2000ce62b3299e0fed4fd345a7748f2557b01c6c/tests/SIL.Machine.AspNetCore.Tests/Usings.cs#L24)):*
> ```Smalltalk
> global using SIL.Machine.Utils;
> global using SIL.ObjectModel;
> global using SIL.Scripture;
> ```

I don't think this is necessary.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/167#-:-Nq3F9Ut3cc6169hga2p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/167)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/167#-:-Nq3I09C3xH69szK_4VN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
Don't you need to update to a newer version of Serval.Grpc?

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/167#-:-Nq47PdwBFZ-pGcBWwp3:b69n8ck)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
