### PR TITLE
Fix exception when parsing USFM with an empty verse paragraph

### PR DESCRIPTION
**Pull request by ddaspit**
- fixes https://github.com/sillsdev/serval/issues/388

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/201)

### CODE REVIEW

**Comment by johnml1135** [comment]
@ddaspit - added more errors found from the sample project.  You may have a specific way you want to fix them.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM` line 5 at r2](https://reviewable.io/reviews/sillsdev/machine/201#-NyVP2cQEaRlnYSuNNJd:-NyVP2cQEaRlnYSuNNJe:b-93r7nv) ([raw file](https://github.com/sillsdev/machine/blob/0aea06daa37ec3130d9110dd8e2932cb151fb4d9/tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM#L5)):*
> ```
> \mt Matthew
> \ip An introduction to Matthew\fe + \ft This is an endnote.\fe*
> \p Here is another paragraph.
> ```

The current error is: `System.InvalidOperationException : An error occurred while parsing the text 'MAT`. Verse: MAT 1:0, offset: 179, error: 'Stack empty.'`.  I  still think that more context would be helpful - instead of people trying to count 179 tokens past the beginning of the verse (which starts exactly where?).

**Review by ddaspit — COMMENTED** [review]
Thanks for adding the errors. I will look into them.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/201#-:-NyW5-fe7WjXFh1y_AJ9:b-x40nhe)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM` line 5 at r2](https://reviewable.io/reviews/sillsdev/machine/201#-NyVP2cQEaRlnYSuNNJd:-NyVlV-S6B7IjBix6OBQ:b-55x1r) ([raw file](https://github.com/sillsdev/machine/blob/0aea06daa37ec3130d9110dd8e2932cb151fb4d9/tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The current error is: `System.InvalidOperationException : An error occurred while parsing the text 'MAT`. Verse: MAT 1:0, offset: 179, error: 'Stack empty.'`.  I  still think that more context would be helpful - instead of people trying to count 179 tokens past the beginning of the verse (which starts exactly where?).
</blockquote></details>

We could do line number and column instead of verse ref and verse offset. It would be a bit more work, since the UsfmTokenizer and UsfmParser aren't tracking line number and column, but it should be doable.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM` line 5 at r2](https://reviewable.io/reviews/sillsdev/machine/201#-NyVP2cQEaRlnYSuNNJd:-NyWihP777DcRuW_1-DE:b-4zvrnd) ([raw file](https://github.com/sillsdev/machine/blob/0aea06daa37ec3130d9110dd8e2932cb151fb4d9/tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We could do line number and column instead of verse ref and verse offset. It would be a bit more work, since the UsfmTokenizer and UsfmParser aren't tracking line number and column, but it should be doable.
</blockquote></details>

Line number and offset (along with verse ref) would be nice - let's do it.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Comment by johnml1135** [comment]
Failed GetUsfm_NonVerse_Paragraph [84 ms]

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
