### PR TITLE
Scripture range parser

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/168)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/168)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine/168#-Nq3Cm3s8ipO_i5ohiLn:-Nq3Cm3s8ipO_i5ohiLo:bhb5o19) ([raw file](https://github.com/sillsdev/machine/blob/dc07a0367475cb31ef26d6d7d1a2911f16f36194/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L1)):*
> ```Smalltalk
> using System.Data;
> ```

I don't think this change is necessary.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/168)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine/168#-Nq3Cm3s8ipO_i5ohiLn:-Nq3Dct2DdjUEPa-jgv7:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/dc07a0367475cb31ef26d6d7d1a2911f16f36194/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this change is necessary.
</blockquote></details>

Done.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine/168#-Nq3Cm3s8ipO_i5ohiLn:-Nq3DqVMEOaqjhcwTDGc:b-bp8dbh) ([raw file](https://github.com/sillsdev/machine/blob/dc07a0367475cb31ef26d6d7d1a2911f16f36194/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L1)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That just a mix-up trying to separate the changes - thank you :).

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/168#-:-Nq3DzGo3HZrTDtlu683:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
