### PR TITLE
Fixes #130

### LINKED ISSUE #130: SMT build error
This SMT build faulted in ext-QA.
```
\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'GetWordGraph'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at SIL.Machine.Utils.ObjectPool`1.GetAsync(CancellationToken cancellationToken) in /app/src/SIL.Machine/Utils/ObjectPool.cs:line 56
         at SIL.Machine.Translation.Thot.ThotSmtModel.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.Translation.Thot/ThotSmtModel.cs:line 120
         at SIL.Machine.Translation.HybridTranslationEngine.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine/Translation/HybridTranslationEngine.cs:line 208
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 127

\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: SIL.Machine.AspNetCore.Services.ClearMLMonitorService[0]
      Build faulted (6545d4793627520aa516b7eb). Error: ValueError : Task object can only be updated if created or in_progress [status=stopped fields=['hyperparams']]
```

What is going on here?

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NipuqgF9laFukq3z7st:-NipuqgF9laFukq3z7su:bo2ca9d) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L27)):*
> ```Smalltalk
>             {
>                 _logger.LogInformation(exception: ex, message: null);
>                 return null;
> ```

Does this mean that the gRPC endpoint won't return a `CANCELLED` status code?

**Comment by Enkidu93** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)_ status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)
> 
> _[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NipuqgF9laFukq3z7st:-NipuqgF9laFukq3z7su:bo2ca9d) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L27)):_
> 
> > ```smalltalk
> >             {
> >                 _logger.LogInformation(exception: ex, message: null);
> >                 return null;
> > ```
> 
> Does this mean that the gRPC endpoint won't return a `CANCELLED` status code?

Before:
image



After:

image

It returns a cancelled status code (which is wasn't before) and gets filtered on the other end. The notable difference is that it is logged as info rather than an failure.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NiqARckBm7zOTwimkqx:-NiqARckBm7zOTwimkqy:b5n4n6) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L26)):*
> ```Smalltalk
>             if (ex is OperationCanceledException)
>             {
>                 _logger.LogInformation(exception: ex, message: null);
> ```

Do we need to log this at all?
___
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NipuqgF9laFukq3z7st:-NiqAGrF1EGScV_I73zd:bl34lks) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L27)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Before:
image



After:

image

It returns a cancelled status code (which is wasn't before) and gets filtered on the other end. The notable difference is that it is logged as info rather than an failure.

</blockquote></details>

Ok, good.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NiqARckBm7zOTwimkqx:-NiqFmeq9JcS2m70V7C_:bsvd3cq) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we need to log this at all?
</blockquote></details>

@johnml1135 , you're the one who asked for it to be moved to info. Do you want this logged at all? A lower log level than info? Just ignore it?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NiqARckBm7zOTwimkqx:-NitXgG206V-9qiTysvJ:b-65trtf) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L26)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

@johnml1135 , you're the one who asked for it to be moved to info. Do you want this logged at all? A lower log level than info? Just ignore it?
</blockquote></details>

Probably instead of printing the whole exception, we can just say "this job was cancelled."  So we can know that the cancellation signal was successful. Info is fine - I don't need a stack trace though.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NiqARckBm7zOTwimkqx:-NitdhIv2W7wZ1oALVRN:b-ba7jcz) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Probably instead of printing the whole exception, we can just say "this job was cancelled."  So we can know that the cancellation signal was successful. Info is fine - I don't need a stack trace though.
</blockquote></details>

Sounds good to me.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/134#-NiqARckBm7zOTwimkqx:-NitdtVr-C7JKbieTsiq:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/9c6dee284117a8544985d59204ce2833ca32877d/src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134#-:-NitiF0mDXgrd_pbzKhR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
