### PR TITLE
default to major biblical terms

### PR DESCRIPTION
**Pull request by johnml1135**
See https://github.com/sillsdev/serval/issues/357.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/180)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/180)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs` line 91 at r2](https://reviewable.io/reviews/sillsdev/machine/180#-Nv7F2Vq-XuU2ZRnCGaL:-Nv7F2Vq-XuU2ZRnCGaM:bonzjwo) ([raw file](https://github.com/sillsdev/machine/blob/01d2bab846e8de90c20bb2d5012831cd31ea8a81/src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs#L91)):*
> ```Smalltalk
>                 biblicalTermsListSetting = "Major::BiblicalTerms.xml";
> 
>             if (biblicalTermsListSetting.Count(c => c == ':') != 2)
> ```

You can perform this check after you call `Split`, so you can avoid scanning the string twice.

```
if (parts.Length != 3)
```

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs` line 91 at r2](https://reviewable.io/reviews/sillsdev/machine/180#-Nv7F2Vq-XuU2ZRnCGaL:-Nv7JwzLAZimv31iEWJo:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/01d2bab846e8de90c20bb2d5012831cd31ea8a81/src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs#L91)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can perform this check after you call `Split`, so you can avoid scanning the string twice.

```
if (parts.Length != 3)
```
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/180)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs` line 93 at r3](https://reviewable.io/reviews/sillsdev/machine/180#-Nv7Krxd2TJ9dy50orpr:-Nv7Krxd2TJ9dy50orps:bavmri7) ([raw file](https://github.com/sillsdev/machine/blob/b26f7a94880f27a81a1b29b41bc190f914cfcf54/src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs#L93)):*
> ```Smalltalk
>             if (parts.Length != 3)
>             {
>                 throw new ArgumentException(
> ```

`InvalidOperationException` is more appropriate, since the error does not involve a method parameter.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/180#-:-Nv7ZEO-17wMwxYlmDu4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
