### PR TITLE
LT-20351: Fix LT-20351 and implement Novel Root Guesser

### PR DESCRIPTION
**Pull request by jtmaxwell3**
1) This adds a one line fix for [LT-20351](https://jira.sil.org/browse/LT-20351) proposed by Andy Black in its comments.
2) This adds a MaxUnapplications parameter to make debugging very slow words possible.
3) This implements the Novel Root Guesser requested in [LT-21911](https://jira.sil.org/browse/LT-21911) by adding lexical patterns using natural classes and some regular operators (e.g. [Seg], ([Seg]), [Seg]*).

Sorry for all of the formatting errors.  I don't have a Resharper license and I'm new to C#.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/245)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/245)* status: all files reviewed, 9 unresolved discussions (waiting on @isaac091 and @jtmaxwell3)

___
*[`src/SIL.Machine/Annotations/Annotation.cs` line 142 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7Ff7fF2-Y5W5Q2dNQC:-O7Ff7fF2-Y5W5Q2dNQD:b-id82fu) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine/Annotations/Annotation.cs#L142)):*
> ```Smalltalk
>         /// </value>
> 
>         public bool IsNaturalClass
> ```

The `Annotation` class is intended to be general-purpose. These properties are specific to HC. You can either use the `Data` property or add these properties to the `FeatureStruct`. If you add them as features, you will need to update HC's feature system, i.e. `HCFeatureSystem`.
___
*[`src/SIL.Machine.Morphology.HermitCrab/CharacterDefinitionTable.cs` line 138 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FelmN0eoKzsV36oZ1:-O7FelmN0eoKzsV36oZ2:brx7ckq) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/CharacterDefinitionTable.cs#L138)):*
> ```Smalltalk
>                 // Check for pattern language.
>                 // NB: This only happens when the characters don't match.
>                 if (normalized[i] == '[')
> ```

Did you consider using a regex to parse the pattern language?
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 88 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FtX-XBEWm2iFl_1de:-O7FtX-Y7zp5v1_rVK2d:b-juytxe) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L88)):*
> ```Smalltalk
>         }
> 
>         public IList<RootAllomorph> LexicalPatterns
> ```

This should return a read-only type, such as `IEnumerable`.
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 135 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7Fsqop4C0eGqg9DyRh:-O7Fsqop4C0eGqg9DyRi:blkjhe4) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L135)):*
> ```Smalltalk
>             File.WriteAllLines("analyses.txt", lines.OrderBy(l => l));
> #endif
>             var origAnalyses = guessRoot ? analyses.ToList() : null;
> ```

Please only use `var` when the type is explicit elsewhere in the line.
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 137 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FteLn-lyQBWDv9AZH:-O7FteLo4GzYhIWLMjT2:bs7ea1b) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L137)):*
> ```Smalltalk
>             var origAnalyses = guessRoot ? analyses.ToList() : null;
>             var syntheses = Synthesize(word, analyses);
>             if (guessRoot && syntheses.Count() == 0)
> ```

C# uses lazy evaluation for LINQ functions. If you are going to iterate over an enumerable multiple times (`Count()` will iterate over the enumerable), you should first convert it to a list or array.
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 372 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7Fs9Ag1dBB1QezLjOx:-O7Fs9Ag1dBB1QezLjOy:by1qu9t) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L372)):*
> ```Smalltalk
>             IEnumerable<ShapeNode> shapeNodes = input.Shape.GetNodes(input.Range);
>             HashSet<string> shapeSet = new HashSet<string>();
>             foreach (RootAllomorph lexicalPattern in _lexicalPatterns)
> ```

Did you consider implementing this using an FSA or the `Pattern` class?
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 430 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FMwcl8tXBqoMSs4sN:-O7FMwcl8tXBqoMSs4sO:b-gu10rp) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L430)):*
> ```Smalltalk
>             if (prefix == null)
>                 prefix = new List<ShapeNode>();
>             if (pattern.Count() == p)
> ```

You should use the `Count` property.
___
*[`src/SIL.Machine.Morphology.HermitCrab/Morpher.cs` line 440 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FN-u3Ac9vFv6fDu5s:-O7FN-u3Ac9vFv6fDu5t:b-gu10rp) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/Morpher.cs#L440)):*
> ```Smalltalk
>                 // Try skipping this item in the pattern.
>                 results.AddRange(MatchNodesWithPattern(nodes, pattern, n, p + 1, false, prefix));
>             if (nodes.Count() == n)
> ```

You should use the `Count` property.
___
*[`src/SIL.Machine.Morphology.HermitCrab/XmlLanguageLoader.cs` line 720 at r2](https://reviewable.io/reviews/sillsdev/machine/245#-O7FLQrz3KwRWUcTaX_o:-O7FLQrz3KwRWUcTaX_p:blkjhe4) ([raw file](https://github.com/sillsdev/machine/blob/5522335e858fb7d15779f0ef4daac63343931df4/src/SIL.Machine.Morphology.HermitCrab/XmlLanguageLoader.cs#L720)):*
> ```Smalltalk
>             _language.NaturalClasses.Add(nc);
>             _natClasses[(string)natClassElem.Attribute("id")] = nc;
>             foreach (var table in _language.CharacterDefinitionTables)
> ```

Please only use `var` when the type is explicit elsewhere in the line.

**Comment by jtmaxwell3** [comment]
I didn't use a regular expression to find or match patterns because I wanted this to be backwards compatible with existing projects.  The characters '[', ']', '(', ')', and '*' all could be valid characters in the character table.  So, I can't tell if a lexeme with [...] in it is a pattern without analyzing the shape.  I only recognize the pattern if the lexeme would have an invalid shape otherwise.  If I have to analyze the shape anyway, it isn't hard to make the shape a pattern to match against other shapes.

I fixed the other issues.

**Comment by jtmaxwell3** [comment]
One advantage of matching the shapes rather than using a regular expression is that I unify the feature structures while matching.  So, the pattern can add some details to the lexeme being matched (such as accent marks or tones).

**Review by ddaspit — COMMENTED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/245)* status: all files reviewed, 1 unresolved discussion (waiting on @isaac091 and @jtmaxwell3)

___
*[`src/SIL.Machine/Annotations/ShapeNode.cs` line 51 at r6](https://reviewable.io/reviews/sillsdev/machine/245#-O82pF__8xKtgFBbeekE:-O82pF__8xKtgFBbeekF:b-7dlmws) ([raw file](https://github.com/sillsdev/machine/blob/ca99fe62852a5397543bcc0a868aa16c56fc82b8/src/SIL.Machine/Annotations/ShapeNode.cs#L51)):*
> ```Smalltalk
>         /// Whether this is an iterative node in a lexical pattern.
>         /// </summary>
>         public bool Iterative
> ```

You should use an extension method. See the `HermitCrabExtensions.cs` file for examples.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/245#-:-O838hEU08iUQJ3AGLQR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/245)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Pull request merged**
