### PR TITLE
Refactor models to records

### PR DESCRIPTION
**Pull request by ddaspit**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/172)

### CODE REVIEW

**Comment by johnml1135** [comment]
Why are the options not also converted?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHOZwQDXz-AfiHp7Hz:-NrHOZwR0h4wPliRcJT9:b-d6wcdd) ([raw file](https://github.com/sillsdev/machine/blob/4b72d1665eea07af754ee0bc095f471a068c311c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L87)):*
> ```Smalltalk
> 
>         Dictionary<string, int> counts = new();
>         counts["CorpusSize"] = 0;
> ```

Why is corpus size removed?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 117 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHOqBc8okv4Loz8lS0:-NrHOqBc8okv4Loz8lS1:b-hyoy0j) ([raw file](https://github.com/sillsdev/machine/blob/4b72d1665eea07af754ee0bc095f471a068c311c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L117)):*
> ```Smalltalk
>                         corpus.TrainOnTextIds.Add(keyTermsTextIds.First()); //Should only be one textId for key terms
>                     parallelCorpora.Add(parallelKeyTermsCorpus);
>                 }
> ```

Why was this removed?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 117 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHOqBc8okv4Loz8lS0:-NrHP6Vo7tzpJEjurbrV:baqtpz0) ([raw file](https://github.com/sillsdev/machine/blob/4b72d1665eea07af754ee0bc095f471a068c311c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L117)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Why was it moved below?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 171 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHPc-W1VbPRf5qdeKR:-NrHPc-W1VbPRf5qdeKS:b-lak7s3) ([raw file](https://github.com/sillsdev/machine/blob/d6c37633212e4f5f1cc06d6087330742e65f8c68/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L171)):*
> ```Smalltalk
>                         await sourceTrainWriter.WriteAsync($"{row.SourceText}\n");
>                         await targetTrainWriter.WriteAsync($"{row.TargetText}\n");
>                         trainCount++;
> ```

Is this tested?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/172)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
I was focusing on the models. We could convert the option classes to records in a future PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/172#-:-NrHSvagAP9pgHxlqoeb:bhl6r8n)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHOZwQDXz-AfiHp7Hz:-NrHTD_t8C_CNOJO4uZu:bpbmxv2) ([raw file](https://github.com/sillsdev/machine/blob/4b72d1665eea07af754ee0bc095f471a068c311c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L87)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why is corpus size removed?
</blockquote></details>

I believe that the corpus size and the train count were trying to capture the same thing.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 117 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHOqBc8okv4Loz8lS0:-NrHTO5zBwJ4xuV2X4j9:bsvl5a8) ([raw file](https://github.com/sillsdev/machine/blob/4b72d1665eea07af754ee0bc095f471a068c311c/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L117)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why was it moved below?
</blockquote></details>

The models were updated to be immutable. The old logic worked by updating a property of the model, which isn't a great idea anyway. To avoid updating the model, I moved the code below. I think the logic is clearer this way as well.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 171 at r1](https://reviewable.io/reviews/sillsdev/machine/172#-NrHPc-W1VbPRf5qdeKR:-NrHUAMV0KZU4G5zAMGU:bwfk3fn) ([raw file](https://github.com/sillsdev/machine/blob/d6c37633212e4f5f1cc06d6087330742e65f8c68/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L171)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is this tested?
</blockquote></details>

It looks like there are some unit tests for key terms.

**Comment by johnml1135** [comment]
Tracked here: https://github.com/sillsdev/machine/issues/174

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
