### PR TITLE
Strict parsing #2

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/92)

### CODE REVIEW

**Comment by johnml1135** [comment]
The build is broken - let's fix that first.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine/92#-NfGnvm6Ctcoy2yaJBOs:-NfGnvm6Ctcoy2yaJBOt:bxelrnf) ([raw file](https://github.com/sillsdev/machine/blob/01faccfb4754d5c9a29fd26d1b8b9860fc961f8c/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L62)):*
> ```Smalltalk
>             try
>             {
>                 useStrictParsing = bool.Parse((string?)buildOptionsObject?["useStrictParsing"] ?? "false");
> ```

So, strict parsing is false by default.  Is that the desire as per Damien?

**Comment by Enkidu93** [comment]
> The build is broken - let's fix that first.

That's because it requires the build_options update to Serval. It's not broken in and of itself. You can verify this locally.

**Comment by Enkidu93** [comment]
> _[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine/92#-NfGnvm6Ctcoy2yaJBOs:-NfGnvm6Ctcoy2yaJBOt:bxelrnf) ([raw file](https://github.com/sillsdev/machine/blob/01faccfb4754d5c9a29fd26d1b8b9860fc961f8c/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L62)):_
> 
> > ```smalltalk
> >             try
> >             {
> >                 useStrictParsing = bool.Parse((string?)buildOptionsObject?["useStrictParsing"] ?? "false");
> > ```
> 
> So, strict parsing is false by default. Is that the desire as per Damien?

As I understood it...See [this connected comment](https://github.com/sillsdev/serval/issues/2#issuecomment-1673926904).

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/92)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine/92#-NfGnvm6Ctcoy2yaJBOs:-NfHJSgKBI9OJWZigkrL:b-yxq55s) ([raw file](https://github.com/sillsdev/machine/blob/01faccfb4754d5c9a29fd26d1b8b9860fc961f8c/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L62)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

As I understood it...See [this connected comment](https://github.com/sillsdev/serval/issues/2#issuecomment-1673926904).
</blockquote></details>

ok.  Makes sense.  See comment in Serval about adding swagger docs about this.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 14 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/92#-:-NfI8H519LHoGL9BgxIb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
