### PR TITLE
Ignore opt break that occurs outside of a segment

### LINKED ISSUE #242: Another USFM-parsing Stack Empty
```
System.InvalidOperationException: An error occurred while parsing the text 'EXO' in project '[See me for project name]'. Verse: EXO 7:0, line: 274, character: 2, error: 'Stack empty.'
       ---> System.InvalidOperationException: Stack empty.
         at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
         at SIL.Machine.Corpora.UsfmTextBase.TextRowCollector.OptBreak(UsfmParserState state)
...
```

@johnml1135, all relevant changes are deployed to QA, correct? (This error was on QA).

### PR DESCRIPTION
**Pull request by ddaspit**
- fixes #242

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 193 at r1](https://reviewable.io/reviews/sillsdev/machine/243#-O6bvs-53Kz_jPfZUy0K:-O6bvs-53Kz_jPfZUy0L:bg28qwt) ([raw file](https://github.com/sillsdev/machine/blob/e78d2005212166b9022bdf995956a8792cdd833d/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L193)):*
> ```Smalltalk
>             @"\id MAT - Test
> \c 1
> //
> ```

I'm sure you've covered this, but just to check: The project on which this failed had a triple slash `///`. Is there any difference in meaning between that and the usual two slashes? I assume your fix will also work for the situation with the triple slash?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 193 at r1](https://reviewable.io/reviews/sillsdev/machine/243#-O6bvs-53Kz_jPfZUy0K:-O6bymuX41Qtm1U6Fkyj:b-ewnmcb) ([raw file](https://github.com/sillsdev/machine/blob/e78d2005212166b9022bdf995956a8792cdd833d/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L193)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm sure you've covered this, but just to check: The project on which this failed had a triple slash `///`. Is there any difference in meaning between that and the usual two slashes? I assume your fix will also work for the situation with the triple slash?
</blockquote></details>

The problem wasn't the triple slash, it was the fact that the opt break occurred outside of any segment. In this case, it occurred in-between the chapter marker and the paragraph.

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 193 at r1](https://reviewable.io/reviews/sillsdev/machine/243#-O6bvs-53Kz_jPfZUy0K:-O6c13ar9Y72m1a6LbeB:bjeljpp) ([raw file](https://github.com/sillsdev/machine/blob/e78d2005212166b9022bdf995956a8792cdd833d/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L193)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The problem wasn't the triple slash, it was the fact that the opt break occurred outside of any segment. In this case, it occurred in-between the chapter marker and the paragraph.
</blockquote></details>

I get that. I'm asking if the triple slash means the same thing as a normal opt break (I couldn't find anything in the USFM docs and I don't think I've run into it before) and is this fix sufficient to cover cases where markers other than the normal opt break occur outside a segment (if such markers exist).  If this triple slash means something other than a normal break, do we need to capture that? And also, if there are any other errors in the same vein as this one, it'd be nice to fix them all at once. Just confirming.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 193 at r1](https://reviewable.io/reviews/sillsdev/machine/243#-O6bvs-53Kz_jPfZUy0K:-O6c9g5OCQoGWPUPz3nq:bl7eklk) ([raw file](https://github.com/sillsdev/machine/blob/e78d2005212166b9022bdf995956a8792cdd833d/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L193)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I get that. I'm asking if the triple slash means the same thing as a normal opt break (I couldn't find anything in the USFM docs and I don't think I've run into it before) and is this fix sufficient to cover cases where markers other than the normal opt break occur outside a segment (if such markers exist).  If this triple slash means something other than a normal break, do we need to capture that? And also, if there are any other errors in the same vein as this one, it'd be nice to fix them all at once. Just confirming.
</blockquote></details>

The triple slash isn't part of USFM. Paratext will treat it like an opt break, so we should as well. Opt breaks are basically treated like text. The `Text` method already has the same check that I added, so it won't have the same issue.

**Review by Enkidu93 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 193 at r1](https://reviewable.io/reviews/sillsdev/machine/243#-O6bvs-53Kz_jPfZUy0K:-O6cKnnj1QbYXodU-Zqb:b3phih8) ([raw file](https://github.com/sillsdev/machine/blob/e78d2005212166b9022bdf995956a8792cdd833d/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L193)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The triple slash isn't part of USFM. Paratext will treat it like an opt break, so we should as well. Opt breaks are basically treated like text. The `Text` method already has the same check that I added, so it won't have the same issue.
</blockquote></details>

OK, great :lgtm:

**Review by ddaspit — COMMENTED** [review]
> Dismissed @Enkidu93 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
