### PR TITLE
Fixes ClearML server is down - and then hangfire crashes #65 --ECL

### PR DESCRIPTION
**Pull request by Enkidu93**
Also relevant to #50. 

* Used Polly to auto-retry
* Refactored `ClearMLAuthenticationService` a bit to avoid issue where token wasn't properly populating immediately
* Small fixes in the `ClearMLHealthCheck` and to logging
* (Added ".history" to the gitignore - vs code extension generates files in this folder on my box and, I presume, others)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-NdHgS2E7s7JE278MHdg:bcz8np2) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
> ```Smalltalk
>     public async Task<string> GetAuthToken(CancellationToken cancellationToken = default)
>     {
>         if (_authToken is "")
> ```

This could result in a race condition where the auth token that is returned is no longer valid. I think it would be better to move this back to the `StartAsync` method. The other option is to use an async lock.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHhNdz6Immgl7qwq2d:-NdHhNdz6Immgl7qwq2e:byk6ipg) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L29)):*
> ```Smalltalk
>         catch (Exception e)
>         {
>             _logger.LogError(
> ```

One of the overloads of the `LogError` method allows you to directly pass the exception.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-Nd_c0E72IElq9p7BF0L:b4pfz7f) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This could result in a race condition where the auth token that is returned is no longer valid. I think it would be better to move this back to the `StartAsync` method. The other option is to use an async lock.
</blockquote></details>

The issue I was having here was that if it cannot fetch the token on startup (even with the retries), then it's left waiting an hour to try again, right?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-Ndbd-edATPaLex9_Uii:b-rommiv) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

The issue I was having here was that if it cannot fetch the token on startup (even with the retries), then it's left waiting an hour to try again, right?
</blockquote></details>

Won't it fail after 3 attempts?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-Ndf0zAz9ko7IDRr28uH:b-2fz7ul) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Won't it fail after 3 attempts?
</blockquote></details>

It ought to. What happens if StartAsync throws an exception? In testing it out, I noticed that if I started everything up without internet connectivity and then turned then connected after a few minutes, it wouldn't fetch the token. I'll investigate.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHhNdz6Immgl7qwq2d:-Nd_bAcCDDKzZwJKsNK8:bh9xpxp) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

One of the overloads of the `LogError` method allows you to directly pass the exception.
</blockquote></details>

I'm not sure I'm seeing that overload. I found one that includes the exception. Let me know if this is what you wanted.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-Ndf5_PnARQvGCf2B-wg:b7xcbz3) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

It ought to. What happens if StartAsync throws an exception? In testing it out, I noticed that if I started everything up without internet connectivity and then turned then connected after a few minutes, it wouldn't fetch the token. I'll investigate.
</blockquote></details>

I'm guessing that the server will simply crash and not startup. That is probably not what we want. Let's add an async lock around the `if` statement. [`SmtTransferEngineState`](https://github.com/sillsdev/machine/blob/5e5312f5f15b9991a7703530296fd3d337eb6c3b/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineState.cs#L41) has an example of using a lock. You should also rename this method to `GetAuthTokenAsync`. This is the naming convention for async methods.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHhNdz6Immgl7qwq2d:-Ndf58Va-9vwvQE5khU9:b-ibmwj0) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L29)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure I'm seeing that overload. I found one that includes the exception. Let me know if this is what you wanted.
</blockquote></details>

[This](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object())) is the overload I am referring to.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 66 at r2](https://reviewable.io/reviews/sillsdev/machine/66#-NdfDi5o8aFz8HDNrybG:-NdfDi5o8aFz8HDNrybH:b-5ny038) ([raw file](https://github.com/sillsdev/machine/blob/bffb807cc1d021f09f71acdeff8923c29bd3f81e/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L66)):*
> ```Smalltalk
>         var base64EncodedAuthenticationString = Convert.ToBase64String(Encoding.ASCII.GetBytes(authenticationString));
>         request.Headers.Add("Authorization", $"Basic {base64EncodedAuthenticationString}");
>         HttpResponseMessage response = await _httpClient.SendAsync(request, cancellationToken);
> ```

Can you give a general explanation "this is what I am trying to do with refactoring this"?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 66 at r2](https://reviewable.io/reviews/sillsdev/machine/66#-NdfDi5o8aFz8HDNrybG:-NdfS0t0Ef2mfZa5yc3z:b-q7sns5) ([raw file](https://github.com/sillsdev/machine/blob/bffb807cc1d021f09f71acdeff8923c29bd3f81e/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L66)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you give a general explanation "this is what I am trying to do with refactoring this"?
</blockquote></details>

Failed requests are now handled by Polly. See the new http error policy that was added in `IMachineBuilderExtensions.cs`.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 66 at r2](https://reviewable.io/reviews/sillsdev/machine/66#-NdfDi5o8aFz8HDNrybG:-NdfWDCw-ntZm6yBMBoA:btih660) ([raw file](https://github.com/sillsdev/machine/blob/bffb807cc1d021f09f71acdeff8923c29bd3f81e/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L66)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Failed requests are now handled by Polly. See the new http error policy that was added in `IMachineBuilderExtensions.cs`.
</blockquote></details>

Yes, exactly.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 66 at r2](https://reviewable.io/reviews/sillsdev/machine/66#-NdfDi5o8aFz8HDNrybG:-NdfeErfCQG2eWKqmZ2q:b-3qn3gi) ([raw file](https://github.com/sillsdev/machine/blob/bffb807cc1d021f09f71acdeff8923c29bd3f81e/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L66)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Yes, exactly.
</blockquote></details>

Thanks.  I'm fine with it.

**Review by johnml1135 — COMMENTED** [review]
> Dismissed @johnml1135 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHgS2E7s7JE278MHdf:-NdfzLw6-rFcjaXRQgnM:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L28)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm guessing that the server will simply crash and not startup. That is probably not what we want. Let's add an async lock around the `if` statement. [`SmtTransferEngineState`](https://github.com/sillsdev/machine/blob/5e5312f5f15b9991a7703530296fd3d337eb6c3b/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineState.cs#L41) has an example of using a lock. You should also rename this method to `GetAuthTokenAsync`. This is the naming convention for async methods.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHhNdz6Immgl7qwq2d:-NdfzPTBE7k5dfHwJthW:b-o7tgi1) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

[This](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object())) is the overload I am referring to.
</blockquote></details>

I see. I got it now - it wasn't showing up in my IDE for some reason, but VScode has been sketchy lately I think because of some of the extensions. I do wonder if we really need to log this at all though since it's automatically logged given it's an unhealthy healthcheck response.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/66#-NdHhNdz6Immgl7qwq2d:-Ndg3sKS4dZFjIUonYXi:b-g9mp9a) ([raw file](https://github.com/sillsdev/machine/blob/3202906963c1d63baf66dbb3a27a2d2be3029117/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L29)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see. I got it now - it wasn't showing up in my IDE for some reason, but VScode has been sketchy lately I think because of some of the extensions. I do wonder if we really need to log this at all though since it's automatically logged given it's an unhealthy healthcheck response.
</blockquote></details>

I agree. We don't need this log.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs` line 31 at r4](https://reviewable.io/reviews/sillsdev/machine/66#-Ndg3LKHDOjyP3tskLrg:-Ndg3LKHDOjyP3tskLrh:bra7yo6) ([raw file](https://github.com/sillsdev/machine/blob/51214aa49382a27b51c0572397e366d3e247c24f/tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs#L31)):*
> ```Smalltalk
>         );
>         var authService = Substitute.For<IClearMLAuthenticationService>();
>         authService.GetAuthTokenAsync().Returns("accessToken");
> ```

This should return a task, i.e. `Task.FromResult("accessToken")`.

**Comment by Enkidu93** [comment]
I think that's it, @ddaspit.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66#-:-NdgJoAH1rm4bmOsrAVw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Dismissed @johnml1135 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
