### PR TITLE
Update machine version

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/183)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/AssemblyInfo.props` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/183#-NvHCvs8BrJpK9T4CpdM:-NvHCvs8BrJpK9T4CpdN:b-riqtth) ([raw file](https://github.com/sillsdev/machine/blob/d1392d3451873027fad99ba65845148b9348f092/src/AssemblyInfo.props#L6)):*
> ```XML
> 		<Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
> 		<AssemblyVersion>3.1.0.0</AssemblyVersion>
> 		<FileVersion>3.1.0.0</FileVersion>
> ```

If we are going to lock down the pull request and commits directly to main, we need to have an efficient release process that doesn't require pull requests, etc.  One option could be https://github.com/versionize/versionize?tab=readme-ov-file.  It may require a bit more research, especially looking at using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification) throughout, but it may be valuable long term.

**Comment by johnml1135** [comment]
*[`src/AssemblyInfo.props` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/183#-NvHCvs8BrJpK9T4CpdM:-NvHE1CK14Rby1bwhqGJ:bj1uung) ([raw file](https://github.com/sillsdev/machine/blob/d1392d3451873027fad99ba65845148b9348f092/src/AssemblyInfo.props#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If we are going to lock down the pull request and commits directly to main, we need to have an efficient release process that doesn't require pull requests, etc.  One option could be https://github.com/versionize/versionize?tab=readme-ov-file.  It may require a bit more research, especially looking at using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification) throughout, but it may be valuable long term.
</blockquote></details>

Actually versionize also commits directly to main - let me see if there is another way around this.

**Comment by johnml1135** [comment]
*[`src/AssemblyInfo.props` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/183#-NvHCvs8BrJpK9T4CpdM:-NvHG_8l1qSG-DdWL5-C:b-jdukkr) ([raw file](https://github.com/sillsdev/machine/blob/d1392d3451873027fad99ba65845148b9348f092/src/AssemblyInfo.props#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Actually versionize also commits directly to main - let me see if there is another way around this.
</blockquote></details>

In looking at the various options, I am inclined to think that we should just allow commits to master.  We make make explicit the convention that we have been using, namely that commits can be made directly to master for:
* Version increments and releases
* CI updates
* Documentation updates? (do we want to review these?  Are any documentation updates ok?  What about Swagger documentation, or Readme?)
  * For documentation, although I have committed documentation directly to master before, the urgency and complex dependencies for CI and versioning are not there while the importance of discretion, wording and clarity is.  Let's say that all documentation updates need a pull request.

**Comment by johnml1135** [comment]
*[`src/AssemblyInfo.props` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/183#-NvHCvs8BrJpK9T4CpdM:-NvHTJ1l1cu7GxVXdw3s:b9a87qm) ([raw file](https://github.com/sillsdev/machine/blob/d1392d3451873027fad99ba65845148b9348f092/src/AssemblyInfo.props#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

In looking at the various options, I am inclined to think that we should just allow commits to master.  We make make explicit the convention that we have been using, namely that commits can be made directly to master for:
* Version increments and releases
* CI updates
* Documentation updates? (do we want to review these?  Are any documentation updates ok?  What about Swagger documentation, or Readme?)
  * For documentation, although I have committed documentation directly to master before, the urgency and complex dependencies for CI and versioning are not there while the importance of discretion, wording and clarity is.  Let's say that all documentation updates need a pull request.
</blockquote></details>

Also, should I be an admin on Machine?

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/183#-:-NvXezetC8qC-wJPtr1N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/AssemblyInfo.props` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/183#-NvHCvs8BrJpK9T4CpdM:-NvXeVTLA3GmP2k6Tsxo:b55tot4) ([raw file](https://github.com/sillsdev/machine/blob/d1392d3451873027fad99ba65845148b9348f092/src/AssemblyInfo.props#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Also, should I be an admin on Machine?
</blockquote></details>

I'm not sure I understand the issue with using PRs. I think it makes sense that updating the version should be reviewed.

**Pull request merged**
