### PR TITLE
Language endpoint

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 2 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1frDfCshirq84i6VS:-Np1frDfCshirq84i6VT:b3b809g) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L3)):*
> ```Smalltalk
> namespace SIL.Machine.AspNetCore.Models
> {
>     public class LanguageInfoDto
> ```

This is just a model. There is no need for the `Dto` suffix.
___
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 5 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gr5T8bUUO10LU2ft:-Np1gr5T8bUUO10LU2fu:b-5i6yza) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L5)):*
> ```Smalltalk
>     public class LanguageInfoDto
>     {
>         public string Language { get; set; } = default!;
> ```

There is no need for this property. You can remove it.
___
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gsvF6aYiV52sDy4S:-Np1gsvF6aYiV52sDy4T:b-5i6yza) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L6)):*
> ```Smalltalk
>     {
>         public string Language { get; set; } = default!;
>         public string EngineType { get; set; } = default!;
> ```

There is no need for this property. You can remove it.
___
*[`src/SIL.Machine.AspNetCore/Services/ILanguageTagService.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gA3L7Qhr8O6qdagx:-Np1gA3L7Qhr8O6qdagy:b-altf3j) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/ILanguageTagService.cs#L6)):*
> ```Smalltalk
> {
>     string ConvertToFlores200Code(string languageTag);
>     LanguageInfoDto CheckInFlores200(string languageTag);
> ```

I would prefer to call this `GetFlores200LanguageInfo`
___
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 45 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1g4I66XwQwUgLarUQ:-Np1g4I66XwQwUgLarUR:bhzc5rl) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L45)):*
> ```Smalltalk
>     Task<int> GetQueueSizeAsync(CancellationToken cancellationToken = default);
> 
>     LanguageInfoDto GetlanguageInfo(string language);
> ```

You forgot to capitalize the `language`.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 70 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1iFjFEMVIg1RKwZU7:-Np1iFjFEMVIg1RKwZU8:b-hiztbh) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L70)):*
> ```Smalltalk
>         Debug.Assert(floresStream is not null);
>         var reader = new StreamReader(floresStream);
>         Debug.Assert(reader.ReadLine() == "language, code");
> ```

The `reader.ReadLine()` should not be called in a `Debug.Assert` call, because these calls are stripped out in Release builds.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1frDfCshirq84i6VS:-Np5wVTIAfsQUPtPeMcP:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is just a model. There is no need for the `Dto` suffix.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 5 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gr5T8bUUO10LU2ft:-Np5wVvq6tIE9ocVPoKt:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is no need for this property. You can remove it.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gsvF6aYiV52sDy4S:-Np5wXtp30Kef59HxauA:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Models/LanguageInfoDto.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is no need for this property. You can remove it.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ILanguageTagService.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1gA3L7Qhr8O6qdagx:-Np5wdJ-8p_MdGSrKwtY:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/ILanguageTagService.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer to call this `GetFlores200LanguageInfo`
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 45 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1g4I66XwQwUgLarUQ:-Np5wnAzCqJ41iu4Cn2o:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L45)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to capitalize the `language`.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 70 at r3](https://reviewable.io/reviews/sillsdev/machine/159#-Np1iFjFEMVIg1RKwZU7:-Np5zSWM8ZRhL3rZdWFe:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/5ad5e714521633245623a4dc9cdd288b60d5f809/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L70)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `reader.ReadLine()` should not be called in a `Debug.Assert` call, because these calls are stripped out in Release builds.
</blockquote></details>

Done.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 92 at r4](https://reviewable.io/reviews/sillsdev/machine/159#-Np6tVQH7tb8oeI5NgUR:-Np6tVQH7tb8oeI5NgUS:bpyybux) ([raw file](https://github.com/sillsdev/machine/blob/a5c12daee2a214a6bbf52c048b8b0c2140d50bc4/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L92)):*
> ```Smalltalk
>     {
>         flores200Code = ResolveLanguageTag(languageTag);
>         return _flores200Languages.TryGetValue(flores200Code, out string? _);
> ```

`ContainsKey` would be more appropriate here.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/machine/159#-Np6tnnx-9G_yH3i_eKV:-Np6tnnx-9G_yH3i_eKW:b-knnjz1) ([raw file](https://github.com/sillsdev/machine/blob/a5c12daee2a214a6bbf52c048b8b0c2140d50bc4/tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs#L16)):*
> ```Smalltalk
> 
>     [Test]
>     [TestCase("es", "spa_Latn")]
> ```

I would prefer not to switch to test cases. The method name gives useful information about what is being tested.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 92 at r4](https://reviewable.io/reviews/sillsdev/machine/159#-Np6tVQH7tb8oeI5NgUR:-NpLdbte4dqW6_YfQg1b:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a5c12daee2a214a6bbf52c048b8b0c2140d50bc4/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L92)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`ContainsKey` would be more appropriate here.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/machine/159#-Np6tnnx-9G_yH3i_eKV:-NpLfcez8FaxJSxnS8D8:b64udmf) ([raw file](https://github.com/sillsdev/machine/blob/a5c12daee2a214a6bbf52c048b8b0c2140d50bc4/tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer not to switch to test cases. The method name gives useful information about what is being tested.
</blockquote></details>

Added descriptions per test case.

**Review by ddaspit — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
