### PR TITLE
Fixes RefId's don't get populated for Paratext Projects #93

### PR DESCRIPTION
**Pull request by Enkidu93**
If there is no target file, there are no target refs; in this case, use the source ref.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/94)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/94)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/machine/94#-NfNCAbIDVdtzkO8MRwN:-NfNCAbIDVdtzkO8MRwO:b-4snxbc) ([raw file](https://github.com/sillsdev/machine/blob/879c7e3e244e4f6dee09d24893a88f3d7f138d22/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L294)):*
> ```Smalltalk
>                             CorpusId = corpus.Id,
>                             TextId = row.TextId,
>                             Refs = row.TargetRefs.Any()
> ```

I think just using `row.Refs` instead of `row.TargetRefs` should work.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/machine/94#-NfNCAbIDVdtzkO8MRwN:-NfRQx1j4d6q2sJNsPoC:b3h7qxs) ([raw file](https://github.com/sillsdev/machine/blob/879c7e3e244e4f6dee09d24893a88f3d7f138d22/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L294)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think just using `row.Refs` instead of `row.TargetRefs` should work.
</blockquote></details>

OK. Just to make sure I understand the logic before I change it (because mine was reversed): `Refs => SourceRefs.Count > 0 ? SourceRefs : TargetRefs`. Why use the source refs and not the target refs by default? Because it's clearer because the source is the thing you're translating? What's the situation in which this matters?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/94)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/machine/94#-NfNCAbIDVdtzkO8MRwN:-NfRS_sUC1Ekb5JMC9J_:b-n8hnip) ([raw file](https://github.com/sillsdev/machine/blob/879c7e3e244e4f6dee09d24893a88f3d7f138d22/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L294)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK. Just to make sure I understand the logic before I change it (because mine was reversed): `Refs => SourceRefs.Count > 0 ? SourceRefs : TargetRefs`. Why use the source refs and not the target refs by default? Because it's clearer because the source is the thing you're translating? What's the situation in which this matters?
</blockquote></details>

You are correct to question the logic. In the case of text files, the source and target refs should be the same, so using `Refs` will work fine. Unfortunately, in this case, we are dealing with Scripture, which requires a more complex fix. We need to take versification into account. If the source and target corpora use the same versification, then we can just use the source refs, if they don't use the same versification, then we will need to convert the source ref to the target versification. We can either update the `ParallelTextCorpus` class to be more robust and support this, or we can just update the code here. The code should look something like this:
```
IReadOnlyList<object> refs;
if (row.TargetRefs.Count == 0)
{
    if (sourceCorpus is ScriptureTextCorpus sstc && targetCorpus is ScriptureTextCorpus tstc)
    {
        refs = row.SourceRefs
            .Cast<VerseRef>()
            .Select(srcRef =>
            {
                var trgRef = srcRef.Clone();
                trgRef.ChangeVersification(tstc.Versification);
                return (object)trgRef;
            })
            .ToList();
    }
    else
    {
        refs = row.SourceRefs;
    }
}
else
{
    refs = row.TargetRefs;
}
yield return new Pretranslation
{
    CorpusId = corpus.Id,
    TextId = row.TextId,
    Refs = refs.Select(r => r.ToString()!).ToList(),
    Translation = row.SourceText
};
```

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/machine/94#-NfNCAbIDVdtzkO8MRwN:-NfRu_Bd5mhmimEwf9YN:bqa1uik) ([raw file](https://github.com/sillsdev/machine/blob/879c7e3e244e4f6dee09d24893a88f3d7f138d22/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L294)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You are correct to question the logic. In the case of text files, the source and target refs should be the same, so using `Refs` will work fine. Unfortunately, in this case, we are dealing with Scripture, which requires a more complex fix. We need to take versification into account. If the source and target corpora use the same versification, then we can just use the source refs, if they don't use the same versification, then we will need to convert the source ref to the target versification. We can either update the `ParallelTextCorpus` class to be more robust and support this, or we can just update the code here. The code should look something like this:
```
IReadOnlyList<object> refs;
if (row.TargetRefs.Count == 0)
{
    if (sourceCorpus is ScriptureTextCorpus sstc && targetCorpus is ScriptureTextCorpus tstc)
    {
        refs = row.SourceRefs
            .Cast<VerseRef>()
            .Select(srcRef =>
            {
                var trgRef = srcRef.Clone();
                trgRef.ChangeVersification(tstc.Versification);
                return (object)trgRef;
            })
            .ToList();
    }
    else
    {
        refs = row.SourceRefs;
    }
}
else
{
    refs = row.TargetRefs;
}
yield return new Pretranslation
{
    CorpusId = corpus.Id,
    TextId = row.TextId,
    Refs = refs.Select(r => r.ToString()!).ToList(),
    Translation = row.SourceText
};
```
</blockquote></details>

For now, I've added (and tested) your code. If you'd like to make the `ParallelTextCorpus` itself more robust down the road, I can open that as a separate issue. Let me know. For now, this works.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/94#-:-NfT4YOR0Co3Tns6vBem:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/machine/94#-NfNCAbIDVdtzkO8MRwN:-NfT4LSoASQ3WialAB4E:b-g2g5z9) ([raw file](https://github.com/sillsdev/machine/blob/879c7e3e244e4f6dee09d24893a88f3d7f138d22/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L294)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

For now, I've added (and tested) your code. If you'd like to make the `ParallelTextCorpus` itself more robust down the road, I can open that as a separate issue. Let me know. For now, this works.
</blockquote></details>

I think this fix works for now. We can make the `ParallelTextCorpus` class more robust later.

**Comment by johnml1135** [comment]
I am assuming the logic is correct.

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
