### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 159 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasqZVO-kmdC_vKOcHI:-NasqZVO-kmdC_vKOcHJ:b-cnz7w1) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L159)):*
> ```Smalltalk
>                 case TranslationEngineType.Nmt:
>                     builder.AddClearMLService();
>                     // builder.Services.AddHealthChecks().AddCheck<S3HealthCheck>(name: "S3Bucket");
> ```

Things should not be commented - either in or out.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 219 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasr7c56cgqmstd0X5G:-Nasr7c56cgqmstd0X5H:b-y0fw19) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L219)):*
> ```Smalltalk
>             foreach (var queue in queues)
>             {
>                 if ((string?)queue?["name"] == "production")
> ```

This should be a configuration parameter/environment variable: ClearMLNmtEngine__Queue.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 215 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasrbFw8SgGeRzcp2FL:-NasrbFw8SgGeRzcp2FM:b-aa9b4n) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L215)):*
> ```Smalltalk
>             JsonNode? queues_node = worker?["queues"];
>             if (queues_node is null)
>                 return false;
> ```

Why return false here and not just continue?  The worker has no queues - who cares?  Go to the next one.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasrpWz6Iwrf3xu73WW:-NasrpWz6Iwrf3xu73WX:bb8y0ip) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L204)):*
> ```Smalltalk
>     }
> 
>     public async Task<bool> AvailableWorkersExist(CancellationToken cancellationToken = default)
> ```

Rename to WorkersAreAssignedToQueue

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 225 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasry1m2hjLY84Y1jAo:-Nasry1m2hjLY84Y1jAp:b-miki18) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L225)):*
> ```Smalltalk
>             catch (HttpRequestException)
>             {
>                 _logger.LogError("Unable to access S3 bucket. Likely, the AWS credentials are invalid.");
> ```

Just logging the error?  Does it get thrown?  What response code is given on the API (failure?).  Should it create bubble up to a 503 "Service Unavailable" code?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 225 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasry1m2hjLY84Y1jAo:-NassdXqEZZmzrsLenlw:bts7zia) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L225)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Just logging the error?  Does it get thrown?  What response code is given on the API (failure?).  Should it create bubble up to a 503 "Service Unavailable" code?
</blockquote></details>

This code should really be refactored into a few different function calls.  If I am correct, this is invoked when a ClearML build is throwing exceptions - it is cleanup code and then the exception is passed on.  Why not have 

```
catch (Exception e) {CleanupBrokenBuild(); throw e}
```
And then refactor a lot of other portions of this function.  At least all the error handling should be able to be put into different functions.  There is a good argument for preserving the main flow of building in one function. A full refactor may look like:

```
RunAsync(...){
   try{
     InitializeTask();
     while(true){
        CheckForCancellation();
        status = GetStatus();
        switch (status){
          case 1: ...
        }
    }
    FinalizeCompletedJob();
  }
  catch ...
```

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv5I628GY0cOreOUK:-Nasv5I628GY0cOreOUL:b531uj8) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L63)):*
> ```Smalltalk
>                     {
>                         soFar += "\n" + new string('\t', tabDepth) + (index == 0 ? "" : "]");
>                         // + (soFar.Count(c => c == '[') > soFar.Count(c => c == ']') ? "]" : "");
> ```

Please remove the comment (or do whatever fix is needed).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasvLLR-9Sum_953FNE:-NasvLLR-9Sum_953FNF:by4ulk3) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L24)):*
> ```Smalltalk
>     }
> 
>     private static string Stringify(object? o, string soFar = "", int tabDepth = 0, int itemIndex = 0)
> ```

This is hard to understand what is happening.  There should likely be one overall comment saying what the purpose is and then a few comments littered throughout explaining it.  Otherwise, it becomes unmaintainable.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Serval.JobServer/Program.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv_Y7Bfdo39Bw3lks:-Nasv_Y7Bfdo39Bw3lkt:bgnkfta) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.Serval.JobServer/Program.cs#L12)):*
> ```Smalltalk
> var app = builder.Build();
> 
> app.MapHealthChecks("/health"); //I don't think this really does anything
> ```

Then delete it.  Or make it do something.  It appears to make the health check available at the url myurl/health.  Isn't that what is needed?  Is there another place that the health check is exposed to the outside world?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 7 unresolved discussions

**Comment by johnml1135** [comment]
@Enkidu93  - please look over the review comments.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 9 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 198 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawKxwC5nidM_vQWMWH:-NawKxwC5nidM_vQWMWI:b-bfq0j9) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L198)):*
> ```Smalltalk
>     }
> 
>     public async Task<bool> PingAsync(CancellationToken cancellationToken = default)
> ```

What are these methods used for?
___
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NawL12Y4IrBvilRfB-m:b-voe965) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):*
> ```Smalltalk
> namespace SIL.Machine.AspNetCore.Utils;
> 
> public static class AutoToString
> ```

I don't see where this class is used.
___
*[`src/SIL.Machine.Serval.JobServer/Program.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv_Y7Bfdo39Bw3lks:-NawL5bpBkDpGWEEVcf9:bgbxh9x) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.Serval.JobServer/Program.cs#L12)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Then delete it.  Or make it do something.  It appears to make the health check available at the url myurl/health.  Isn't that what is needed?  Is there another place that the health check is exposed to the outside world?
</blockquote></details>

I assume that these health check URLs are periodically queried by some Kubernetes service?

**Comment by Enkidu93** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)_ status: all files reviewed, 9 unresolved discussions (waiting on @johnml1135)
> 
> _[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 198 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawKxwC5nidM_vQWMWH:-NawKxwC5nidM_vQWMWI:b-bfq0j9) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L198)):_
> 
> > ```smalltalk
> >     }
> > 
> >     public async Task<bool> PingAsync(CancellationToken cancellationToken = default)
> > ```
> 
> What are these methods used for?

They're used in the `ClearMLHealthCheck`. Is that OK?

> _[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NawL12Y4IrBvilRfB-m:b-voe965) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):_
> 
> > ```smalltalk
> > namespace SIL.Machine.AspNetCore.Utils;
> > 
> > public static class AutoToString
> > ```
> 
> I don't see where this class is used.

It's been very useful during debugging (because nothing has a toString method). It had been used in some logging and error messages, but it looks like those didn't make it haha. I can remove it if you like - although I suspect it will be useful in the future. Let me know.

> _[`src/SIL.Machine.Serval.JobServer/Program.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv_Y7Bfdo39Bw3lks:-NawL5bpBkDpGWEEVcf9:bgbxh9x) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.Serval.JobServer/Program.cs#L12)):_
> Previously, johnml1135 (John Lambert) wrote…
> 
> I assume that these health check URLs are periodically queried by some Kubernetes service?

Yeah. that's possible. I'm not sure. The `/health` endpoint that's visible to the user is mapped to the health checks queried by the serval container - not this one. But if you think it's being used by Kubernetes under the hood, I'm happy to keep it in. I didn't understand where it was being used - that's why I left it in with a comment, hoping you guys might know. Thank you!

**Comment by Enkidu93** [comment]
> 

It gets rethrown. I, in general, don't like the flow of the logic here - too much of using try/catch for flow control. Can you think of a simple way to refactor it off the top of your head?

**Comment by Enkidu93** [comment]
I fixed some of the issues. Let me know about the outstanding ones :).

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 8 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 198 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawKxwC5nidM_vQWMWH:-Nawb_TI6v66dYs9jO1n:bxxx4gf) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L198)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

They're used in the `ClearMLHealthCheck`. Is that OK?
</blockquote></details>

That makes sense.
___
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-Nawbsxx0URvuSZV8KhS:b-7q4jz9) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

It's been very useful during debugging (because nothing has a toString method). It had been used in some logging and error messages, but it looks like those didn't make it haha. I can remove it if you like - although I suspect it will be useful in the future. Let me know.
</blockquote></details>

I would prefer not to check in debugging code.
___
*[`src/SIL.Machine.Serval.JobServer/Program.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv_Y7Bfdo39Bw3lks:-Nawc3W43bhVYH39gnkW:b-7svu1n) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.Serval.JobServer/Program.cs#L12)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

Yeah. that's possible. I'm not sure. The `/health` endpoint that's visible to the user is mapped to the health checks queried by the serval container - not this one. But if you think it's being used by Kubernetes under the hood, I'm happy to keep it in. I didn't understand where it was being used - that's why I left it in with a comment, hoping you guys might know. Thank you!
</blockquote></details>

I think we should leave it in, since this is how you would query the health status of the job server. If we aren't using it now, I'm sure we will in the future.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 225 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasry1m2hjLY84Y1jAo:-NbF18eO59B1dnK8Yvu_:bahrjb9) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L225)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

I agree. I'm happy to do so. Do you think that's appropriate in this branch or should that be done elsewhere? Also, I notice that it parallels the code in SMT. Should it be refactored in parallel as well?
</blockquote></details>

Hmm... Let's just make sure the 503 pops up here (if it does not already) and make another issue for refactoring - https://github.com/sillsdev/serval/issues/73

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 215 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasrbFw8SgGeRzcp2FL:-NbF2ia78RPQDdb3dm6R:bcca8z) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L215)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why return false here and not just continue?  The worker has no queues - who cares?  Go to the next one.
</blockquote></details>

Just to double check - is my logic correct, or am I misunderstanding something...  If it looks good to you, then ok.

**Comment by Enkidu93** [comment]
> 

Yes, it does bubble up. It should tested in the missing-services-tests workflow. And sounds good! I'll add that to the list :).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NbF2v1a0gwy_Txw-3yG:b84p9bl) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer not to check in debugging code.
</blockquote></details>

I will argue that for a production system, we will want certain things printed to the logs from time to time to retroactively see what is going wrong - observability, monitoring, etc..  If this is (or will be) used for that, then ok - if not, then.... hmmm.... is there a scripts folder?  What is the best way to keep it but not have it be compiled in?

**Comment by Enkidu93** [comment]
> _[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 215 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasrbFw8SgGeRzcp2FL:-NbF2ia78RPQDdb3dm6R:bcca8z) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L215)):_
> Previously, johnml1135 (John Lambert) wrote…
> 
> > Why return false here and not just continue?  The worker has no queues - who cares?  Go to the next one.
> 
> Just to double check - is my logic correct, or am I misunderstanding something... If it looks good to you, then ok.

No, no, you were right. Honestly, it might be appropriate to throw an exception because the queue_node should always exist as long as ClearML hasn't changed its API. That's why the logical error didn't come up in my tests. Thank you! I already fixed it I believe.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NasvLLR-9Sum_953FNE:-NbF3plZCoThG4s_c8RP:b-foeghm) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L24)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is hard to understand what is happening.  There should likely be one overall comment saying what the purpose is and then a few comments littered throughout explaining it.  Otherwise, it becomes unmaintainable.
</blockquote></details>

Excellent - it is much easier to understand now.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Serval.JobServer/Program.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-Nasv_Y7Bfdo39Bw3lks:-NbF4GFoCvsmmGQBXdLN:b-cstnkg) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.Serval.JobServer/Program.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we should leave it in, since this is how you would query the health status of the job server. If we aren't using it now, I'm sure we will in the future.
</blockquote></details>

I agree

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NbQ0dmd5sN7N3hWcGQR:b-a2ezfh) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I will argue that for a production system, we will want certain things printed to the logs from time to time to retroactively see what is going wrong - observability, monitoring, etc..  If this is (or will be) used for that, then ok - if not, then.... hmmm.... is there a scripts folder?  What is the best way to keep it but not have it be compiled in?
</blockquote></details>

If we are only using it be debugging purposes, we could use the [Dumpify](https://github.com/MoaidHathot/Dumpify) library and only include it as a development dependency like this:

```
<PackageReference Include="Dumpify" Version="0.6.0">
    <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

Another simpler option is to serialize the object to YAML or JSON like this:

```
JsonConvert.SerializeObject(obj);
```

Then you don't need to include any extra dependencies or functions in the codebase for debugging purposes.

In any case, I'm not sure what this buys you over inspecting the object in the VS Code/VS debugger.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NbVyVupCTb6RVW-8iZk:bgwgsuv) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If we are only using it be debugging purposes, we could use the [Dumpify](https://github.com/MoaidHathot/Dumpify) library and only include it as a development dependency like this:

```
<PackageReference Include="Dumpify" Version="0.6.0">
    <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

Another simpler option is to serialize the object to YAML or JSON like this:

```
JsonConvert.SerializeObject(obj);
```

Then you don't need to include any extra dependencies or functions in the codebase for debugging purposes.

In any case, I'm not sure what this buys you over inspecting the object in the VS Code/VS debugger.
</blockquote></details>

I see more clearly now - it is not used in production logging, but in debugging.  @Enkidu93 - if you are OK with one of Damien's solutions, then fine.  I myself usually just use the debugger.

**Comment by Enkidu93** [comment]
> _[`src/SIL.Machine.AspNetCore/Utils/AutoToString.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/49#-NawL12Y4IrBvilRfB-l:-NbVyVupCTb6RVW-8iZk:bgwgsuv) ([raw file](https://github.com/sillsdev/machine/blob/38748f4a81591700f9dce8ba0ded4524b28a9a48/src/SIL.Machine.AspNetCore/Utils/AutoToString.cs#L3)):_
> Previously, ddaspit (Damien Daspit) wrote…
> 
> I see more clearly now - it is not used in production logging, but in debugging. @Enkidu93 - if you are OK with one of Damien's solutions, then fine. I myself usually just use the debugger.

Yeah, the JSON/YAML serialization is a good trick! Thank you, Damien. I do think it may be helpful (and has been) in some of the test failure error messages to see what went wrong retrospectively (rather than rerunning the test and trying to mock those conditions - we've had enough heisenbugs haha), so I'll just use that strategy there.

**Review by ddaspit — CHANGES_REQUESTED** [review]
I apologize. I missed a couple of files in my initial review. I recommended a couple of more changes.

> Reviewed 7 of 13 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49#-:-Nbp9Miy7IbB0PCxWts6:bom4ttm)* status: all files reviewed, 4 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 241 at r3](https://reviewable.io/reviews/sillsdev/machine/49#-Nbp6bIX3hzx2fNwUvEO:-Nbp6bIY65caImrtzMy5:bgec405) ([raw file](https://github.com/sillsdev/machine/blob/abd88f1402f712789947e8442389bfa1c2e6d510/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L241)):*
> ```Smalltalk
>                 await _platformService.BuildFaultedAsync(buildId, e.Message, CancellationToken.None);
>                 _logger.LogError(0, e, "Build faulted ({0})", buildId);
>                 throw e;
> ```

This messes up the stack trace. I think it would be better to not put this in a `finally` block, so that you can just use `throw;`.
___
*[`src/SIL.Machine.AspNetCore/Services/S3HealthCheck.cs` line 26 at r3](https://reviewable.io/reviews/sillsdev/machine/49#-Nbp7PR3E4gXByQ2d95q:-Nbp7PR3E4gXByQ2d95r:bz0ngp6) ([raw file](https://github.com/sillsdev/machine/blob/abd88f1402f712789947e8442389bfa1c2e6d510/src/SIL.Machine.AspNetCore/Services/S3HealthCheck.cs#L26)):*
> ```Smalltalk
>             if (
>                 e is HttpRequestException
>                 && ((HttpRequestException)e).StatusCode is HttpStatusCode.Forbidden or HttpStatusCode.Unauthorized
> ```

If you use [pattern matching](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching#type-tests), then you won't need the cast.
```
if (e is HttpRequestException hre && hre.StatusCode is HttpStatusCode.Forbidden or HttpStatusCode.Unauthorized)
```
___
*[`src/SIL.Machine.Serval.EngineServer/Program.cs` line 12 at r3](https://reviewable.io/reviews/sillsdev/machine/49#-Nbp81J-84ada9IchBM_:-Nbp81J-84ada9IchBMa:b7875iu) ([raw file](https://github.com/sillsdev/machine/blob/abd88f1402f712789947e8442389bfa1c2e6d510/src/SIL.Machine.Serval.EngineServer/Program.cs#L12)):*
> ```Smalltalk
>     .AddServalTranslationEngineService();
> 
> builder.Services.AddHealthChecks().AddCheck<S3HealthCheck>("S3 Bucket");
> ```

This health check should be registered where the `SharedFileService` is registered, i.e. `IServiceCollectionExtensions.AddMachine()`.
___
*[`src/SIL.Machine.Serval.EngineServer/Program.cs` line 13 at r3](https://reviewable.io/reviews/sillsdev/machine/49#-Nbp8wFW-mXjnnorTUCL:-Nbp8wFW-mXjnnorTUCM:b-xqougc) ([raw file](https://github.com/sillsdev/machine/blob/abd88f1402f712789947e8442389bfa1c2e6d510/src/SIL.Machine.Serval.EngineServer/Program.cs#L13)):*
> ```Smalltalk
> 
> builder.Services.AddHealthChecks().AddCheck<S3HealthCheck>("S3 Bucket");
> builder.Services.AddHealthChecks().AddCheck<ClearMLHealthCheck>("ClearML Health Check");
> ```

This health check should be registered where the `ClearMLService` is registered, i.e. `IMachineBuilderExtensions.AddClearMLService()`.

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 4 unresolved discussions (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
I believe everything is in order now: @ddaspit @johnml1135. Let me know if there any other changes needed.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj` line 11 at r4](https://reviewable.io/reviews/sillsdev/machine/49#-NbplM2MB-qyufO6Fq0g:-NbplM2MB-qyufO6Fq0h:bbd1xbg) ([raw file](https://github.com/sillsdev/machine/blob/8d014954ae68eef9bce9db67e6c36de996e25952/src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj#L11)):*
> ```XML
> 
> 	<ItemGroup>
> 		<PackageReference Include="AspNetCore.HealthChecks.Aws.S3" Version="6.0.2" />
> ```

Does this need to be moved to SIL.Machine.AspNetCore?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj` line 11 at r4](https://reviewable.io/reviews/sillsdev/machine/49#-NbplM2MB-qyufO6Fq0g:-NbpnDg8ErmYDbCPjE0A:b-p7xcr3) ([raw file](https://github.com/sillsdev/machine/blob/8d014954ae68eef9bce9db67e6c36de996e25952/src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Does this need to be moved to SIL.Machine.AspNetCore?
</blockquote></details>

And is it needed in Serval anymore?  It's in ApiServer.csproj - and Serval doesn't access the S3 bucket!

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj` line 11 at r4](https://reviewable.io/reviews/sillsdev/machine/49#-NbplM2MB-qyufO6Fq0g:-NbpoN5f6hWupd0iKP57:b-ghhp6x) ([raw file](https://github.com/sillsdev/machine/blob/8d014954ae68eef9bce9db67e6c36de996e25952/src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj#L11)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

And is it needed in Serval anymore?  It's in ApiServer.csproj - and Serval doesn't access the S3 bucket!
</blockquote></details>

Yes, it should be removed from Serval.ApiServer.

**Comment by Enkidu93** [comment]
> _[`src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj` line 11 at r4](https://reviewable.io/reviews/sillsdev/machine/49#-NbplM2MB-qyufO6Fq0g:-NbpnDg8ErmYDbCPjE0A:b-p7xcr3) ([raw file](https://github.com/sillsdev/machine/blob/8d014954ae68eef9bce9db67e6c36de996e25952/src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj#L11)):_
> Previously, ddaspit (Damien Daspit) wrote…
> 
> And is it needed in Serval anymore? It's in ApiServer.csproj - and Serval doesn't access the S3 bucket!

Good catch. It's removed from machine.

**Review by ddaspit — APPROVED** [review]
:lgtm: Good Job.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49#-:-Nbtuhe9AyTS42HAXU-8:b-elr8jf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
@johnml1135 We clear to merge? You want me to or you? Rebase then merge?

**Review by johnml1135 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/49#-:-NbuSao34viQMo2BqThG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by ddaspit** [comment]
"Rebase and merge" would be good if possible. No need to squash.

**Pull request merged**
