### PR TITLE
Control the pretranslation of existing text

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/serval/issues/370

Reworked the logic of preferring existing or new text.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/189)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/189)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnFDV6CqYa82iOhCjj:-NvnFDV6CqYa82iOhCjk:bwy01uz) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L29)):*
> ```Smalltalk
>             bool stripAllText = false,
>             bool strictComparison = true,
>             bool preferExistingText = true
> ```

I would make the default `false`, since that is the current behavior.
___
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 363 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnErh12JqlqHy0iE7E:-NvnErh28dSgsdYhBnu_:bihq3nq) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L363)):*
> ```Smalltalk
>             bool newText = _replace.Count > 0 && _replace.Peek();
>             bool existingText = state
>                 .Tokens.Skip(_tokenIndex)
> ```

I wouldn't use `Skip` here. It is not very efficient when operating on a list. It will iterate through the list instead of jumping to the specified index.
___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnFaWu3Wqb7AFW4qqk:-NvnFaWu3Wqb7AFW4qql:b5zbhx2) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L53)):*
> ```Smalltalk
> 
>     [Test]
>     public void GetUsfm_PreferPretranslated()
> ```

I would rename this test, maybe `GetUsfm_PreferRows`.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnFDV6CqYa82iOhCjj:-NvnaKhrD6S8PR1on-fm:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make the default `false`, since that is the current behavior.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmTextUpdater.cs` line 363 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnErh12JqlqHy0iE7E:-Nvnexxj1Ur09tBasorX:bgs1ioa) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/src/SIL.Machine/Corpora/UsfmTextUpdater.cs#L363)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I wouldn't use `Skip` here. It is not very efficient when operating on a list. It will iterate through the list instead of jumping to the specified index.
</blockquote></details>

OK - reworked algorithm.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine/189#-NvnFaWu3Wqb7AFW4qqk:-NvnfXVs9V8q1p9gzZsH:bb7f2mf) ([raw file](https://github.com/sillsdev/machine/blob/38d8be62a3c174e3a506b5ce7f2d06c5510fa8ca/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L53)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this test, maybe `GetUsfm_PreferRows`.
</blockquote></details>

done

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/189#-:-Nvr1Avy30khBhwmTUTr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/189)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/AssemblyInfo.props` line 3 at r3](https://reviewable.io/reviews/sillsdev/machine/189#-Nvr8fO8DBKKpSvywEKH:-Nvr8fO8DBKKpSvywEKI:blwa58w) ([raw file](https://github.com/sillsdev/machine/blob/12611e71688972603b981439a16f1ebd3c969d20/src/AssemblyInfo.props#L3)):*
> ```XML
> <Project>
> 	<PropertyGroup>
> 		<Version>3.2.0</Version>
> ```

Please update the version in a separate PR, especially not in a PR that has already been approved. Update the version to 3.1.1. There isn't enough of a change to warrant a new minor release.

**Comment by johnml1135** [comment]
*[`src/AssemblyInfo.props` line 3 at r3](https://reviewable.io/reviews/sillsdev/machine/189#-Nvr8fO8DBKKpSvywEKH:-NvrBBet1BQUT-OEgFMT:b32wtd) ([raw file](https://github.com/sillsdev/machine/blob/12611e71688972603b981439a16f1ebd3c969d20/src/AssemblyInfo.props#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please update the version in a separate PR, especially not in a PR that has already been approved. Update the version to 3.1.1. There isn't enough of a change to warrant a new minor release.
</blockquote></details>

ok

**Comment by johnml1135** [comment]
:lgtm:

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/189#-:-NvrYu4wBuBSvtBeX2-s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
