### PR TITLE
Queue depth endpoint + status message

### PR DESCRIPTION
**Pull request by Enkidu93**
See [here](https://github.com/sillsdev/serval/pull/177) for parallel PR in serval.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
This looks like it includes changes from a previous PR that I already reviewed. I can't tell what is new and what isn't.

> Reviewed 2 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110#-:-NgV3O2nDigmfXGfWSmL:bkpe8tx)* status: 2 of 27 files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
This addresses https://github.com/sillsdev/serval/issues/79 and https://github.com/sillsdev/serval/issues/89.

**Comment by Enkidu93** [comment]
I began this work before the config passing was merged in but I needed those changes. What's the easiest way to make this clearer for you?

**Review by ddaspit — COMMENTED** [review]
How difficult would it be for you to create a new branch with just the changes for this PR?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110#-:-NgVT6k869q3VcjRUBxL:b-m5stt6)* status: 2 of 27 files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
It would take a bit. I can run a diff (`git diff <...>` is yielding about 800 lines of text), reintegrate the changes, and test. Is there a simpler way to do this? I'm not a git wizard. I thought you could review commits individually in Reviewable (?), but that might not be sufficient. I'm happy to do so if it'd help. Just let me know.

**Comment by Enkidu93** [comment]
(These are the commits related to queue depth: https://github.com/sillsdev/machine/pull/110/commits/3f27f250a4609912e16cebb4682e1f8bc247434a and https://github.com/sillsdev/machine/pull/110/commits/f160ab00c4b2b2dea32a221bd589ee11674ff547)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 25 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVsosh8OQvm8mo7okj:-NgVsosh8OQvm8mo7okk:bs46npb) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L15)):*
> ```Smalltalk
>     private readonly ILogger<ClearMLMonitorService> _logger;
>     private readonly Dictionary<string, ProgressStatus> _curBuildStatus = new();
>     private SortedList<DateTime, string> _curQueuedTasks = new SortedList<DateTime, string>();
> ```

This should be readonly.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVtnphD-Naxvzh_MlU:-NgVtnphD-Naxvzh_MlV:bkak98t) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L60)):*
> ```Smalltalk
>             ).ToDictionary(t => t.Id);
> 
>             foreach (
> ```

`_curQueuedTasks` should be synchronized, because multiple threads can access it at the same time. You can avoid locks altogether by simplifying the code. Replace `_curQueuedTasks` with the property `QueueDepth`
```
Dictionary<string, int> queuePositions = tasks.Values
    .Where(t => t.Status is ClearMLTaskStatus.Queued or ClearMLTaskStatus.Created)
    .OrderBy(t => t.Created)
    .Select((t, i) => (Position: i, Task: t))
    .ToDictionary(e => e.Task.Id, e => e.Position);
QueueDepth = queuePositions.Count;
```

You can then use the `queuePositions` dictionary to update the queue position for each build.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVsX7T24rfjX1MEB1X:-NgVsX7T24rfjX1MEB1Y:b-hl1vcj) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L88)):*
> ```Smalltalk
>                             0,
>                             0.0,
>                             $"Number of jobs ahead in queue: {GetNumAheadInQueue(engine.CurrentBuild.BuildId)}"
> ```

I think we should add a separate queue depth property. 
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 208 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVlCXF7tOEpkrdfhox:-NgVlCXF7tOEpkrdfhoy:b-uaxixs) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L208)):*
> ```Smalltalk
>     {
>         return (await _buildJobService.GetBuildingEnginesAsync(BuildJobRunner.Hangfire))
>             .Where(e => e.CurrentBuild!.JobState == BuildJobState.Pending)
> ```

This will return NMT and SMT engines. You could use the Hangfire monitoring API to get the number of jobs on the `smt_transfer` queue. First, you need to inject `JobStorage` into this service. Then, use `_jobStorage.GetMonitoringApi().EnqueuedCount("smt_transfer")` to get the number of jobs on the queue.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: 21 of 29 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVsosh8OQvm8mo7okj:-NgZWgSg8Ge1Pwy22RYi:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be readonly.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVtnphD-Naxvzh_MlU:-NgZWi0j6SF_EEdp7EdJ:bk81pcm) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`_curQueuedTasks` should be synchronized, because multiple threads can access it at the same time. You can avoid locks altogether by simplifying the code. Replace `_curQueuedTasks` with the property `QueueDepth`
```
Dictionary<string, int> queuePositions = tasks.Values
    .Where(t => t.Status is ClearMLTaskStatus.Queued or ClearMLTaskStatus.Created)
    .OrderBy(t => t.Created)
    .Select((t, i) => (Position: i, Task: t))
    .ToDictionary(e => e.Task.Id, e => e.Position);
QueueDepth = queuePositions.Count;
```

You can then use the `queuePositions` dictionary to update the queue position for each build.
</blockquote></details>

Done. I used `Task.Name` since I want to query it later by buildId.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVsX7T24rfjX1MEB1X:-NgZWq686fnLQwPR1f3x:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L88)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we should add a separate queue depth property.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 208 at r1](https://reviewable.io/reviews/sillsdev/machine/110#-NgVlCXF7tOEpkrdfhox:-NgZWtLP0ol1mTRbPr5N:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/f160ab00c4b2b2dea32a221bd589ee11674ff547/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L208)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This will return NMT and SMT engines. You could use the Hangfire monitoring API to get the number of jobs on the `smt_transfer` queue. First, you need to inject `JobStorage` into this service. Then, use `_jobStorage.GetMonitoringApi().EnqueuedCount("smt_transfer")` to get the number of jobs on the queue.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine/Utils/ProgressStatus.cs` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/110#-NgZiQuM1DSYSkif_N42:-NgZiQuM1DSYSkif_N43:bodlb9d) ([raw file](https://github.com/sillsdev/machine/blob/7f60c69aa9524562c06da15f67c0cfa0bf0f3ef6/src/SIL.Machine/Utils/ProgressStatus.cs#L21)):*
> ```Smalltalk
>         public double? PercentCompleted { get; }
>         public string Message { get; }
>         public int? QueueDepth { get; }
> ```

I would prefer not to add `QueueDepth` to `ProgressStatus`. You could pass queue depth as a separate parameter to `ClearMLMonitorService.UpdateTrainJobStatus` or create a `ClearMLMonitorService.UpdateBuildQueueDepth` method specifically for updating the queue depth. 
___
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 43 at r2](https://reviewable.io/reviews/sillsdev/machine/110#-NgZjjhRB5GrSN5luCPJ:-NgZjjhRB5GrSN5luCPK:b-dmse42) ([raw file](https://github.com/sillsdev/machine/blob/7f60c69aa9524562c06da15f67c0cfa0bf0f3ef6/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L43)):*
> ```Smalltalk
>     Task CancelBuildAsync(string engineId, CancellationToken cancellationToken = default);
> 
>     int GetQueueDepth(CancellationToken cancellationToken = default);
> ```

I know that all of the current implementations of `GetQueueDepth` are not async, but I would go ahead and leave it as async.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: 29 of 30 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 43 at r2](https://reviewable.io/reviews/sillsdev/machine/110#-NgZjjhRB5GrSN5luCPJ:-Ng_Yg3p8nssfdveaIM2:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7f60c69aa9524562c06da15f67c0cfa0bf0f3ef6/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I know that all of the current implementations of `GetQueueDepth` are not async, but I would go ahead and leave it as async.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 8 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 80 at r3](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_LP5k5z_9dUqU96ey:-Ng_LP5k5z_9dUqU96ez:b-o2bips) ([raw file](https://github.com/sillsdev/machine/blob/f0b77a76f5d187ba57ff749e88059bbb21fdec90/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L80)):*
> ```Smalltalk
>                         platformService,
>                         engine.CurrentBuild.BuildId,
>                         new ProgressStatus(0, 0.0),
> ```

When passing a literal to a method, you should make the parameter name explicit, i.e. `new ProgressStatus(step: 0, percentCompleted: 0.0)`.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_iLaa0eow_32Q7EmX:-Ng_iLaa0eow_32Q7EmY:b-ebneng) ([raw file](https://github.com/sillsdev/machine/blob/78733ca57197157e4ccc599ce88dfdcf06fe4a8e/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L16)):*
> ```Smalltalk
>     private readonly Dictionary<string, ProgressStatus> _curBuildStatus = new();
> 
>     public int QueueDepth { get; private set; }
> ```

This should be named `QueueSize`.
___
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 43 at r4](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_i1-4-ybOEv3iZdD-:-Ng_i1-4-ybOEv3iZdD0:bqmu7al) ([raw file](https://github.com/sillsdev/machine/blob/78733ca57197157e4ccc599ce88dfdcf06fe4a8e/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L43)):*
> ```Smalltalk
>     Task CancelBuildAsync(string engineId, CancellationToken cancellationToken = default);
> 
>     Task<int> GetQueueDepthAsync(CancellationToken cancellationToken = default);
> ```

You missed renaming this method. Should be `GetQueueSizeAsync`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: 25 of 30 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Utils/ProgressStatus.cs` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/110#-NgZiQuM1DSYSkif_N42:-Ng_k1Sp5oBtG3UM9Qpl:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7f60c69aa9524562c06da15f67c0cfa0bf0f3ef6/src/SIL.Machine/Utils/ProgressStatus.cs#L21)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer not to add `QueueDepth` to `ProgressStatus`. You could pass queue depth as a separate parameter to `ClearMLMonitorService.UpdateTrainJobStatus` or create a `ClearMLMonitorService.UpdateBuildQueueDepth` method specifically for updating the queue depth.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 80 at r3](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_LP5k5z_9dUqU96ey:-Ng_k42O5ln7ecQySHl2:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/f0b77a76f5d187ba57ff749e88059bbb21fdec90/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L80)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

When passing a literal to a method, you should make the parameter name explicit, i.e. `new ProgressStatus(step: 0, percentCompleted: 0.0)`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_iLaa0eow_32Q7EmX:-Ng_k3CR0WF2oTrFmSWg:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/78733ca57197157e4ccc599ce88dfdcf06fe4a8e/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `QueueSize`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs` line 43 at r4](https://reviewable.io/reviews/sillsdev/machine/110#-Ng_i1-4-ybOEv3iZdD-:-Ng_k5Yx3PdabMvkWTHQ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/78733ca57197157e4ccc599ce88dfdcf06fe4a8e/src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You missed renaming this method. Should be `GetQueueSizeAsync`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110#-:-Ng_pt6a87PscmNRVAMi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 5 of 5 files at r5, 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
You will need to re-release the GRPC nuget package in Serval and update it here before the CI tests will pass.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
This should be fixed before merging.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110#-:-NgdT2YNEiYWbFR2F5aG:b-lllrz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> This should be fixed before merging.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110#-:-NgdT2YNEiYWbFR2F5aG:b-lllrz)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

I think I've not done this process correctly. Could you let me know how I ought to go about releasing the new version etc.? Last time you did it, but it would be helpful for me for future reference to know the process.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
@Enkidu93 - there are still some failing tests around cancelling jobs.

**Comment by Enkidu93** [comment]
> @Enkidu93 - there are still some failing tests around cancelling jobs.

Yep, I'm working on it.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 17 of 17 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
