### PR TITLE
Extend manual test to process multiple projects including zipped projects

### PR DESCRIPTION
**Pull request by Enkidu93**
Addresses https://github.com/sillsdev/serval/issues/429

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/227)

### CODE REVIEW

**Comment by johnml1135** [comment]
:lgtm:

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine/227#-O1vjTFr0ZUC1LFUDmWh:-O1vjTFr0ZUC1LFUDmWi:b9mapy3) ([raw file](https://github.com/sillsdev/machine/blob/2b986edc974073ffb52dbc4381ae87012099cb2f/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs#L71)):*
> ```Smalltalk
>     [Ignore("This is for manual testing only.  Remove this tag to run the test.")]
>     public async Task CreateUsfmFile()
>     {
> ```

Can you put in a comment on how to use it?  What is the range of paratext projects that this can accept? Any arbitrarily nested set of zip files or folders of unzipped paratext projects?  How about instructions - place your zipped para text projects in this folder, remove the ignore and then run...

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/227)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine/227#-O1vjTFr0ZUC1LFUDmWh:-O1wf9E02fBsUPN1xSLt:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/2b986edc974073ffb52dbc4381ae87012099cb2f/tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs#L71)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you put in a comment on how to use it?  What is the range of paratext projects that this can accept? Any arbitrarily nested set of zip files or folders of unzipped paratext projects?  How about instructions - place your zipped para text projects in this folder, remove the ignore and then run...
</blockquote></details>

Done.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/227)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
