### PR TITLE
Fix forever loop

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/260)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/260)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 579 at r1](https://reviewable.io/reviews/sillsdev/machine/260#-O9WKsAcCtBR7F-x4D3A:-O9WKsAcCtBR7F-x4D3B:b-j9n84j) ([raw file](https://github.com/sillsdev/machine/blob/bcefa3bd8ae70878f86bece5ab6550b97cba2b6e/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L579)):*
> ```Smalltalk
>                 }
> 
>                 bool result = _enumerator.MoveNext();
> ```

You should set `_enumeratorHasMoreData` instead of `result`, so that the field is set consistently in all cases.
___
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 584 at r1](https://reviewable.io/reviews/sillsdev/machine/260#-O9WLIhO123zctBJ7tgw:-O9WLIhO123zctBJ7tgx:b-zdxsww) ([raw file](https://github.com/sillsdev/machine/blob/bcefa3bd8ae70878f86bece5ab6550b97cba2b6e/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L584)):*
> ```Smalltalk
>             }
> 
>             public void Reset()
> ```

You should reset `_enumeratorHasMoreData` here.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 579 at r1](https://reviewable.io/reviews/sillsdev/machine/260#-O9WKsAcCtBR7F-x4D3A:-O9WMPal1fwaSFwBUgvw:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/bcefa3bd8ae70878f86bece5ab6550b97cba2b6e/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L579)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should set `_enumeratorHasMoreData` instead of `result`, so that the field is set consistently in all cases.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 584 at r1](https://reviewable.io/reviews/sillsdev/machine/260#-O9WLIhO123zctBJ7tgw:-O9WMQAiA4XcO0axgbXk:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/bcefa3bd8ae70878f86bece5ab6550b97cba2b6e/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L584)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should reset `_enumeratorHasMoreData` here.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/260#-:-O9WMkiZD9zO5Ek6j4Qn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
