### PR TITLE
Config passing via build options for post-nmt/hangfire refactor

### PR DESCRIPTION
**Pull request by Enkidu93**
See [here](https://github.com/sillsdev/machine/pull/104) for previous discussion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)

### CODE REVIEW

**Comment by Enkidu93** [comment]
Waiting on Matthew to publish the updates to machine and then I can test more properly. I believe buildOptions is being passed appropriately (just as it was in the previous PR).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgOVLLU7gOihGWu9uYq:by09xvs) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):*
> ```Smalltalk
>                 + $"    'shared_file_uri': '{_sharedFileService.GetBaseUri()}',\n"
>                 + $"    'buildOptions': '''{buildOptions}''',\n"
>                 + $"    'clearml': True\n"
> ```

Just to be clear and say it explicitly - if buildOptions is null, what exactly will happen?  I would think it would be preferable to not pass anything for build options if it is null (not even the arg) to be explicit that there are, in fact, no build options.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtTrainBuildJob.cs` line 70 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVtIk3ALuo6mxbnlI:-NgOVtIk3ALuo6mxbnlJ:b-9ujtug) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtTrainBuildJob.cs#L70)):*
> ```Smalltalk
>                         + $"    'trg_lang': '{ConvertLanguageTag(engine.TargetLanguage)}',\n"
>                         + $"    'shared_file_uri': '{_sharedFileService.GetBaseUri()}',\n"
>                         + $"    'buildOptions': '''{buildOptions}''',\n"
> ```

Same as other comment - shouldn't we just not send the arg buildOptions at all?

**Comment by Enkidu93** [comment]
> _[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgOVLLU7gOihGWu9uYq:by09xvs) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):_
> 
> > ```smalltalk
> >                 + $"    'shared_file_uri': '{_sharedFileService.GetBaseUri()}',\n"
> >                 + $"    'buildOptions': '''{buildOptions}''',\n"
> >                 + $"    'clearml': True\n"
> > ```
> 
> Just to be clear and say it explicitly - if buildOptions is null, what exactly will happen? I would think it would be preferable to not pass anything for build options if it is null (not even the arg) to be explicit that there are, in fact, no build options.

I think we ought to pass something because of [this](https://github.com/sillsdev/machine.py/blob/adf9bb9e31fc38427b51ccaf97b00872d36920a0/machine/jobs/build_nmt_engine.py#L41) - unless you'd like to make a change there. Maybe passing empty braces would be ideal (???). What do you think?

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgOY9Th87pSDrvkmp85:bf93tct) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I think we ought to pass something because of [this](https://github.com/sillsdev/machine.py/blob/adf9bb9e31fc38427b51ccaf97b00872d36920a0/machine/jobs/build_nmt_engine.py#L41) - unless you'd like to make a change there. Maybe passing empty braces would be ideal (???). What do you think?
</blockquote></details>

Also, to answer your other question, it would currently evaluate to the empty string.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgOxMz-04Jf5bDya4nH:b-bdam3o) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Also, to answer your other question, it would currently evaluate to the empty string.
</blockquote></details>

But also this: https://github.com/sillsdev/machine.py/blob/adf9bb9e31fc38427b51ccaf97b00872d36920a0/machine/jobs/build_nmt_engine.py#L79.  The default is {}.  Therefore, it is safer to pass nothing, have nothing be recorded in ClearML and have machine.py insert brackets for the default.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgOxy_9EQ7TadS70sAP:bkkvl1z) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

But also this: https://github.com/sillsdev/machine.py/blob/adf9bb9e31fc38427b51ccaf97b00872d36920a0/machine/jobs/build_nmt_engine.py#L79.  The default is {}.  Therefore, it is safer to pass nothing, have nothing be recorded in ClearML and have machine.py insert brackets for the default.
</blockquote></details>

Oh, true - I see. OK, so remove it altogether? Or null will be fine then? Or will the empty string override the braces?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/machine/109#-NgOVLLU7gOihGWu9uYp:-NgP2WkkA4h9AeALZWO6:bktmkib) ([raw file](https://github.com/sillsdev/machine/blob/f4f20b7b80bff3d0e36bba039edeb296cb77b5fa/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs#L46)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Oh, true - I see. OK, so remove it altogether? Or null will be fine then? Or will the empty string override the braces?
</blockquote></details>

I would remove it alltogether.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 23 of 26 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 50 at r3](https://reviewable.io/reviews/sillsdev/machine/109#-NgPMApt0Se-Fcts43zO:-NgPMApt0Se-Fcts43zP:b-t78zp4) ([raw file](https://github.com/sillsdev/machine/blob/69abc8731a302c6533a48531021d96c654fdc4bb/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L50)):*
> ```Smalltalk
>             Content = new StringContent(body.ToJsonString(), Encoding.UTF8, "application/json")
>         };
>         request.Headers.Add("Authorization", $"Bearer {await _clearMLAuthenticationService.GetAuthTokenAsync()}");
> ```

Why was this change made?

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 50 at r3](https://reviewable.io/reviews/sillsdev/machine/109#-NgPMApt0Se-Fcts43zO:-NgPOOEP5Ko_48I3ASBJ:b-3hswf9) ([raw file](https://github.com/sillsdev/machine/blob/69abc8731a302c6533a48531021d96c654fdc4bb/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L50)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this change made?
</blockquote></details>

While I was debugging the bug that was introduced having to do with ClearML authentication, I edited both `CallAsync`s. When I undid those changes, I made them consistent with each other (i.e. with the `CallAsync` in `ClearMLService`. See [here](https://github.com/sillsdev/machine/blob/6dfb47c5259829f47e0ad25d3e59199267a7f9d8/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L188C1-L188C105).) But come to think of it, it's probably the version in `ClearMLService` that should be changed, correct?

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 50 at r3](https://reviewable.io/reviews/sillsdev/machine/109#-NgPMApt0Se-Fcts43zO:-NgTrI3c7ojOyfB0m9Ba:b-3szga0) ([raw file](https://github.com/sillsdev/machine/blob/69abc8731a302c6533a48531021d96c654fdc4bb/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L50)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

While I was debugging the bug that was introduced having to do with ClearML authentication, I edited both `CallAsync`s. When I undid those changes, I made them consistent with each other (i.e. with the `CallAsync` in `ClearMLService`. See [here](https://github.com/sillsdev/machine/blob/6dfb47c5259829f47e0ad25d3e59199267a7f9d8/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L188C1-L188C105).) But come to think of it, it's probably the version in `ClearMLService` that should be changed, correct?
</blockquote></details>

I just went ahead and passed the token.

**Comment by Enkidu93** [comment]
@ddaspit I went ahead and passed the token in both places assuming there was no reason not to. Is there anything else that needs to be addressed?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109#-:-NgUZJrp6s30qHkGYguU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
