### PR TITLE
Fixes #46

### LINKED ISSUE #46: Error copying to stream
When making a job the first time, there was an error code in machine.job:

```
[41m[30mfail[39m[22m[49m: Hangfire.AutomaticRetryAttribute[0]
      Failed to process the job '64814c54761d983ab9eaeeb2': an exception occurred.
      System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
       ---> System.Net.Sockets.SocketException (32): Broken pipe
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|182_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
         at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
         at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
         at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at SIL.Machine.AspNetCore.Services.S3AuthHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/S3AuthHandler.cs:line 36
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at SIL.Machine.AspNetCore.Services.S3FileStorage.UploadPartAsync(String key, String uploadId, Int32 partNumber, Byte[] buffer, Int32 count) in /app/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs:line 206
         at SIL.Machine.AspNetCore.Services.S3WriteStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs:line 53
         at System.IO.BufferedStream.WriteToUnderlyingStreamAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken, Task semaphoreLockTask)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 293
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.RunAsync(String engineId, String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 58
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.RunAsync(String engineId, String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 234
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Let's fix this.

### PR DESCRIPTION
**Pull request by Enkidu93**
I tried to keep as much of the original structure as possible while replacing any interfacing with the bucket with API calls. This allowed me to keep the existing in-memory implementation. If this seems janky (i.e. using Stowage and the Amazon SDK - although Stowage is not used for anything to do with Amazon directly), I'm happy to remove the FileStorage layer and have a direct implementation of the SharedFileService - shouldn't be too hard. A few comments have been left in for review

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/51)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 39 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVPir4CiejbVSyEHfc:-NbVPir4CiejbVSyEHfd:b-gd24ng) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L39)):*
> ```Smalltalk
>         var response = await _client.ListObjectsV2Async(request, cancellationToken);
> 
>         return response.S3Objects.Any();
> ```

This will also return objects that are in a "subdirectory" - even though that concept does not exist in S3 buckets.  This is fine.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 44 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVU1v1-mlx_tz15mz-:-NbVU1v1-mlx_tz15mz0:bh96ipr) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L44)):*
> ```Smalltalk
>     public async Task<IReadOnlyCollection<IOEntry>> Ls(
>         IOPath? path = null,
>         bool recurse = false,
> ```

recurse now longer does anything.  There is an ability to do something with "delimiter as per here: https://stackoverflow.com/questions/73295517/get-list-of-files-from-an-s3-bucket-but-not-recursively.  Currently, it should work recursively.  The only place this is called is in DeleteAsync - which calls it recursively.  Either rename as LsRecursive and remove the parameter - or restore the delimiter logic (preferred).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVX5JdB3Naf_-Coa_j:-NbVX5JdB3Naf_-Coa_k:b-6jqczm) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L72)):*
> ```Smalltalk
>         catch (Exception)
>         {
>             Abort();
> ```

dotnet 7 is giving a warning - Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.  This should be fixed in some way...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 76 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVciN_0u5uD4wLgoYL:-NbVciN_0u5uD4wLgoYM:b-zh2up2) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L76)):*
> ```Smalltalk
>     public async Task<Stream?> OpenRead(IOPath path, CancellationToken cancellationToken = default)
>     {
>         var objectId = IOPath.IsRoot(path)
> ```

Why are we no longer checking the path for null?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVczr14detbqcQt0YV:-NbVczr14detbqcQt0YW:bem1oha) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L86)):*
> ```Smalltalk
>     public async Task<Stream> OpenWrite(IOPath path, CancellationToken cancellationToken = default)
>     {
>         Console.WriteLine("PATH ||| " + path.ToString());
> ```

Why no null checking?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 89 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVdDbiCJhWKxdzAEDu:-NbVdDbiCJhWKxdzAEDv:b9672m) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L89)):*
> ```Smalltalk
>         var objectId = IOPath.IsRoot(path)
>             ? string.Empty
>             : IOPath.Normalize(path, removeLeadingSlash: true, appendTrailingSlash: true);
> ```

This normalization logic occurs 4 times - can we make it into a function?  Can NormalizeWithBasePath be reintroduced?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 89 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVdDbiCJhWKxdzAEDu:-NbVdsW7CBS0F0BlzdpS:b-ytwrej) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L89)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This normalization logic occurs 4 times - can we make it into a function?  Can NormalizeWithBasePath be reintroduced?
</blockquote></details>

Or call it PathToObjectId or similar...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVe1LR6YQnJlt4L1nd:-NbVe1LR6YQnJlt4L1ne:bag5mzm) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L2)):*
> ```Smalltalk
> using Amazon.S3;
> using Amazon.S3.Model;
> ```

global using...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVeObH4LaFlz4sQAHa:-NbVeObH4LaFlz4sQAHb:b-ttlw9t) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L68)):*
> ```Smalltalk
> 
>             //     }
>             // );
> ```

What is this commented code for?  Is it needed or should it be removed?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 96 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVeW_-DqgYmC8fa8tG:-NbVeW_-DqgYmC8fa8tH:b-g65zb5) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L96)):*
> ```Smalltalk
> 
>             //     }
>             // );
> ```

Remove commented code (or otherwise fix).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVX5JdB3Naf_-Coa_j:-NbVf3B9ELSHPsPHgXlW:b-st5975) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

dotnet 7 is giving a warning - Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.  This should be fixed in some way...
</blockquote></details>

add a .wait() with a timeout?  I see that you are trying to not have it be async.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @ddaspit and @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 4 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbUt9Wm5xE4JouNljVZ:-NbUt9Wn2ve0hIufufVf:b-ayhbn) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L4)):*
> ```Smalltalk
> using Amazon;
> using Amazon.S3;
> using Amazon.S3.Model;
> ```

The preference is for global using statements.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51)* status: all files reviewed, 9 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
As I said in the meeting, it would be a good idea to go ahead and remove Stowage altogether. I will review after you have made that change.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51#-:-NbpBn_g3wVOVN7niJzT:b-rxwacu)* status: all files reviewed, 9 unresolved discussions (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
Still working on this: I'll ping you when I'm ready for review.

**Comment by Enkidu93** [comment]
One quick question and then I can push a final draft @ddaspit @johnml1135 : So I've made in-memory and local storage implementations alongside the S3 Bucket implementation (since Stowage provided both and we had both potentially utilized in the current logic). I wrote some unit tests for both (which are all passing). My question is this: Assuming it's valuable to check in the tests, what directory should I give in the unit tests as a base directory for the local file storage? I.e. a directory I'll have access to and is safe to use. I suppose I can generate a unique one and then get permissions, but I figured there was a *right way* to do this. Sorry for the delay.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVeObH4LaFlz4sQAHa:-Nc-NZU95d8M6kwSLvBj:b-p1bbxn) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L68)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What is this commented code for?  Is it needed or should it be removed?
</blockquote></details>

I was just wondering if you'd like to log (maybe at a low log level: trace, let's say) the progress of file uploads to s3.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 44 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVU1v1-mlx_tz15mz-:-Nc2NME99L9DlczQCsW1:btasq0f) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L44)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

recurse now longer does anything.  There is an ability to do something with "delimiter as per here: https://stackoverflow.com/questions/73295517/get-list-of-files-from-an-s3-bucket-but-not-recursively.  Currently, it should work recursively.  The only place this is called is in DeleteAsync - which calls it recursively.  Either rename as LsRecursive and remove the parameter - or restore the delimiter logic (preferred).
</blockquote></details>

You added recuse logic - I am assuming it works.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 49 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc2PBma6y4SaQD2nPou:-Nc2PBmb8VBPvv_DL8t5:bu2535q) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L49)):*
> ```Smalltalk
>     {
>         if (path != null && !path.EndsWith("/"))
>             throw new ArgumentException("Path must be a folder", nameof(path));
> ```

"a folder and end with a '/'."

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 76 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVciN_0u5uD4wLgoYL:-Nc2NWE94TFV4uebaI8d:b-f9agip) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L76)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why are we no longer checking the path for null?
</blockquote></details>

Standard normalization

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVczr14detbqcQt0YV:-Nc2PU_2Eq39R90-Jdh8:b-enpgm0) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L86)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why no null checking?
</blockquote></details>

Standard normalization - great!

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVX5JdB3Naf_-Coa_j:-Nc2Q5WK1MyCRN60EW0g:b-634bzo) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

add a .wait() with a timeout?  I see that you are trying to not have it be async.
</blockquote></details>

@ddaspit - is this an appropriate recommendation?  It appears sound to me...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVeObH4LaFlz4sQAHa:-Nc2QRX_9o7ntpQpBVdz:bkgrbp2) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L68)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I was just wondering if you'd like to log (maybe at a low log level: trace, let's say) the progress of file uploads to s3.
</blockquote></details>

  Let's say no for now.  The files should be fairly small - and not take too long.  If they fail, they will be retried a few times.  If they really fail, there will be error logs.  
  If we start uploading 100MB or larger files, then progress may become important - but I don't see that happening soon.  Serval is not build for big corpora, and the fine tuned models will stay in python land (for now).

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVeObH4LaFlz4sQAHa:-Nc2QxOF0ZxiWeBsar3-:b-vjz8go) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L68)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Let's say no for now.  The files should be fairly small - and not take too long.  If they fail, they will be retried a few times.  If they really fail, there will be error logs.  
  If we start uploading 100MB or larger files, then progress may become important - but I don't see that happening soon.  Serval is not build for big corpora, and the fine tuned models will stay in python land (for now).
</blockquote></details>

If we need to pull fine tuned models from S3 buckets to run inferencing and we choose Dotnet rather than python (very plausible), even then, I don't see needing user feedback nor having more logging than we have right now.  so my vote is for removing the comment.  @ddaspit, any thoughts?

**Comment by johnml1135** [comment]
My best guess is to just make a tmp directory - https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.createtempsubdirectory?view=net-7.0.  We would have to upgrade to dotnet 7.0 to use it.  @ddaspit  is there any reason we should not?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 5 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 49 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc2PBma6y4SaQD2nPou:-Nc2X_5L9XOxPGJI2aV3:b-bxub4q) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L49)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

"a folder and end with a '/'."
</blockquote></details>

Following what there was before, I was conceptualizing a folder as a path that ends with "/"  by definition. The null check with short-circuit evaluation just prevents the second check from failing.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 49 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc2PBma6y4SaQD2nPou:-Nc2dlBr664v21_RPIut:b-g0zski) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L49)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Following what there was before, I was conceptualizing a folder as a path that ends with "/"  by definition. The null check with short-circuit evaluation just prevents the second check from failing.
</blockquote></details>

I was thinking about the message in the exception - The path could very well be a folder, but giving the user insight that the trailing slash is needed.

**Review by ddaspit — COMMENTED** [review]
[This unit test fixture](https://github.com/sillsdev/machine/blob/master/tests/SIL.Machine.Translation.Thot.Tests/ThotSmtModelTrainerTests.cs) has some examples of using a temp directory. I use a `TempDirectory` class that I copied from another SIL library. You could move the `TempDirectory` class to `SIL.Machine.Utils`, which should make it available to both unit test assemblies.

> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51#-:-Nc3xmbU-vx-BJe30alY:bkcfd76)* status: all files reviewed, 7 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/InMemoryStorage.cs` line 9 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc4-XaQ-4H-2fW0ynMA:-Nc4-XaQ-4H-2fW0ynMB:b1sxm5o) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/src/SIL.Machine.AspNetCore/Services/InMemoryStorage.cs#L9)):*
> ```Smalltalk
>     public class Entry : Stream
>     {
>         public MemoryStream MemoryStream;
> ```

The convention in C# is to use properties instead of public fields. `MemoryStream` and `Path` look like they are readonly, so you would declare them like this:
```
public MemoryStream MemoryStream { get; }
```
___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 37 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc4-czN2T-hcSQ_IgdI:-Nc4-czN2T-hcSQ_IgdJ:b-mee207) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L37)):*
> ```Smalltalk
>         };
> 
>         var response = await _client.ListObjectsV2Async(request, cancellationToken);
> ```

In my C# codebases, I prefer that `var` is only used when the type is explicit elsewhere. Please check other uses of `var` in this class as well.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.AspNetCore.Tests/Services/FileStorageTests.cs` line 90 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc2SNk32PqnI4TDds9V:-NcNBP6-5YcFlPzx2_Zg:bd9u2hr) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/tests/SIL.Machine.AspNetCore.Tests/Services/FileStorageTests.cs#L90)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is there some other way to do this?  A few ideas:
* Make the test category "do not run" and have it not be commented - and then update the standard launchers and CI builds and don't run them
* Either way, there should be some comment explaining why these are commented out/not normally run.
</blockquote></details>

Can you give a short explanation as to why you uncommented these tests?  Will they all pass now on CI?

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.AspNetCore.Tests/Services/FileStorageTests.cs` line 90 at r3](https://reviewable.io/reviews/sillsdev/machine/51#-Nc2SNk32PqnI4TDds9V:-NcNB_xb2PA6CvAvh88C:bner0ym) ([raw file](https://github.com/sillsdev/machine/blob/53f62b69c130b25b5cb239f271d3fa88e1a5465e/tests/SIL.Machine.AspNetCore.Tests/Services/FileStorageTests.cs#L90)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you give a short explanation as to why you uncommented these tests?  Will they all pass now on CI?
</blockquote></details>

Ah - temp directory.  It should be all ok now.

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51#-:-NcNBjKtCOQ2LWC9wbnq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
I added a couple of retroactive comments. Hopefully, we can get back to fixing these at some point.

> Reviewed 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/51#-:-Nd128CADXnhDmszLUG7:b-nc866n)* status: all files reviewed, 1 unresolved discussion

___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/51#-NbVX5JdB3Naf_-Coa_j:-Nd110B_DeOUwbam54M_:b-lc6onp) ([raw file](https://github.com/sillsdev/machine/blob/77ccca543d5bb134c1ee4782be85138c745c8785/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - is this an appropriate recommendation?  It appears sound to me...
</blockquote></details>

Calling async methods from a synchronous method is not safe unless you are very careful. Since the S3 SDK doesn't provide synchronous implementations of their methods, I think it would be better to not provide an implementation for the `Write` method. I don't think we need it. We can simply throw a `NotSupportedException`. 
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 91 at r6](https://reviewable.io/reviews/sillsdev/machine/51#-Nd124K62hPPgO9FlZjx:-Nd124K7ABxYoNW40DFZ:bh8klvi) ([raw file](https://github.com/sillsdev/machine/blob/7f97afcab3ae0bed1a2b13df6ca445ddff103b6b/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L91)):*
> ```Smalltalk
>     }
> 
>     protected override void Dispose(bool disposing)
> ```

This override can be safely removed.

**Comment by johnml1135** [comment]
Damien's comments are resolved through:
* https://github.com/sillsdev/machine/issues/63
* https://github.com/sillsdev/machine/issues/64

**Pull request merged**
