### PR TITLE
Config passing

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/serval/issues/45

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Usings.cs` line 33 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-b5uX7lWcAtaIbT3j:-Ng-b5uYC8csbB1Wa2SE:b-bg5uw8) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Usings.cs#L33)):*
> ```Smalltalk
> global using MongoDB.Driver;
> global using MongoDB.Driver.Linq;
> global using Newtonsoft.Json.Linq;
> ```

Are we using JSON.NET anywhere?
___
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-ab2NBaXqMuikO7HL:b-5in30o) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
> ```Smalltalk
>                 request.EngineId,
>                 request.BuildId,
>                 request.Options,
> ```

`Options` is optional. You should check to see if it is set and return null if it isn't. This parameter should be passed as a nullable string everywhere, so that it is clear that it could be unset.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 53 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-bAeK8fgw7iwqjNRi:-Ng-bAeK8fgw7iwqjNRj:bj5hbfv) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L53)):*
> ```Smalltalk
>         try
>         {
>             // JsonObject? buildOptionsObject = JsonSerializer.Deserialize<JsonObject>(buildOptions); //Use/fields TBD
> ```

You can remove this comment.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-kI__CAQMJBfenPY7:b3cmu0e) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`Options` is optional. You should check to see if it is set and return null if it isn't. This parameter should be passed as a nullable string everywhere, so that it is clear that it could be unset.
</blockquote></details>

Which is better - to have options nullable or if it is null to set it to "{}" right at the beginning?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 41 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-kVB3D2eJmnz3f0jD:-Ng-kVB3D2eJmnz3f0jE:bu5kqeu) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L41)):*
> ```Smalltalk
>         string engineId,
>         string buildId,
>         string buildOptions,
> ```

If it is nullable, this and all others should be nullable...

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-kyY8EaoO8NG7jru2:bdmh5mc) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Which is better - to have options nullable or if it is null to set it to "{}" right at the beginning?
</blockquote></details>

I would rather make it explicit that it was not set.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-kxuRDNVQEwQwSXdz:b-n2nbgz) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rather make it explicit that it was not set.
</blockquote></details>

I'm not sure I understand, Damien. I'll go ahead and make sure it's passed as a nullable string, but what do you mean by return null if it's unset? You mean that its value should be null here? But wouldn't it already be? I think I'm not understanding.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-oHCV6lut_exZOaXF:b-m6jdal) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure I understand, Damien. I'll go ahead and make sure it's passed as a nullable string, but what do you mean by return null if it's unset? You mean that its value should be null here? But wouldn't it already be? I think I'm not understanding.
</blockquote></details>

Optional properties on gRPC models are not nullable types. You have to check the `HasOptions` property to see if it has been set. Check out the `Create` method in this class to see an example of what I am talking about.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng-qz-r3fxRNsVXkyxj:b-tr6og8) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Optional properties on gRPC models are not nullable types. You have to check the `HasOptions` property to see if it has been set. Check out the `Create` method in this class to see an example of what I am talking about.
</blockquote></details>

OK, I see. I had run into that before, but wasn't thinking: "return null" was confusing me. Out of curiosity (can't seem to find this online), what value to unset gRPC optional parameters have?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng0CWsD5XOGSaApBp9X:b-qlkees) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, I see. I had run into that before, but wasn't thinking: "return null" was confusing me. Out of curiosity (can't seem to find this online), what value to unset gRPC optional parameters have?
</blockquote></details>

There should be a `ClearOptions` method.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng0F9677MW6gz7Q4nCw:bmb6bch) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There should be a `ClearOptions` method.
</blockquote></details>

I see. So it's the empty string. I just wondered because I'm surprised that it didn't break without this change.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: 5 of 14 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-ab2NBaXqMuikO7HK:-Ng4oOxIBa0-CiAHruH7:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see. So it's the empty string. I just wondered because I'm surprised that it didn't break without this change.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 41 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-kVB3D2eJmnz3f0jD:-Ng4oQru8L2AfHrVFcup:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L41)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If it is nullable, this and all others should be nullable...
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs` line 53 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-bAeK8fgw7iwqjNRi:-Ng4oRqY30thCsJVMWn0:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L53)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can remove this comment.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Usings.cs` line 33 at r2](https://reviewable.io/reviews/sillsdev/machine/104#-Ng-b5uX7lWcAtaIbT3j:-Ng4oTtJ7jjhoRpLJqD2:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/01c55085f9d18bebf7afa62696a122106dd49e07/src/SIL.Machine.AspNetCore/Usings.cs#L33)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Are we using JSON.NET anywhere?
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/machine/104#-Ng4q3JK3cSPANIU6FcN:-Ng4q3JL2odCtZQPXTtf:b2lmfz6) ([raw file](https://github.com/sillsdev/machine/blob/369f3d37b7e4c1efe85c9848c197497c1be265c5/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
> ```Smalltalk
>                 request.EngineId,
>                 request.BuildId,
>                 request.HasOptions ? request.Options : null,
> ```

HasOptions nor Options doesn't exist in StartBuildRequest and breaks the build.  What gives?

https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104

Warning: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineService.cs(42,73): warning CS8765: Nullability of type of parameter 'buildOptions' doesn't match overridden member (possibly because of nullability attributes). \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]

[19](https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104#step:11:20)Error: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs(102,25): error CS1061: 'StartBuildRequest' does not contain a definition for 'HasOptions' and no accessible extension method 'HasOptions' accepting a first argument of type 'StartBuildRequest' could be found (are you missing a using directive or an assembly reference?) \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]

[20](https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104#step:11:21)Error: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs(102,46): error CS1061: 'StartBuildRequest' does not contain a definition for 'Options' and no accessible extension method 'Options' accepting a first argument of type 'StartBuildRequest' could be found (are you missing a using directive or an assembly reference?) \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/machine/104#-Ng4q3JK3cSPANIU6FcN:-Ng57BRzEHyBd38AoHt1:b8f95md) ([raw file](https://github.com/sillsdev/machine/blob/369f3d37b7e4c1efe85c9848c197497c1be265c5/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

HasOptions nor Options doesn't exist in StartBuildRequest and breaks the build.  What gives?

https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104

Warning: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineService.cs(42,73): warning CS8765: Nullability of type of parameter 'buildOptions' doesn't match overridden member (possibly because of nullability attributes). \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]

[19](https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104#step:11:20)Error: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs(102,25): error CS1061: 'StartBuildRequest' does not contain a definition for 'HasOptions' and no accessible extension method 'HasOptions' accepting a first argument of type 'StartBuildRequest' could be found (are you missing a using directive or an assembly reference?) \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]

[20](https://github.com/sillsdev/machine/actions/runs/6434132684/job/17472711751?pr=104#step:11:21)Error: /home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs(102,46): error CS1061: 'StartBuildRequest' does not contain a definition for 'Options' and no accessible extension method 'Options' accepting a first argument of type 'StartBuildRequest' could be found (are you missing a using directive or an assembly reference?) \[/home/runner/work/machine/machine/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj\]
</blockquote></details>

No, no, that's a serval-machine conflict issue. It's rectified if you use the config-passing branches form both repos.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/104#-:-Ng5D-Tj6aZ8OCHW02HP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/machine/104#-Ng4q3JK3cSPANIU6FcN:-NgJi5sOCtkVpEynZv7G:bfjrzw1) ([raw file](https://github.com/sillsdev/machine/blob/369f3d37b7e4c1efe85c9848c197497c1be265c5/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs#L102)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

No, no, that's a serval-machine conflict issue. It's rectified if you use the config-passing branches form both repos.
</blockquote></details>

We need to release GRPC nugget package.

**Comment by Enkidu93** [comment]
Because of the refactoring, I've decided to open a new PR on a new branch.

**Pull request closed without merging**
