### PR TITLE
Add functionality to Paratext project settings parser

### PR DESCRIPTION
**Pull request by ddaspit**
- add ParatextProjectSettings.GetBookFileName()
- add ZipParatextProjectSettingsParserBase class

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/163)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ParatextProjectSettings.cs` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine/163#-NpZfYCR3-7Drh-nL4Fj:-NpZfYCR3-7Drh-nL4Fk:b-r4958j) ([raw file](https://github.com/sillsdev/machine/blob/d8a310b1c1ae0bef18eedaef44279244f69ccaab/src/SIL.Machine/Corpora/ParatextProjectSettings.cs#L48)):*
> ```Smalltalk
>         public string BiblicalTermsFileName { get; }
> 
>         public string GetBookFileName(string bookId)
> ```

Yes - this should be in Machine, not Serval - I agree.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ZipParatextProjectSettingsParserBase.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/163#-NpZfk6J73G8qGgOrDAB:-NpZfk6J73G8qGgOrDAC:b-rte7j9) ([raw file](https://github.com/sillsdev/machine/blob/d8a310b1c1ae0bef18eedaef44279244f69ccaab/src/SIL.Machine/Corpora/ZipParatextProjectSettingsParserBase.cs#L6)):*
> ```Smalltalk
> namespace SIL.Machine.Corpora
> {
>     public abstract class ZipParatextProjectSettingsParserBase : ParatextProjectSettingsParserBase
> ```

This looks like reducing code duplication with Serval and Machine and putting more of the Paratext logic into Machine - is that correct?  Is there something else that is going on as well?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/ParatextProjectSettings.cs` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine/163#-NpZfYCR3-7Drh-nL4Fj:-NpZg5457L5Oo-Qj55qr:bop513c) ([raw file](https://github.com/sillsdev/machine/blob/d8a310b1c1ae0bef18eedaef44279244f69ccaab/src/SIL.Machine/Corpora/ParatextProjectSettings.cs#L48)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes - this should be in Machine, not Serval - I agree.
</blockquote></details>

I still would like a reference to some other documentation from Paratext, if it exists, or at least a reference to the fact that there is no reference.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/163)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Comment by johnml1135** [comment]
Does some testing need to be stripped out of Serval and put here?  There should at least be a few for getBookFilename.  I am assuming the base class is covered from the parent class tests.  Where is the coverage report?

**Review by ddaspit — COMMENTED** [review]
I added unit tests for `GetBookFileName`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/163#-:-Np_HK2x9FmusT4cS6un:b-ggrpyu)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParatextProjectSettings.cs` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine/163#-NpZfYCR3-7Drh-nL4Fj:-Np_Gvvs91zMJsGTMhIT:b-s0zxzu) ([raw file](https://github.com/sillsdev/machine/blob/d8a310b1c1ae0bef18eedaef44279244f69ccaab/src/SIL.Machine/Corpora/ParatextProjectSettings.cs#L48)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I still would like a reference to some other documentation from Paratext, if it exists, or at least a reference to the fact that there is no reference.
</blockquote></details>

There simply is nothing to reference (code or documentation). It doesn't really seem helpful to reference that there is no reference.
___
*[`src/SIL.Machine/Corpora/ZipParatextProjectSettingsParserBase.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/machine/163#-NpZfk6J73G8qGgOrDAB:-Np_GtsR0Z6trfFnz5Ge:b-2uv1uy) ([raw file](https://github.com/sillsdev/machine/blob/d8a310b1c1ae0bef18eedaef44279244f69ccaab/src/SIL.Machine/Corpora/ZipParatextProjectSettingsParserBase.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This looks like reducing code duplication with Serval and Machine and putting more of the Paratext logic into Machine - is that correct?  Is there something else that is going on as well?
</blockquote></details>

You are correct.

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/163#-:-Np_xmrQ2IbBHWrQ9SnE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
