### PR TITLE
Fixes #133

### LINKED ISSUE #133: Health check ClearML Health Check with status Unhealthy
We continue to get a few of these each day.  Can we increase the threshold in which we call it unhealthy?  What is it now?  Can it be 5 minutes at least?

### PR DESCRIPTION
**Pull request by Enkidu93**
Implemented same logic in ClearML as in S3.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/135)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/135)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 35 at r1](https://reviewable.io/reviews/sillsdev/machine/135#-NiuPZLE7Acgn5Pfxy0W:-NiuPZLE7Acgn5Pfxy0X:b-fs7327) ([raw file](https://github.com/sillsdev/machine/blob/2f3f0529cdf2ec4b01c40ad933e5a5bf31e7dfce/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L35)):*
> ```Smalltalk
>                     $"No ClearML agents are available for configured queue \"{_options.CurrentValue.Queue}\""
>                 );
>             _numConsecutiveFailures = 0;
> ```

You should be locking all access to `_numConsecutiveFailures`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/135)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 35 at r1](https://reviewable.io/reviews/sillsdev/machine/135#-NiuPZLE7Acgn5Pfxy0W:-NiuSmPF6emYbsDHa40c:b-b9elkf) ([raw file](https://github.com/sillsdev/machine/blob/2f3f0529cdf2ec4b01c40ad933e5a5bf31e7dfce/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L35)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should be locking all access to `_numConsecutiveFailures`.
</blockquote></details>

Done. I noticed that S3 was missing a lock as well in the same place, so I changed that as well.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/135#-:-Niuc80z2oALKu_AV_AP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
