### PR TITLE
auto-add missing verses.

### PR DESCRIPTION
**Pull request by johnml1135**
Auto add missing verses -  https://github.com/sillsdev/serval/issues/414

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/213)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
I believe that the core underlying issue is that the `ScriptureRefUsfmParserHandlerBase` class ignores duplicate verses. Maybe we should reevaluate this behavior, since the assumption was that this was a mistake in the USFM. The examples from this issue were intentional. If we change the underlying behavior, it should fix this issue.

> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/213#-:-O-llRTU9X5ZQvJhlC_R:b-j3fn3m)* status: 4 of 9 files reviewed, all discussions resolved

**Comment by johnml1135** [comment]
I don't fully understand your rationale.  I updated the code to reflect the pattern of the other PR.  It appears to respond intelligently to the test cases added.

**Comment by ddaspit** [comment]
https://github.com/sillsdev/serval/issues/414 is not something that Scripture Forge has asked for, so I think we should defer it for now. In the case of https://github.com/sillsdev/serval/issues/411, I would say that Serval is actually working as intended. We should wait for feedback on how Scripture Forge wants to handle that issue for continuing.

**Comment by johnml1135** [comment]
I pulled out the 2 fixes into 2 different pull requests.  Now this is just add missing verses.  The other issue is handled elsewhere.

**Comment by johnml1135** [comment]
This is no longer needed and being supplanted by giving the user the choice to use the source USFM structure.

**Pull request closed without merging**
