### PR TITLE
Fixes https://github.com/sillsdev/serval/issues/449

### PR DESCRIPTION
**Pull request by Enkidu93**
I'm not sure that this is the cleanest solution, but it does resolve the issue. Please critique :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/232)

### CODE REVIEW

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/232)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 117 at r1](https://reviewable.io/reviews/sillsdev/machine/232#-O4BvkoF-YZzgk76Lraf:-O4ByB877deYKBbMNv3_:b23lzjr) ([raw file](https://github.com/sillsdev/machine/blob/e49bd29b79410f1880fcf29b07e1b7e05ef493ac/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L117)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Non verse followed by verse?  Isn't it the other way around?
</blockquote></details>

That was a copy-paste mistake. Done.

**Comment by Enkidu93** [comment]
That works, @ddaspit . I saw that function but dismissed it because of the naming.

**Review by ddaspit — APPROVED** [review]
Opt breaks are basically text, so we want to handle them the same way. I also made some small changes to the unit test names.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/232#-:-O4C3QZBAGY3wTvtSBqp:b-vgsu7b)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Review by Enkidu93 — COMMENTED** [review]
Sounds good. It surprised me that there weren't tests yet for opt breaks. And I should have noted that I confirmed that the original changes resolve the two related failures we've seen coming out of SF. I'd assume these also resolve it given they're ultimately doing similar things.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/232#-:-O4C45QfEmYu0kn6I2pC:b-t81ore)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Review by ddaspit — COMMENTED** [review]
There are opt break tests in the `UsfmFileTextTests` fixture, but it only tested for opt breaks in the middle of a segment.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/232#-:-O4C6FBuA4UlsJ6x3vSt:b-ahcbyn)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by johnml1135** [comment]
Aside from outbreaks not being documented as part of USFM, it looks great.

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
