### PR TITLE
Update garbage collection settings.

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/serval/issues/361

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/185)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/185)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/185#-NvYaoJ3Bi6hwtO1M4ce:-NvYaoJ3Bi6hwtO1M4cf:b-aqlb5z) ([raw file](https://github.com/sillsdev/machine/blob/cea2d3326f4ba220ae70e7eec45ebef2d3015938/src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs#L60)):*
> ```Smalltalk
>             await DoWorkAsync(engineId, buildId, data, buildOptions, @lock, cancellationToken);
>             // actively clear out memory when the job is complete.
>             GC.Collect();
> ```

We should not manually trigger garbage collection. It will have a negative impact on performance. The GC is highly optimized and knows way better than us when it should be triggered.
___
*[`src/SIL.Machine.Serval.EngineServer/runtimeconfig.template.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine/185#-NvYb4TJ4WIa6qSHzK8z:-NvYb4TJ4WIa6qSHzK9-:b9qjpfa) ([raw file](https://github.com/sillsdev/machine/blob/cea2d3326f4ba220ae70e7eec45ebef2d3015938/src/SIL.Machine.Serval.EngineServer/runtimeconfig.template.json#L2)):*
> ```JSON
> {
>     "configProperties": {
> ```

I'm not sure I understand what issue we are trying to solve with this change. Also, we should not mess with the default GC settings. It will probably result in a negative impact on performance.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Serval.EngineServer/runtimeconfig.template.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine/185#-NvYb4TJ4WIa6qSHzK8z:-NvaqBsa-I7xZx1s3591:btudeag) ([raw file](https://github.com/sillsdev/machine/blob/cea2d3326f4ba220ae70e7eec45ebef2d3015938/src/SIL.Machine.Serval.EngineServer/runtimeconfig.template.json#L2)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand what issue we are trying to solve with this change. Also, we should not mess with the default GC settings. It will probably result in a negative impact on performance.
</blockquote></details>

https://github.com/sillsdev/serval/issues/338#issuecomment-2058955041

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/185#-NvYaoJ3Bi6hwtO1M4ce:-NvarUQa3-GBGC23s9eP:b3z065a) ([raw file](https://github.com/sillsdev/machine/blob/cea2d3326f4ba220ae70e7eec45ebef2d3015938/src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should not manually trigger garbage collection. It will have a negative impact on performance. The GC is highly optimized and knows way better than us when it should be triggered.
</blockquote></details>

I'm fine going with minimal GC changes. From my reading, in "job based" processing, calling the GC can be ok to clear memory, but if it is not needed, we can keep it out.

**Comment by johnml1135** [comment]
These changes will not be implemented now - unless we determine that it's needed.

**Pull request closed without merging**
