### PR TITLE
Add support for mixed source corpora

### PR DESCRIPTION
**Pull request by ddaspit**
- align all Scripture corpora to Original versification

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Utils/EnumerableExtensions.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsDv_h36Vp3pvySdAiJ:-NsDv_h36Vp3pvySdAiK:b-rkdu1c) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine/Utils/EnumerableExtensions.cs#L13)):*
> ```Smalltalk
>             Func<IEnumerable<TSource>, TResult> selector
>         )
>         {
> ```

This is not really a zipper - it is a delegated selector.  Also, if there is not an entry in all sources, it just bombs out (rather than returning whichever source has data, etc.).  This behavior is not clear from the naming, so it should likely be in a comment.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE0vSiCHz35cjL_oMj:-NsE0vSiCHz35cjL_oMk:b-p62ifb) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L32)):*
> ```Smalltalk
>     }
> 
>     internal int Seed
> ```

It is never set - why not just make _seed a const?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE15QC7pouRauFC5aQ:-NsE15QD12KzxfaUWVYQ:bxq3c6w) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L122)):*
> ```Smalltalk
>                     continue;
> 
>                 //var src1 = AlignScripture(sourceTextCorpora[0], targetTextCorpus).ToArray();
> ```

Commented out code should be removed.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE1OTd8qOc0GVJ-1xo:-NsE1OTd8qOc0GVJ-1xp:btvmym2) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L130)):*
> ```Smalltalk
>                 foreach (Row?[] rows in AlignCorpora(sourceTextCorpora, targetTextCorpus))
>                 {
>                     if (skipCount > 0)
> ```

So, you chose to implement the skip count?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Utils/EnumerableExtensions.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsDv_h36Vp3pvySdAiJ:-NsE3gBzCgYAtsw7_ozj:bomczf3) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine/Utils/EnumerableExtensions.cs#L13)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is not really a zipper - it is a delegated selector.  Also, if there is not an entry in all sources, it just bombs out (rather than returning whichever source has data, etc.).  This behavior is not clear from the naming, so it should likely be in a comment.
</blockquote></details>

I just checked - the standard zip takes the [minimum number of the two enumerables](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip?view=net-8.0) - that is fine.  The name should be updated to reflect that it is not truly zipping but something similar to `SelectFromMany`.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 303 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE9MVh3DHjh3azwuob:-NsE9MVh3DHjh3azwuoc:bac8bl3) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L303)):*
> ```Smalltalk
>         foreach (
>             (VerseRef vref, string srcSegment, string trgSegment) in srcCorpus
>                 .ExtractScripture()
> ```

I assume that this will always create a full set of original versification elements.  Is that correct?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 271 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEAY0T1NHlO3O2kfpe:-NsEAY0T1NHlO3O2kfpf:b2tdmap) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L271)):*
> ```Smalltalk
>                 .Select(sc => AlignScripture(sc, trgCorpus))
>                 .ZipMany(rows => rows.ToArray())
>                 .Where(rows => rows.Any(r => r is null || r.SourceSegment.Length > 0 || r.TargetSegment.Length > 0));
> ```

The null, length logic is a bit unclear because it interacts with the AlignScripture logic.  Could it be replaced with a function such as `HasContentOrInRange(r)`?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NsEJ3yeCQHywkdsoQ7O:bw4ii2s) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
> ```Smalltalk
>             ITextCorpus? targetTextCorpus = _corpusService.CreateTextCorpora(corpus.TargetFiles).FirstOrDefault();
>             if (sourceTextCorpus is null || targetTextCorpus is null)
>                 continue;
> ```

The logic is a bit different - skipping if one is null for instance.  Is there significance to these changes other than aligning with the lower level functions (CreatTextCorpora, etc.)?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: 0 of 35 files reviewed, 9 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE0vSiCHz35cjL_oMj:-NsEmMIvC--smEUBxVz9:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L32)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I meant to set this in the unit tests, so that we can ensure that it works consistently.
</blockquote></details>

Done
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE15QC7pouRauFC5aQ:-NsEmOXL381DoIZCiDeU:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L122)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Oops, I will remove it.
</blockquote></details>

Done
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 162 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEHjpE1cPWlktaxgeh:-NsEmRO7ExOOrgF-AK6i:bsng317) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L162)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I agree. I've never really liked the way this was implemented. It is designed this way so that we can use `JsonSerializer.SerializeAsync` to write out the JSON.
</blockquote></details>

I refactored this to use `Utf8JsonWriter`.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 271 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEAY0T1NHlO3O2kfpe:-NsEmZ6m1wUlLdw_ldAk:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L271)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I will add a comment.
</blockquote></details>

Done

**Comment by johnml1135** [comment]
The SMT changes are untested.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 162 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEHjpE1cPWlktaxgeh:-NsF878lC4lUm34SYAjN:b-9ng0t7) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L162)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I refactored this to use `Utf8JsonWriter`.
</blockquote></details>

Its cleaner now :-)

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE00Qf9QiKNOzuhNvy:-NsE00Qf9QiKNOzuhNvz:b-gy6ois) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L23)):*
> ```Smalltalk
>         ICorpusService corpusService,
>         ILanguageTagService languageTagService
>     )
> ```

Why did you get rid of the primary constructor?  It would support the random

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NsF91Mi1VTDkLuMd89p:b-3y959q) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

SMT doesn't support mixed source, so we only use the first source corpus.
</blockquote></details>

Just needs some regression tests...

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Utils/EnumerableExtensions.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsDv_h36Vp3pvySdAiJ:-NsFA0bn9phTgkw_b41e:b5jsbxh) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine/Utils/EnumerableExtensions.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand. It is doing the exact same thing as `Zip` just for an arbitrary number of lists instead of 2 or 3.
</blockquote></details>

I misunderstood.  Selector is not the random function :-P.  It makes sense now.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/CorpusService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE-49W8sKQoLwy2F7i:-NsFAqYo6ZnXMJDASJ7n:b3c6vro) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/CorpusService.cs#L32)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is doing what I want. Each dictionary in `textFileCorpora` represents a separate text corpus.
</blockquote></details>

I would like a short walk-through if possible.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs` line 132 at r2](https://reviewable.io/reviews/sillsdev/machine/177#-NsFEwC-2x2TmGva1yOt:-NsFEwC-2x2TmGva1yOu:b-d7c1qe) ([raw file](https://github.com/sillsdev/machine/blob/3c927cbdad7acc23d486277ef7d5853c79210ebd/tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs#L132)):*
> ```Smalltalk
> 
>         Assert.That(await env.GetTrainCountAsync(), Is.EqualTo(17));
>         Assert.That(await env.GetPretranslateCountAsync(), Is.EqualTo(8));
> ```

It would be great to have a test for Paratext and and Text mixes source where it is confirmed that there are selections from both sources.  Count the number of source 1's and source 2's in the written text file?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 34 of 35 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: 30 of 36 files reviewed, 4 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE00Qf9QiKNOzuhNvy:-NsKFyOQ6zVn3zeIKUe2:bl140ha) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L23)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why did you get rid of the primary constructor?  It would support the random
</blockquote></details>

I cannot reference another field when initializing a field in a declaration. I can reference another field in a constructor. 
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NsKFR-L5snjg1hdK3YO:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Just needs some regression tests...
</blockquote></details>

Done.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs` line 132 at r2](https://reviewable.io/reviews/sillsdev/machine/177#-NsFEwC-2x2TmGva1yOt:-NsKFKKj29f8OiXLiOOn:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/3c927cbdad7acc23d486277ef7d5853c79210ebd/tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs#L132)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It would be great to have a test for Paratext and and Text mixes source where it is confirmed that there are selections from both sources.  Count the number of source 1's and source 2's in the written text file?
</blockquote></details>

Done.

**Review by Enkidu93 — COMMENTED** [review]
Just taking a peek, Damien, to keep up-to-date with code changes. An exciting addition! :)

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177#-:-NsT_nIy09QCF_G3ddu0:b-s2p84f)* status: 30 of 36 files reviewed, 6 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/177#-NsTZjNY9I0MplInYymn:-NsTZjNY9I0MplInYymo:b98s5m1) ([raw file](https://github.com/sillsdev/machine/blob/ac751b7f39972260d3e3058c73e30a15ca95b622/tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs#L7)):*
> ```Smalltalk
> {
>     [Test]
>     public async Task RunAsync_FilterOutEverything()
> ```

Do you have a strong distaste for using `TestCase` or `TestCaseSource`? Removing the parsing makes sense, but it does seem like 5 or so of these tests are basically the same with one variation or so :shrug:. I guess this is more readable but it is duplicated code. 
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 398 at r3](https://reviewable.io/reviews/sillsdev/machine/177#-NsTZCsA-Bx2-Ta2gIug:-NsTZCsA-Bx2-Ta2gIuh:b-fntybg) ([raw file](https://github.com/sillsdev/machine/blob/ac751b7f39972260d3e3058c73e30a15ca95b622/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L398)):*
> ```Smalltalk
>                                     3,
>                                     1.0,
>                                     ".".Split(),
> ```

Totally unimportant, but just curious about this change: Isn't using split a bit less readable/clear? Why not just `["."]`? Am I missing something?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: 30 of 36 files reviewed, 6 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/177#-NsTZjNY9I0MplInYymn:-NsTkTJdBu2VIS7Ql1bS:b-hfnlfz) ([raw file](https://github.com/sillsdev/machine/blob/ac751b7f39972260d3e3058c73e30a15ca95b622/tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Do you have a strong distaste for using `TestCase` or `TestCaseSource`? Removing the parsing makes sense, but it does seem like 5 or so of these tests are basically the same with one variation or so :shrug:. I guess this is more readable but it is duplicated code.
</blockquote></details>

It was difficult for me to understand what was being tested, because the test cases are a mix of unlabeled variables. Separating them out made it much clearer to me. As developers on a team, we spend more time reading code than typing code, so I generally lean towards readability over conciseness. Here are my suggestions for using test cases:

1. If you have to pass in many variables to the test case, consider not using test cases. It can difficult to parse all of the variables to figure out what is being tested.
2. If a test case variable changes the logic of the test, consider not using test cases.
3. If you are using test cases, always provide a description.

An example of a good use of test cases would be `LanguageTagServiceTests.ConvertToFlores200CodeTest`.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 398 at r3](https://reviewable.io/reviews/sillsdev/machine/177#-NsTZCsA-Bx2-Ta2gIug:-NsTnvUK6UvJTiHOsiCS:bi8q6sk) ([raw file](https://github.com/sillsdev/machine/blob/ac751b7f39972260d3e3058c73e30a15ca95b622/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L398)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Totally unimportant, but just curious about this change: Isn't using split a bit less readable/clear? Why not just `["."]`? Am I missing something?
</blockquote></details>

This was just to make it consistent with other `new WordGraphArc()` calls.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NsYSxJm-Eki8f8trQvr:b-f1aq7n) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the test coverage added, nor the extra tests.  Am I missing something?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NtSUM4KAn8iPcmktWMc:b-pp8oko) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I don't see the test coverage added, nor the extra tests.  Am I missing something?
</blockquote></details>

I updated the existing `SmtTransferEngineService` tests

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NtVnd24BNwX34QhAcYx:b2l29jx) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I updated the existing `SmtTransferEngineService` tests
</blockquote></details>

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: 33 of 40 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsEJ3yeCQHywkdsoQ7N:-NtXZPYM-cceKl0jeUKT:b-od781a) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs#L60)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>


</blockquote></details>

It should actually be tested now.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/CorpusService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE-49W8sKQoLwy2F7i:-NtaOvwHAVWxk49raRlR:bmit1j8) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/CorpusService.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would like a short walk-through if possible.
</blockquote></details>

I got it - the changes are for mixed source.  If there are texts with the same textId in the same corpus, add create a corpus for each instance of textId or each paratext project.  This should be in a comment - it is not clear from the code.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/CorpusService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/177#-NsE-49W8sKQoLwy2F7i:-NtadadQ85S6OOLASPMj:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/c2e06596ffdee586e0e37f2ca636a6dc042a9883/src/SIL.Machine.AspNetCore/Services/CorpusService.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I got it - the changes are for mixed source.  If there are texts with the same textId in the same corpus, add create a corpus for each instance of textId or each paratext project.  This should be in a comment - it is not clear from the code.
</blockquote></details>

Done.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
