### PR TITLE
Fix some logic found during e2e testing

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/178)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/178)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 124 at r1](https://reviewable.io/reviews/sillsdev/machine/178#-NtvLd4_AP-y1R-7KsWJ:-NtvLd4_AP-y1R-7KsWK:biobysx) ([raw file](https://github.com/sillsdev/machine/blob/26f8c4b464d4ef29468fb1747e3b5480614bd763/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L124)):*
> ```Smalltalk
>         {
>             ITextCorpus[] sourceTextCorpora = _corpusService.CreateTextCorpora(corpus.SourceFiles).ToArray();
>             ITextCorpus? targetTextCorpus =
> ```

The type is no longer nullable.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 124 at r1](https://reviewable.io/reviews/sillsdev/machine/178#-NtvLd4_AP-y1R-7KsWJ:-NtwuvfXEsbgh12zkbm-:b-q8z3c5) ([raw file](https://github.com/sillsdev/machine/blob/26f8c4b464d4ef29468fb1747e3b5480614bd763/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L124)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The type is no longer nullable.
</blockquote></details>

True. I'll fix it.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/178#-:-NtwvvEQDxu9h6omEUAk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
