### PR TITLE
Fixes #82 --ECL

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/57)

### CODE REVIEW

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/57#-:-NcSRBjzEtXobmV3e_RF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by Enkidu93 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by Enkidu93 — APPROVED** [review]

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
