### PR TITLE
Refactored S3 access

### PR DESCRIPTION
**Pull request by Enkidu93**
Reverted to low-level implementation (removing need for large buffers); fixes Refine S3 bucket usage #61

Also removed synchronous write; fixes S3 remove sync write (async only) #64

Note: Dispose has async calls/logic because "await using" on the StreamWriters in ClearMLNMTBuildJob calls DisposeAsync on the StreamWriters but Dispose on the BaseStream. This is the only way I could find to circumvent this - other solutions are welcome given there's a workaround I'm missing.

--ECL

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-Ndl0uKI4lhol9NkSE2X:-Ndl0uKI4lhol9NkSE2Y:b5xyg4l) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L82)):*
> ```Smalltalk
>         return new BufferedStream(
>             new S3WriteStream(_client, objectId, _bucketName, response.UploadId),
>             1024 * 1024 * 5
> ```

I've seen this twice. This should probably be a constant, maybe on `S3WriteStream`.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBZAr0tX3DIHVLh2D:-NdlBZAr0tX3DIHVLh2E:b-s3en7n) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L18)):*
> ```Smalltalk
>         _bucketName = bucketName;
>         _uploadId = uploadId;
>         _logger = new LoggerFactory().CreateLogger<S3WriteStream>();
> ```

You should inject `ILoggerFactory` into `S3FileStorage`, use it to create the logger instance, and pass it to this class in the constructor.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 79 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlB7nd4xVihBHtvWHr:-NdlB7neBKXU1GpdwoYV:b-28u2ik) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L79)):*
> ```Smalltalk
>         catch (Exception e)
>         {
>             await Abort(e);
> ```

You should rethrow the exception after aborting.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 109 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBNvHDFZ_6Gu1z_70:-NdlBNvHDFZ_6Gu1z_71:b-28u2ik) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L109)):*
> ```Smalltalk
>             catch (Exception e)
>             {
>                 Abort(e).WaitAndUnwrapException();
> ```

You should rethrow the exception after aborting.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 141 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBTjU5Zc4MkxxmWm5:-NdlBTjU5Zc4MkxxmWm6:b-jqgsu7) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L141)):*
> ```Smalltalk
>     }
> 
>     private async Task Abort(Exception e)
> ```

This should be suffixed with `Async`.

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBZAr0tX3DIHVLh2D:-NdlWbpq8tCJeH6xDIeO:b-92hr4s) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should inject `ILoggerFactory` into `S3FileStorage`, use it to create the logger instance, and pass it to this class in the constructor.
</blockquote></details>

Can I do that or do I have to inject it at the ShareFileService level since the S3FileStorage is manually constructed with its constructor? Is there a way to get around that - I hate to just pass LoggerFactories if there's a better way.

**Comment by johnml1135** [comment]
My review is honestly very brief - I am relying on Damien's review, being that he knows the interface and the memory buffer mechanisms better than I do.  Nothing stands out as an issue other than the question - I don't see any changes in the testing.  Are we testing the multipart upload/download?  Are we sure we are breaking and reconstituting these portions correctly?

**Review by Enkidu93 — COMMENTED** [review]
In which tests would you expect to see changes? The multipart upload strategy was being used from the get-go. It's just that we're using the SDK instead of hand-crafting http requests. I've followed the SDK pretty closely. The only difference is the strategy we use (which is ultimately borrowed from the stowage code) in which we write to a 5MB buffered stream (5MB being the max part size) which is flushed as needed, and then we complete the multipart upload on disposal. I can verify that it works properly inasmuch as the E2E tests cover file uploads. (e.g., NmtBatch passes). 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80#-:-NdosbYd6SoRmFKq-E37:bsk8ch1)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit)

___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-Ndl0uKI4lhol9NkSE2X:-NdosV_rERp44NHqM9Tb:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I've seen this twice. This should probably be a constant, maybe on `S3WriteStream`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 79 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlB7nd4xVihBHtvWHr:-NdosZVY1Xn3sjQk4las:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L79)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should rethrow the exception after aborting.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 109 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBNvHDFZ_6Gu1z_70:-NdosZn087pHP_p_KyYT:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should rethrow the exception after aborting.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 141 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBTjU5Zc4MkxxmWm5:-Ndos_QP57-n6AOmiYEJ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L141)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be suffixed with `Async`.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-Ndl0uKI4lhol9NkSE2X:-Ndpfv-KBYxQ57ulAFHX:bfjzzpi) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L82)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`MaxPartSize` would probably be a better name. 
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-NdlBZAr0tX3DIHVLh2D:-NdpfIQt-6njw6UEzxDm:bstbypn) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L18)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Can I do that or do I have to inject it at the ShareFileService level since the S3FileStorage is manually constructed with its constructor? Is there a way to get around that - I hate to just pass LoggerFactories if there's a better way.
</blockquote></details>

Yes, you are correct. `SharedFileService` is where you need to inject the logger factory. Unfortunately, there isn't a much better way to handle this.
___
*[`src/SIL.Machine.AspNetCore/Services/SharedFileService.cs` line 1 at r2](https://reviewable.io/reviews/sillsdev/machine/80#-NdpgtEa2z-UeEg8_0mY:-NdpgtEa2z-UeEg8_0mZ:bxpq3b1) ([raw file](https://github.com/sillsdev/machine/blob/4513ee74bf1a9546ea95749fe8ac397d9055482b/src/SIL.Machine.AspNetCore/Services/SharedFileService.cs#L1)):*
> ```Smalltalk
> using SIL.Reporting;
> ```

Is this using needed?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/80#-Ndl0uKI4lhol9NkSE2X:-NdphxXk2IQNZb2mjYYj:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/31774611c296d7d76b2007d427f913b5d23d2fb1/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`MaxPartSize` would probably be a better name.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SharedFileService.cs` line 1 at r2](https://reviewable.io/reviews/sillsdev/machine/80#-NdpgtEa2z-UeEg8_0mY:-NdphzGTBIgMInoNYOl-:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/4513ee74bf1a9546ea95749fe8ac397d9055482b/src/SIL.Machine.AspNetCore/Services/SharedFileService.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is this using needed?
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
At least in one "missing test" - it would be good to test that the S3 multi-part loading works.  Even if it is a test that uploads a larger file (of random data even) to S3 bucket and then downloads it again.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
This sounds like an integration test. We currently haven't implemented any integration tests for Machine. Could this be covered in a Serval E2E test? Although I don't want to get into the business of writing E2E tests to cover small test cases deep in the system. I guess I am asking, do any of our existing E2E tests cover this code branch?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80#-:-NdpmXaYCQ25ldDR3Ic5:b-mwc33m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> This sounds like an integration test. We currently haven't implemented any integration tests for Machine. Could this be covered in a Serval E2E test? Although I don't want to get into the business of writing E2E tests to cover small test cases deep in the system. I guess I am asking, do any of our existing E2E tests cover this code branch?
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/80#-:-NdpmXaYCQ25ldDR3Ic5:b-mwc33m)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)
 is
@ddaspit @johnml1135 The easiest way I see to cover the multi-part element (if that's what you're getting at) is to change (or add a near clone of) one of the E2E tests in serval that uploads a file of more than 5MB.

**Comment by johnml1135** [comment]
E2E test for multi-part upload can be handled here: https://github.com/sillsdev/serval/issues/125

**Pull request merged**
