### PR TITLE
Recreate the USFM text updating issue in unit tests.

### PR DESCRIPTION
**Pull request by johnml1135**
Make USFM updating errors more explicit: https://github.com/sillsdev/serval/issues/398

@ddaspit  - can up finish resolving the USFM updating parse stack empty issue?

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/206)

### CODE REVIEW

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 5 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 5 files at r2, 5 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/206#-:-NzdwioAD4jf55TH6Jko:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`.ignore` line 1 at r5](https://reviewable.io/reviews/sillsdev/machine/206#-NzdvpRu4HO9rbUU_nDd:-NzdvpRu4HO9rbUU_nDe:bus3u8o) ([raw file](https://github.com/sillsdev/machine/blob/da949b98667f8581ac93eb5a66f5f50f05638aaf/.ignore#L1)):*
> ```
> !tests/SIL.Machine.Tests/Corpora/TestData/usfm/source/*
> ```

What is this file used for?

**Comment by johnml1135** [comment]
*[`.ignore` line 1 at r5](https://reviewable.io/reviews/sillsdev/machine/206#-NzdvpRu4HO9rbUU_nDd:-NzhnGB0CbjjXlWaVX5l:b-etyh0a) ([raw file](https://github.com/sillsdev/machine/blob/da949b98667f8581ac93eb5a66f5f50f05638aaf/.ignore#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is this file used for?
</blockquote></details>

These are where the manual tests can be run.  By adding this file, the files put here will be searchable, but will not be added to git. https://stackoverflow.com/questions/55949132/vscode-how-to-get-file-search-not-content-to-include-git-ignored-files/55949239#55949239

**Pull request merged**
