### PR TITLE
Better USFM parsing error visibility 

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/serval/issues/388

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/199)

### CODE REVIEW

**Review by ddaspit — APPROVED** [review]
I added a `UsfmParserException` class. It should provide the exact location where the error occurred. I also removed the exception from `UsfmTextBase`. It doesn't provide any more information than the `UsfmParserException`.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/199#-:-NxsDV-Q0j3jYvA6IBIl:b-bd8p9o)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
We also have a request to add which corpus it's from.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/199)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 204 at r3](https://reviewable.io/reviews/sillsdev/machine/199#-NyM8hvS75sEFbVkb4L1:-NyM8hvS75sEFbVkb4L2:bjouny3) ([raw file](https://github.com/sillsdev/machine/blob/2be531120fc9d1c1f19eb459817fcf2609187743/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L204)):*
> ```Smalltalk
>             {
>                 throw new InvalidOperationException(
>                     $"Error occurred while preprocessing the corpus {corpus.Id}. Error: {ex.Message}",
> ```

We should also tag the file that is causing an issue.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Corpora/UsfmFileText.cs` line 43 at r5](https://reviewable.io/reviews/sillsdev/machine/199#-NyMHGr24dju-JkAPXvS:-NyMHGr24dju-JkAPXvT:b-57xtoe) ([raw file](https://github.com/sillsdev/machine/blob/2f65f630b43713f4c41bbb05e9c78da2c78e247e/src/SIL.Machine/Corpora/UsfmFileText.cs#L43)):*
> ```Smalltalk
>                     .SetValue(e, $"{_fileName}: {e.Message}");
>                 throw e;
>             }
> ```

@ddaspit  - what do you think about spitting out the filename like this?

**Comment by ddaspit** [comment]
I don't think it is necessary to output the filename. The verse ref should be sufficient to tell you what file in a project is having the issue.

**Comment by johnml1135** [comment]
But if there are two sources and one target scripture, they don't know which one to look at.  The ID of the paratext zip file should tell them more.

**Comment by ddaspit** [comment]
That is a good point. I will look at adding that. We might need to update the gRPC API to pass the file id.

**Review by ddaspit — COMMENTED** [review]
I created a separate [PR](https://github.com/sillsdev/machine/pull/201) to fix the exception.

> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/199#-:-NyS0Mln6AvpH1DqvTNp:b-vjdmz9)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Corpora/UsfmParser.cs` line 150 at r6](https://reviewable.io/reviews/sillsdev/machine/199#-NyR_bk65ugdQHnfTv81:-NyR_bk65ugdQHnfTv82:bhtifw2) ([raw file](https://github.com/sillsdev/machine/blob/77d072e4d47c3adb528d2d40a3538eddaaff2ce7/src/SIL.Machine/Corpora/UsfmParser.cs#L150)):*
> ```Smalltalk
>                 throw new UsfmParserException(
>                     $"An error occurred while parsing USFM. Verse: {State.VerseRef}, with token {State.Token} and error: '{ex.Message}'. "
>                         + $"The surrounding context is: {previousTokens}<<<{State.Token}>>>{nextTokens}",
> ```

Please change this back. The verse ref and verse offset should be sufficient for developers to see where the problem occurred.

**Comment by ddaspit** [comment]
There's been a lot of churn on this PR, so I submitted a separate [PR](https://github.com/sillsdev/machine/pull/202) that throws an exception with all of the information we need. I'm going to close this PR.

**Pull request closed without merging**
