### PR TITLE
Try 2 for editor config:

### PR DESCRIPTION
**Pull request by johnml1135**
* Namespace always file level
* Always primary constructor
* Inline null checks
* Enforce naming
* Fix spelling mistakes
* simplify default initializations
* Add static and readonly where valid
* Remove unnecessary usings.
* No Functional change

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/171)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 173 of 229 files at r1, 22 of 28 files at r2, 44 of 44 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/171)* status: all files reviewed, 6 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Tokenization/LatinWordTokenizer.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnqFhn7G6d_Yg1tGZr:-NqnqFhn7G6d_Yg1tGZs:b-j41x9q) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/src/SIL.Machine/Tokenization/LatinWordTokenizer.cs#L27)):*
> ```Smalltalk
>         }
> 
>         public bool _treatApostropheAsSingleQuote = false;
> ```

This is public, so it shouldn't use an underscore. Is one of the rules incorrect?
___
*[`src/SIL.Machine.Tool/Program.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnseTU9SHyvJh8WOi9:-NqnseTU9SHyvJh8WOiA:barrsgy) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/src/SIL.Machine.Tool/Program.cs#L5)):*
> ```Smalltalk
> namespace SIL.Machine;
> 
> #pragma warning disable CA1724 // Naming conflict with SIL.Program - ignore.
> ```

I thought we changed this rule to suggestion.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/ModelCleanupServiceTests.cs` line 18 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqnt5pqDfCKSR7jgV9n:-Nqnt5pqDfCKSR7jgV9o:bbnr0ue) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.AspNetCore.Tests/Services/ModelCleanupServiceTests.cs#L18)):*
> ```Smalltalk
>         "models/engineId2_1.tar.gz", // 1 build behind
>         "models/engineId2_4.tar.gz", // 2 builds ahead
>         "models/wrongId_1.tar.gz",
> ```

Was it intentional to change these file names? Will it break anything?
___
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqntPQh0oqGMF3uPw7u:-NqntPQh0oqGMF3uPw7v:bex30r5) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L12)):*
> ```Smalltalk
> public abstract class HermitCrabTestBase
> {
>     protected TraceManager _ttraceManager = default!;
> ```

All of these protected fields should be turned into properties. Also, there is an extra "t" in the variable name.
___
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 900 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqntz8g8b0NFw9atzq5:-Nqntz8g8b0NFw9atzq6:b-7p66cg) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L900)):*
> ```Smalltalk
> 
> #pragma warning disable CA1720 // Identifier contains type name - Don't touch the legacy code
>     protected FeatureStruct Char(CharacterDefinitionTable table, string strRep)
> ```

You can rename this function.
___
*[`tests/SIL.Machine.Tests/PhoneticTestsBase.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnugCG8vsgiQWezEzs:-NqnugCG8vsgiQWezEzt:b-k321xg) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Tests/PhoneticTestsBase.cs#L10)):*
> ```Smalltalk
> public abstract class PhoneticTestsBase
> {
>     protected FeatureSystem _phoneticFeatSys = default!;
> ```

All of these protected fields should be turned into properties.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Tokenization/LatinWordTokenizer.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnqFhn7G6d_Yg1tGZr:-NrAjz4u3Y3XnrUZsQHy:b3kz91z) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/src/SIL.Machine/Tokenization/LatinWordTokenizer.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is public, so it shouldn't use an underscore. Is one of the rules incorrect?
</blockquote></details>

Added new rule: non-private fields are camelCase.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.Tool/Program.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnseTU9SHyvJh8WOi9:-NrAmp4Q0om1U4ADoM4q:b-jqparo) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/src/SIL.Machine.Tool/Program.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I thought we changed this rule to suggestion.
</blockquote></details>

Removed pragmas.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.AspNetCore.Tests/Services/ModelCleanupServiceTests.cs` line 18 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqnt5pqDfCKSR7jgV9n:-NrAmuym7lVik2dgbK9p:b-qpvp5l) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.AspNetCore.Tests/Services/ModelCleanupServiceTests.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Was it intentional to change these file names? Will it break anything?
</blockquote></details>

There were spelling errors when I wrote them.  They were unintentional.  It will not break anything.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 900 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqntz8g8b0NFw9atzq5:-NrAoIreEyu63me2SwsQ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L900)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can rename this function.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqntPQh0oqGMF3uPw7u:-NrAowuQ17mdXEUvB6tq:bhnf0r6) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

All of these protected fields should be turned into properties. Also, there is an extra "t" in the variable name.
</blockquote></details>

Should they have the underscore?  Should they be pascal?  I am assuming they would be treated as "non-public fields and properties" as _camelCase?

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqntPQh0oqGMF3uPw7u:-NrAqQjb0MIo27kZcWii:bm3xxr7) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L12)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should they have the underscore?  Should they be pascal?  I am assuming they would be treated as "non-public fields and properties" as _camelCase?
</blockquote></details>

I am assuming Pascal.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/PhoneticTestsBase.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnugCG8vsgiQWezEzs:-NrAqYVYDj09mdYIGpGN:b-n4mxs) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Tests/PhoneticTestsBase.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

All of these protected fields should be turned into properties.
</blockquote></details>

Done and Pascal.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine/Tokenization/LatinWordTokenizer.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqnqFhn7G6d_Yg1tGZr:-NrAqf0q8YW1UaDgOf6Q:b-gdqn9k) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/src/SIL.Machine/Tokenization/LatinWordTokenizer.cs#L27)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Added new rule: non-private fields are camelCase.
</blockquote></details>

Check that - all public fields are PascalCase.  I believe that is closer to the intention.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 26 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/171)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqntPQh0oqGMF3uPw7u:-NrBFU-c211jfs9b7hZP:bj9r733) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L12)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I am assuming Pascal.
</blockquote></details>

Once they are converted to protected properties, they should be treated like public properties, so they can be converted back to pascal case.
___
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 900 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqntz8g8b0NFw9atzq5:-NrBGD7BA-mO54pVu2Iv:b-z6y881) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L900)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would rename it to `Character`. I should have specified before.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 900 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-Nqntz8g8b0NFw9atzq5:-NrH4SLy9abLhHaCnN8p:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L900)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename it to `Character`. I should have specified before.
</blockquote></details>

Done

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/machine/171#-NqntPQh0oqGMF3uPw7u:-NrH4VK37viAt8Nz0RGI:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/a7b8cab9d9b95d2c8eb8c3e9be0f4a0f0adf5054/tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Once they are converted to protected properties, they should be treated like public properties, so they can be converted back to pascal case.
</blockquote></details>

Done

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/171#-:-NrH7wWQAu4Yj-UfsBlz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
