### PR TITLE
Fix usfm population

### PR DESCRIPTION
**Pull request by johnml1135**
This should fix the triple - loop sorted search issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/195)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
Can you add a unit test to cover the issue?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/195#-:-NwBEfm72vbtZgU0eZgu:b3cf5i5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 374 at r2](https://reviewable.io/reviews/sillsdev/machine/195#-NwBi1hoCAOmGW7p2P2s:-NwBi1hoCAOmGW7p2P2t:b-fr9hua) ([raw file](https://github.com/sillsdev/machine/blob/610be606f5cb8aa25ced6756c2e7c696c8147d97/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L374)):*
> ```Smalltalk
>         Assert.That(
>             target,
>             Contains.Substring("\\v 1 \\va 2\\va*\\vp 1 (2)\\vp*Updating later in the book to start.\r\n")
> ```

Damien - what about `\va 2\va* \vp 1 (2)\vp*` with a space between the `*` and the `\`.  is that valid?  It doesn't appear to be handled by the Tokenizer, specifically in adding a new space token.

**Comment by johnml1135** [comment]
done

**Review by ddaspit — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/195)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 374 at r2](https://reviewable.io/reviews/sillsdev/machine/195#-NwBi1hoCAOmGW7p2P2s:-NwFstgs0px8cOa9T_kx:b-6x4ruk) ([raw file](https://github.com/sillsdev/machine/blob/610be606f5cb8aa25ced6756c2e7c696c8147d97/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L374)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Damien - what about `\va 2\va* \vp 1 (2)\vp*` with a space between the `*` and the `\`.  is that valid?  It doesn't appear to be handled by the Tokenizer, specifically in adding a new space token.
</blockquote></details>

What exactly do you mean when you say it isn't handled by the tokenizer?

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 374 at r2](https://reviewable.io/reviews/sillsdev/machine/195#-NwBi1hoCAOmGW7p2P2s:-NwG1JD91NXyG5y8uCts:b-dz0s5a) ([raw file](https://github.com/sillsdev/machine/blob/610be606f5cb8aa25ced6756c2e7c696c8147d97/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L374)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What exactly do you mean when you say it isn't handled by the tokenizer?
</blockquote></details>

https://github.com/sillsdev/serval/issues/377.  We can address is separately.

**Review by ddaspit — COMMENTED** [review]
I was hoping that the unit test would give me some idea as to what this is fixing, but I'm still not sure. Can you give me more details on what issue this is addressing?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/195#-:-NwGlJJT5nnkpcfELNIj:bpeqqq3)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 379 at r3](https://reviewable.io/reviews/sillsdev/machine/195#-NwGnHCu5wzJJUSuQy38:-NwGnHCu5wzJJUSuQy39:b-p59g44) ([raw file](https://github.com/sillsdev/machine/blob/e2b6172b0bc8fa7f7affdd0dbea7a1668bbf1a54/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L379)):*
> ```Smalltalk
> 
>     [Test]
>     public void GetUsfm_Verse_PretranslationsBeforeText()
> ```

I don't quite understand what this is testing. The `UsfmTextUpdater` requires that the rows are already sorted to function properly.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 379 at r3](https://reviewable.io/reviews/sillsdev/machine/195#-NwGnHCu5wzJJUSuQy38:-NwK7TFoAS9fk-J5Y1wD:b3u87zt) ([raw file](https://github.com/sillsdev/machine/blob/e2b6172b0bc8fa7f7affdd0dbea7a1668bbf1a54/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L379)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't quite understand what this is testing. The `UsfmTextUpdater` requires that the rows are already sorted to function properly.
</blockquote></details>

Here is the issue with 2JN - there were something like 6 pretranslation segments before 2JN 1:1, but only 5 spots to put them in the USFM.  The previous algorithm had you incrementing the `_rowIndex` at least once for every time the function was called (for every source segment that attempts to match the pretranslation rows).   This caused there to be a mismatch between the source USFM and the pretranslations, where the _rowIndex was behind of the usfm segments and never caught back up (if the _rowIndex is behind of source segment, you just stop looking).  The changes allow for the function to be called without the _rowIndex incrementing and allow for either one to be ahead.

If you run the new test with your previous code, you can see if fail.

**Review by johnml1135 — COMMENTED** [review]
See comment.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/195#-:-NwK9n26DoSo-ON9az4M:btk743l)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 379 at r3](https://reviewable.io/reviews/sillsdev/machine/195#-NwGnHCu5wzJJUSuQy38:-NwKCH3n4QC3I6i8LP7C:b-v5lf6f) ([raw file](https://github.com/sillsdev/machine/blob/e2b6172b0bc8fa7f7affdd0dbea7a1668bbf1a54/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L379)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Here is the issue with 2JN - there were something like 6 pretranslation segments before 2JN 1:1, but only 5 spots to put them in the USFM.  The previous algorithm had you incrementing the `_rowIndex` at least once for every time the function was called (for every source segment that attempts to match the pretranslation rows).   This caused there to be a mismatch between the source USFM and the pretranslations, where the _rowIndex was behind of the usfm segments and never caught back up (if the _rowIndex is behind of source segment, you just stop looking).  The changes allow for the function to be called without the _rowIndex incrementing and allow for either one to be ahead.

If you run the new test with your previous code, you can see if fail.
</blockquote></details>

* that is, the previous algorithm incremented the row index in effect once for every time it was called (assuming the same or less rows than usfm segments).

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/195#-:-NwKei4k3Xdl7lMpwx-E:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs` line 379 at r3](https://reviewable.io/reviews/sillsdev/machine/195#-NwGnHCu5wzJJUSuQy38:-NwKeYdFEe_RmsjDFXsQ:bnptvn6) ([raw file](https://github.com/sillsdev/machine/blob/e2b6172b0bc8fa7f7affdd0dbea7a1668bbf1a54/tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs#L379)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

* that is, the previous algorithm incremented the row index in effect once for every time it was called (assuming the same or less rows than usfm segments).
</blockquote></details>

I think the thing that threw me off was that the first 5 rows were from a different book.

**Pull request merged**
