### PR TITLE
Fixes Throw error for unbuilt engine #81

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/82)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/82)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs` line 225 at r2](https://reviewable.io/reviews/sillsdev/machine/82#-Ne4bG4I9sxGU9RuYD7t:-Ne4bG4I9sxGU9RuYD7u:b-x0zp3n) ([raw file](https://github.com/sillsdev/machine/blob/fb552e22b612507325facfdad2479f786787acdb/src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs#L225)):*
> ```Smalltalk
>         TranslationEngine engine = await GetEngineAsync(engineId, cancellationToken);
>         if (engine.BuildState != BuildState.None || engine.BuildRevision == 0) //TranslationEngine.Revision - I don't see it used anywhere
>             throw new RpcException(new Status(StatusCode.Aborted, "The engine must be built first"));
> ```

You should not throw an `RpcException` from here. `RpcException` is a gRPC-specific exception. This layer of the system should not be coupled to gRPC. You should probably create a new `EngineNotBuildException` or something like that.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs` line 217 at r2](https://reviewable.io/reviews/sillsdev/machine/82#-Ne4mLGVAEj_GXKrWOGN:-Ne4mLGVAEj_GXKrWOGO:ba6mczy) ([raw file](https://github.com/sillsdev/machine/blob/fb552e22b612507325facfdad2479f786787acdb/src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs#L217)):*
> ```Smalltalk
>         TranslationEngine? engine = await Engines.GetAsync(e => e.EngineId == engineId, cancellationToken);
>         if (engine is null)
>             throw new InvalidOperationException("");
> ```

Shouldn't this throw a better error message?  Like "Couldn't find engine 12345"?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/82)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/82)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs` line 217 at r2](https://reviewable.io/reviews/sillsdev/machine/82#-Ne4mLGVAEj_GXKrWOGN:-Ne8fp0IDp9SH9N9ozeF:b-d0j2n4) ([raw file](https://github.com/sillsdev/machine/blob/fb552e22b612507325facfdad2479f786787acdb/src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs#L217)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Shouldn't this throw a better error message?  Like "Couldn't find engine 12345"?
</blockquote></details>

I added one. It is caught almost immediately, but even so, it seems like it couldn't hurt to include a message. 
___
*[`src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs` line 225 at r2](https://reviewable.io/reviews/sillsdev/machine/82#-Ne4bG4I9sxGU9RuYD7t:-Ne8g-ZmBvzVMIzh7MLH:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/fb552e22b612507325facfdad2479f786787acdb/src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs#L225)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should not throw an `RpcException` from here. `RpcException` is a gRPC-specific exception. This layer of the system should not be coupled to gRPC. You should probably create a new `EngineNotBuildException` or something like that.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/82#-:-Ne8xie20Q6f0RS_w5Aa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
