### PR TITLE
Percent complete

### PR DESCRIPTION
**Pull request by Enkidu93**
Note that this should be merged in parallel with matching PR in serval: https://github.com/sillsdev/serval/pull/78

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)

### CODE REVIEW

**Comment by johnml1135** [comment]
This implements https://github.com/sillsdev/serval/issues/44.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 236 at r1](https://reviewable.io/reviews/sillsdev/machine/52#-NbW2Jpj9FbvH3giDZy_:-NbW2Jpj9FbvH3giDZya:b-6qusdq) ([raw file](https://github.com/sillsdev/machine/blob/5ef722d29c7228fe09314da0d8d2e60ed69a77a4/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L236)):*
> ```Smalltalk
>         return status;
>     }
> ```

The code looks fine - see comments in https://github.com/sillsdev/serval/issues/44 primarily about supporting inferencing.  We need a plan that can work with it very shortly - and LastIteration won't work well.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 116 at r1](https://reviewable.io/reviews/sillsdev/machine/52#-NbWT-9L7Z-r4hEMJb2w:-NbWT-9L7Z-r4hEMJb2x:bdg2xfw) ([raw file](https://github.com/sillsdev/machine/blob/5ef722d29c7228fe09314da0d8d2e60ed69a77a4/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L116)):*
> ```Smalltalk
>                         if (status is not null)
>                         {
>                             await _platformService.UpdateBuildStatusAsync(buildId, (ProgressStatus)status!);
> ```

It shouldn't be necessary to cast `status` or use the null-forgiving operator (!) here.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 222 at r1](https://reviewable.io/reviews/sillsdev/machine/52#-NbWWctOB4jrpnqt0LW8:-NbWWctOB4jrpnqt0LW9:b-ewal02) ([raw file](https://github.com/sillsdev/machine/blob/5ef722d29c7228fe09314da0d8d2e60ed69a77a4/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L222)):*
> ```Smalltalk
>         JsonArray entries = (JsonArray)entriesNode;
>         int numTasksAheadInQueue = 0;
>         foreach (var entry in entries)
> ```

`var` should only be used when the type is explicit elsewhere in the line of code. This helps to make the code more readable.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 228 at r1](https://reviewable.io/reviews/sillsdev/machine/52#-NbWUoPi0NXNqcyk1s9j:-NbWUoPjAQ39JgJCMAos:b-5cgikk) ([raw file](https://github.com/sillsdev/machine/blob/5ef722d29c7228fe09314da0d8d2e60ed69a77a4/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L228)):*
> ```Smalltalk
>             numTasksAheadInQueue++;
>         }
>         ProgressStatus status =
> ```

It is the responsibility of the `ClearMLNmtEngineBuildJob` class to construct the `ProgressStatus` object and status message. I think it would be better to move the construction of the `ProgressStatus` object to that class. This class is only responsible for abstracting calls to the ClearML REST API.

**Review by ddaspit — COMMENTED** [review]
I realized that getting the current position in the queue is actually not as straightforward as querying the position from ClearML. There are actually two queues: the Hangfire queue and the ClearML queue. A job is first placed in the Hangfire queue. Once, it is actually running on the job server, then the job will be placed in the ClearML queue. The main purpose of the Hangfire queue is to put a limit on the number of jobs that Machine needs to monitor on ClearML at the same time.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52#-:-NbWcSE11-w3XmrLO6Ki:bh6m0qd)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
@ddaspit - Should we put them all on the ClearML queue? How many can it handle? Should the be in both queues? What is the best mechanism for this? If we have 50 items in the ClearML queue, can we make one call to see everything in the queue instead of 50 calls? What about multiple instances of Serval using the same ClearML instance (QA, prod)? Should they have different project names such as `Serval-<random 6 digit Hex ID>` or, have them all in the same project but have the experiment name be -? Note that machine does not know what instance it is actually in...

One potential solution could be to query ClearML every 5 seconds once for all queued items that match a specific pattern (that corresponds with the specific instance of Serval) and query MongoDB once for all current builds - and if there is an update to make in MongoDB, make it. If any jobs have been cancelled, aborted or failed in one (ClearML or MongoDB), update the other.

**Comment by johnml1135** [comment]
Update after talking with @Enkidu93 - Let's make the following updates:
* number to dequeue = number of clearML agents on the queue * 2
* Number in the queue is a combination of Hangfire queue and ClearML queue
* % complete can be 90/10 split training/inference - and inference progress can be posted through logging scalar values in ClearML and called from the API.

**Review by ddaspit — COMMENTED** [review]
This sounds good to me.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52#-:-NbpB3jH5VwLSFe1DNCK:brtyo9h)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
@ddaspit  - we made some more updates to the proposed algorithm here (see the last comment): https://github.com/sillsdev/serval/issues/44.  What do you think?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 138 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTTSR79tX3Es2hWHPE:-NcTTSR79tX3Es2hWHPF:btqs9ty) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L138)):*
> ```Smalltalk
>                         }
>                         previousClearMLTasks = currentClearMLTasks;
>                         goto case ClearMLTaskStatus.InProgress;
> ```

Let's remove the queue logic for right now and commit it to a branch to be dealt with later.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 152 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTThwU9zgldUOmT6NJ:-NcTThwU9zgldUOmT6NK:b-5l0nz3) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L152)):*
> ```Smalltalk
>                                 clearMLTask.LastIteration,
>                                 (clearMLTask.LastIteration / (float)_options.CurrentValue.MaxSteps) * 90.0
>                                     + (inferencePercentComplete / 100.0f) * 10.0,
> ```

To account for potential early stopping, if inferencePercentComplete > 0, assume training is done and just put in the 90%.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 205 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTUWDE3bpot4qJIrgz:-NcTUWDE3bpot4qJIrh-:b-5p3jc2) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L205)):*
> ```Smalltalk
>     )
>     {
>         var body = new JsonObject { ["id"] = taskId };
> ```

Can you add some comments as to why hashes are used and how the data is extracted?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 198 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTUk2aD0Rp-9Gymofb:-NcTUk2aD0Rp-9Gymofc:b-67prfl) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L198)):*
> ```Smalltalk
>     }
> 
>     private async Task<string?> GetMetricAsync(
> ```

rename to GetTaskMetricAsyc

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 267 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTVE9I6w1kT3axNlZB:-NcTVE9I6w1kT3axNlZC:b-hq66lp) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L267)):*
> ```Smalltalk
>                 tasksAheadInQueue.Add(name);
>         }
>         return tasksAheadInQueue;
> ```

Remove this queue logic as specified above.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 236 at r1](https://reviewable.io/reviews/sillsdev/machine/52#-NbW2Jpj9FbvH3giDZy_:-NcTVdQ10NZ4L456pxSw:bz4wr0l) ([raw file](https://github.com/sillsdev/machine/blob/5ef722d29c7228fe09314da0d8d2e60ed69a77a4/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L236)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The code looks fine - see comments in https://github.com/sillsdev/serval/issues/44 primarily about supporting inferencing.  We need a plan that can work with it very shortly - and LastIteration won't work well.
</blockquote></details>

It should work for now - when inferencing is added, we can just have inferencing take all 100% of the progress.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/IClearMLService.cs` line 35 at r2](https://reviewable.io/reviews/sillsdev/machine/52#-NcTVnVtA-GX7wekYxzc:-NcTVnVtA-GX7wekYxzd:ba3dfmt) ([raw file](https://github.com/sillsdev/machine/blob/cd720b8731b597c7961bd8b468086d7e6b345d30/src/SIL.Machine.AspNetCore/Services/IClearMLService.cs#L35)):*
> ```Smalltalk
>         CancellationToken cancellationToken = default
>     );
> ```

Remove.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> Dismissed @ddaspit from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)* status: all files reviewed, 7 unresolved discussions (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
@johnml1135 I've removed the queue logic and, I believe, responded to the other reviews. Let me know if anything needs to be changed as you make alterations in machine.py.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)* status: all files reviewed, 7 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 112 at r3](https://reviewable.io/reviews/sillsdev/machine/52#-Nd2HmY9CUsuOoN7fMrC:-Nd2HmY9CUsuOoN7fMrD:b6bf1xq) ([raw file](https://github.com/sillsdev/machine/blob/3a0ab7b017b09cf968a759db5ce3b56101d0efec/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L112)):*
> ```Smalltalk
>                 {
>                     case ClearMLTaskStatus.InProgress:
>                         float inferencePercentComplete = await _clearMLService.GetInferencePercentCompleteAsync(
> ```

Do we need a separate request to get this information? Can we get it in the `GetTaskAsync` call?

**Comment by Enkidu93** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 112 at r3](https://reviewable.io/reviews/sillsdev/machine/52#-Nd2HmY9CUsuOoN7fMrC:-NdFt6G_5y_TkKsJ2wPC:bexaip2) ([raw file](https://github.com/sillsdev/machine/blob/3a0ab7b017b09cf968a759db5ce3b56101d0efec/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L112)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we need a separate request to get this information? Can we get it in the `GetTaskAsync` call?
</blockquote></details>

(Sorry for the delay). We could - if you're OK with me changing the `ClearMLTask` data class. I'm not sure if it would deserialize properly without some help since the metric is stored in a serialized hashmap of hashmaps. (Thus, MD5 popping up in the ClearML service). I can pursue that if you like; just give me a thumbs up.

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52#-:-NdGBuRwCYLhowSE56g_:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 112 at r3](https://reviewable.io/reviews/sillsdev/machine/52#-Nd2HmY9CUsuOoN7fMrC:-NdGhRXPEfTP2g9Je3ix:b-8og4d8) ([raw file](https://github.com/sillsdev/machine/blob/3a0ab7b017b09cf968a759db5ce3b56101d0efec/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L112)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

(Sorry for the delay). We could - if you're OK with me changing the `ClearMLTask` data class. I'm not sure if it would deserialize properly without some help since the metric is stored in a serialized hashmap of hashmaps. (Thus, MD5 popping up in the ClearML service). I can pursue that if you like; just give me a thumbs up.
</blockquote></details>

I think it is worth checking out. We want to minimize the number of requests we make to ClearML as much as possible.

**Comment by Enkidu93** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/52)_ status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93)
> 
> _[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 112 at r3](https://reviewable.io/reviews/sillsdev/machine/52#-Nd2HmY9CUsuOoN7fMrC:-NdGhRXPEfTP2g9Je3ix:b-8og4d8) ([raw file](https://github.com/sillsdev/machine/blob/3a0ab7b017b09cf968a759db5ce3b56101d0efec/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L112)):_
> Previously, Enkidu93 (Eli C. Lowry) wrote…
> 
> I think it is worth checking out. We want to minimize the number of requests we make to ClearML as much as possible.

I'll check it out.

**Comment by Enkidu93** [comment]
@johnml1135 Are you still working on the machine.py end of this? Any updates?

**Comment by Enkidu93** [comment]
Finished [here](https://github.com/sillsdev/machine/pull/112).

**Pull request closed without merging**
