### PR TITLE
USFM column index issue

### PR DESCRIPTION
**Pull request by johnml1135**
This is to fix: https://github.com/sillsdev/serval/issues/424.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/220)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/220)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine/220#-O1T4K7N4aau39DPDEQ4:-O1T4K7O6htKjBt6_uvl:bnnzv7q) ([raw file](https://github.com/sillsdev/machine/blob/f648aa462667346391fa2b349e0fd6902d0faf9a/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L53)):*
> ```Smalltalk
> 
>     [Test]
>     public void GetRows_Ending_ParagraphMarker()
> ```

I think it would be better to add a unit test to `UsfmTokenizerTests` instead of this test fixture.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine/220#-O1T4K7N4aau39DPDEQ4:-O1T9_4X6pIcMg6wLZo3:b-dmbz9m) ([raw file](https://github.com/sillsdev/machine/blob/f648aa462667346391fa2b349e0fd6902d0faf9a/tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs#L53)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think it would be better to add a unit test to `UsfmTokenizerTests` instead of this test fixture.
</blockquote></details>

This is what I think is needed.  Is this what you were thinking?

**Review by ddaspit — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/220)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs` line 75 at r2](https://reviewable.io/reviews/sillsdev/machine/220#-O1TBQMiBM9HkbYqci9B:-O1TBQMj7FTPmjCpPufg:btvmfa3) ([raw file](https://github.com/sillsdev/machine/blob/156cbecd90000c45dfd25988c02c8c06e97eaf35/tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs#L75)):*
> ```Smalltalk
>     private static TextRow[] GetRows(string usfm, bool includeMarkers = false, bool includeAllText = false)
>     {
>         UsfmMemoryText text =
> ```

Instead of creating a `UsfmMemoryText`, can you call the `UsfmTokenizer` directly? I just want to directly test the `UsfmTokenizer` instead of testing it indirectly through the `UsfmMemoryText`.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs` line 75 at r2](https://reviewable.io/reviews/sillsdev/machine/220#-O1TBQMiBM9HkbYqci9B:-O1TI_f919Vca--JmAH0:b-87tsrt) ([raw file](https://github.com/sillsdev/machine/blob/156cbecd90000c45dfd25988c02c8c06e97eaf35/tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs#L75)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Instead of creating a `UsfmMemoryText`, can you call the `UsfmTokenizer` directly? I just want to directly test the `UsfmTokenizer` instead of testing it indirectly through the `UsfmMemoryText`.
</blockquote></details>

I see

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/220)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs` line 59 at r3](https://reviewable.io/reviews/sillsdev/machine/220#-O1TKtU296PhyzSLv2uX:-O1TKtU296PhyzSLv2uY:b-cdwtel) ([raw file](https://github.com/sillsdev/machine/blob/24cc6b86bf91f8865369494aa3c4369d66575b12/tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs#L59)):*
> ```Smalltalk
> \v 1 Descriptive title\x - \xo 18:16 \xt  hello world\x*\p
> ";
>         new UsfmTokenizer().Tokenize(usfm);
> ```

It would be good to at least assert the expected number of tokens.

**Comment by johnml1135** [comment]
*[`tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs` line 59 at r3](https://reviewable.io/reviews/sillsdev/machine/220#-O1TKtU296PhyzSLv2uX:-O1TMFc_BNbdlNYXqgNS:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/24cc6b86bf91f8865369494aa3c4369d66575b12/tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs#L59)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be good to at least assert the expected number of tokens.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/220#-:-O1TMRrF4WI5OeVRmOH4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
