### PR TITLE
Only delete S3 branch stuff on production.  Staging and development c…

### PR DESCRIPTION
**Pull request by johnml1135**
…an be deleted manually - but are often needed for debugging.

https://github.com/sillsdev/serval/issues/190

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/120)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
This should configured using appsettings.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/120#-:-NhChcew2ebxsfEnJnUr:b-aw7ars)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/120)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/120#-NhDT23m9j9Plf4CCzWH:-NhDT23m9j9Plf4CCzWI:b9fakaw) ([raw file](https://github.com/sillsdev/machine/blob/44396c0f986fba7e77ad5f1a6ddae0a479d14484/src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs#L64)):*
> ```Smalltalk
>         try
>         {
>             if (_sharedFileOptions.DeleteFilesOnCompletion)
> ```

We also cleanup the build files in `NmtPreprocessBuildJob` and `ClearMLMonitorService`. Maybe we should only cleanup the build files if a build completes successfully. We could do this in every deployment environment, so the config wouldn't be needed.

**Comment by johnml1135** [comment]
Is that better?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/120#-NhDT23m9j9Plf4CCzWH:-NhDhFpw6HfnNyXSdwsb:b-3zo289) ([raw file](https://github.com/sillsdev/machine/blob/44396c0f986fba7e77ad5f1a6ddae0a479d14484/src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We also cleanup the build files in `NmtPreprocessBuildJob` and `ClearMLMonitorService`. Maybe we should only cleanup the build files if a build completes successfully. We could do this in every deployment environment, so the config wouldn't be needed.
</blockquote></details>

Can the postprocess build job always run?  I like your idea of removing them if they are successful but writing to the S3 bucket if there is a failure.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/120)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/120#-NhDT23m9j9Plf4CCzWH:-NhDrDyq-iDXnHxmkbU2:bz4ie0j) ([raw file](https://github.com/sillsdev/machine/blob/44396c0f986fba7e77ad5f1a6ddae0a479d14484/src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs#L64)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can the postprocess build job always run?  I like your idea of removing them if they are successful but writing to the S3 bucket if there is a failure.
</blockquote></details>

If the build completes successfully, the postprocess job will always run. We would probably also want to delete the files if the build is canceled.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/120#-NhDT23m9j9Plf4CCzWH:-NhRf9Cx1WvsWJoEU2MU:b-qgnkxg) ([raw file](https://github.com/sillsdev/machine/blob/44396c0f986fba7e77ad5f1a6ddae0a479d14484/src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If the build completes successfully, the postprocess job will always run. We would probably also want to delete the files if the build is canceled.
</blockquote></details>

I believe the changes now reflect the intent:
* Don't delete if there is a fault
* Delete if successful or if canceled
* Remove environment variable choice

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/120#-:-NhSUQHxBRb1-_mCfi0M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
