### PR TITLE
#75 - don't fail nmt job on delete failing

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/76)

### CODE REVIEW

**Review by Enkidu93 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/76#-:-NdjuPbc12m-6lcyK2iL:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/76)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ddaspit — COMMENTED** [review]
I added a retroactive comment.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/76#-:-Ndk6SDLCTnJejjYp9JH:b-i0i1lm)* status: all files reviewed, 1 unresolved discussion

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 150 at r1](https://reviewable.io/reviews/sillsdev/machine/76#-Ndk6Due0nkkuk0a7Ywb:-Ndk6Due0nkkuk0a7Ywc:b-sc953f) ([raw file](https://github.com/sillsdev/machine/blob/a736a896f4aa010ac3a7be61ef19210431c2c303/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L150)):*
> ```Smalltalk
>             catch (AmazonS3Exception e)
>             {
>                 _logger.LogError(
> ```

You can pass the exception directly to the `LogError` method. This way the stack trace wouldn't be lost. It is a good idea to always pass the exception when logging an error.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 150 at r1](https://reviewable.io/reviews/sillsdev/machine/76#-Ndk6Due0nkkuk0a7Ywb:-Ndk6tVS4W8f_NtuW66e:b-poakls) ([raw file](https://github.com/sillsdev/machine/blob/a736a896f4aa010ac3a7be61ef19210431c2c303/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L150)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can pass the exception directly to the `LogError` method. This way the stack trace wouldn't be lost. It is a good idea to always pass the exception when logging an error.
</blockquote></details>

By the time it gets there, we already know what happened (we have read and write privileges, but not delete).  The error stack trace becomes less valuable.  That is why I chose to not include it.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/76)* status: all files reviewed, 1 unresolved discussion

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs` line 150 at r1](https://reviewable.io/reviews/sillsdev/machine/76#-Ndk6Due0nkkuk0a7Ywb:-Ndk8iMY8E1sr6kdtXv4:bd6offp) ([raw file](https://github.com/sillsdev/machine/blob/a736a896f4aa010ac3a7be61ef19210431c2c303/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L150)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

By the time it gets there, we already know what happened (we have read and write privileges, but not delete).  The error stack trace becomes less valuable.  That is why I chose to not include it.
</blockquote></details>

You should always use [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object())) overload when logging an exception. It is just good practice.

**Pull request merged**
