### PR TITLE
Ignore a note that occurs right after \id marker

### PR DESCRIPTION
**Pull request by ddaspit**
- fixes https://github.com/sillsdev/serval/issues/393

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/203)

### CODE REVIEW

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/203)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/SIL.Machine/Corpora/UsfmTokenizer.cs` line 393 at r1](https://reviewable.io/reviews/sillsdev/machine/203#-NzEnjst6OfhoB_jkrUC:-NzEnjsu4YEvZ4ggssUz:b-r0eh93) ([raw file](https://github.com/sillsdev/machine/blob/97435197d2940b1170d8c5f44a75db66c8592b97/src/SIL.Machine/Corpora/UsfmTokenizer.cs#L393)):*
> ```Smalltalk
>                             if (
>                                 usfm[usfm.Length - 1] == ' '
>                                 && ((prevToken != null && prevToken.ToUsfm().Trim() != "") || !tokensHaveWhitespace)
> ```

What's the point of this logic here? I'm not quite getting it.

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/203)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/SIL.Machine/Corpora/UsfmTokenizer.cs` line 393 at r1](https://reviewable.io/reviews/sillsdev/machine/203#-NzEnjst6OfhoB_jkrUC:-NzTS1MO4OtNoXhya0LR:b-e8uhhx) ([raw file](https://github.com/sillsdev/machine/blob/6cc0bc71baf63a174ee7054902b8543dcd9c13e8/src/SIL.Machine/Corpora/UsfmTokenizer.cs#L393)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

What's the point of this logic here? I'm not quite getting it.
</blockquote></details>

Sorry, I haven't approved this yet because I was hoping to get a better handle on this logic here. Could you explain what's going on, @ddaspit ?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/203)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/SIL.Machine/Corpora/UsfmTokenizer.cs` line 393 at r1](https://reviewable.io/reviews/sillsdev/machine/203#-NzEnjst6OfhoB_jkrUC:-NzTe0kO8zDrwIaqhrdn:bowjv85) ([raw file](https://github.com/sillsdev/machine/blob/6cc0bc71baf63a174ee7054902b8543dcd9c13e8/src/SIL.Machine/Corpora/UsfmTokenizer.cs#L393)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry, I haven't approved this yet because I was hoping to get a better handle on this logic here. Could you explain what's going on, @ddaspit ?
</blockquote></details>

This checks to see if we need to strip off the space at the end before a newline. There are two cases that we have to handle:
1. The tokens contain whitespace. This occurs when we are trying to preserve the whitespace from the original USFM.
2. The tokens do not contain whitespace. This occurs when we want to normalize the whitespace.

This logic is preserved from the original USFM parser code in Paratext.

**Review by Enkidu93 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/203)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/SIL.Machine/Corpora/UsfmTokenizer.cs` line 393 at r1](https://reviewable.io/reviews/sillsdev/machine/203#-NzEnjst6OfhoB_jkrUC:-NzTiVqSDq-I9wa1Fri0:b-9755fn) ([raw file](https://github.com/sillsdev/machine/blob/6cc0bc71baf63a174ee7054902b8543dcd9c13e8/src/SIL.Machine/Corpora/UsfmTokenizer.cs#L393)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This checks to see if we need to strip off the space at the end before a newline. There are two cases that we have to handle:
1. The tokens contain whitespace. This occurs when we are trying to preserve the whitespace from the original USFM.
2. The tokens do not contain whitespace. This occurs when we want to normalize the whitespace.

This logic is preserved from the original USFM parser code in Paratext.
</blockquote></details>

Thank you!

**Pull request merged**
