### PR TITLE
Drive health

### PR DESCRIPTION
**Pull request by johnml1135**
Resolves https://github.com/sillsdev/machine/issues/141 and https://github.com/sillsdev/serval/issues/243.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine/156)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/156)* status: all files reviewed, 4 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 224 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuGT7I1TLS4M7hcEfF:-NnuGT7I1TLS4M7hcEfG:b-m4xhzn) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L224)):*
> ```Smalltalk
>     public static IMachineBuilder AddMongoDataAccess(this IMachineBuilder builder, string? connectionString = null)
>     {
>         connectionString ??= builder.Configuration!.GetConnectionString("Mongo");
> ```

Please avoid using the null-forgiving operator when possible. Throw an exception if necessary.
___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 375 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuIRO21kYA9Y2VjAnZ:-NnuIRO21kYA9Y2VjAn_:bwbak35) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L375)):*
> ```Smalltalk
> 
>             string EnginesDir = builder.Configuration
>                 .GetSection(SmtTransferEngineOptions.Key)!
> ```

I don't think that the null-forgiving operators are needed here.
___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 378 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuIYUWCXVEOiPqY8D9:-NnuIYUWCXVEOiPqY8DA:brpytxn) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L378)):*
> ```Smalltalk
>                 .GetValue<string>("EnginesDir")!;
> 
>             string driveLetter = Path.GetPathRoot(EnginesDir)![..1];
> ```

Please avoid using the null-forgiving operator when possible.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuFdPw6DkZIIltERXv:-NnuFdPw6DkZIIltERXw:b6jy5ii) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L13)):*
> ```Smalltalk
>     // to know well ahead of time if something is wrong.
>     private static readonly TimeSpan RefreshPeriod = TimeSpan.FromSeconds(3600);
>     private string? _authToken = "";
> ```

I don't think it is ever possible for `_authToken` to be `null`.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/156)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 224 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuGT7I1TLS4M7hcEfF:-NoHk1is7qodQpvfGrxT:bzerg8t) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L224)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please avoid using the null-forgiving operator when possible. Throw an exception if necessary.
</blockquote></details>

Does that meet your expectations?

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 378 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuIYUWCXVEOiPqY8D9:-NoHkOYQ4ZNiUILb1PPx:bt2vr1b) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L378)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please avoid using the null-forgiving operator when possible.
</blockquote></details>

Fixed.

**Comment by johnml1135** [comment]
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/156#-NnuFdPw6DkZIIltERXv:-NoHkRzCAvEuHJ4reQ0U:bhsz6lg) ([raw file](https://github.com/sillsdev/machine/blob/9f5734a9db53f0b0e1c353639f7fd42bd13fdb34/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think it is ever possible for `_authToken` to be `null`.
</blockquote></details>

I revised the logic a bit to handle edge cases better.  Specifically, if we can't get the auth token when first starting up, we should crash out.  If refreshing fails, we should keep laboring on as long as possible.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/156#-:-NoI72NFEHRG56ovz4tv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
